// react-app/src/pages/AdminPage.tsx
import { useQuery } from '@tanstack/react-query';
import {
  BarChart3,
  CheckCircle2,
  Clock3,
  CreditCard,
  Inbox,
  RefreshCw,
  Shield,
  Users,
  Wallet,
} from 'lucide-react';
import * as adminApi from '@/api/admin';
import { queryKeys } from '@/api/queryKeys';
import { EmptyState } from '@/components/common/EmptyState';
import { ErrorBoundary } from '@/components/common/ErrorBoundary';
import { KPICard } from '@/components/common/KPICard';
import { PageHeader } from '@/components/common/PageHeader';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import type {
  AdminKpisDto,
  AdminOverviewDto,
  AdminUserSnapshotDto,
} from '@/types';
import { resolveApiErrorMessage } from '@/utils/errors';
import { formatDateTime, formatNumber } from '@/utils/format';

const EMPTY_KPIS: AdminKpisDto = {
  totalUsers: 0,
  activeSubscriptions: 0,
  activeSubscriptionsRatePercent: 0,
  onboardingCompletedUsers: 0,
  onboardingCompletionRatePercent: 0,
  totalAccounts: 0,
  totalTransactions: 0,
  transactionsLast30Days: 0,
};

function resolveUserLabel(name: string, email: string | null): string {
  if (name.trim().length > 0) {
    return name;
  }

  if (email?.trim()) {
    return email;
  }

  return 'Без имени';
}

function formatDateTimeSafe(value: string | null): string {
  if (!value) {
    return '—';
  }

  try {
    return formatDateTime(value);
  } catch {
    return '—';
  }
}

function StatusBadge({
  label,
  tone,
}: {
  label: string;
  tone: 'default' | 'success' | 'warning' | 'info';
}) {
  const toneClassName =
    tone === 'success'
      ? 'border-[var(--ft-success-500)]/30 bg-[color-mix(in_srgb,var(--ft-success-500)_10%,transparent)] text-[var(--ft-success-400)]'
      : tone === 'warning'
        ? 'border-[var(--ft-warning-500)]/30 bg-[color-mix(in_srgb,var(--ft-warning-500)_10%,transparent)] text-[var(--ft-warning-300)]'
        : tone === 'info'
          ? 'border-primary/25 bg-primary/10 text-primary'
          : 'border-border bg-background/40 text-muted-foreground';

  return (
    <Badge variant="outline" className={toneClassName}>
      {label}
    </Badge>
  );
}

function AdminUsersTable({ users }: { users: AdminUserSnapshotDto[] }) {
  return (
    <div className="overflow-hidden rounded-xl border border-border bg-card/80 shadow-[var(--ft-shadow-sm)]">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Email</TableHead>
            <TableHead>Имя</TableHead>
            <TableHead>Роль</TableHead>
            <TableHead>Подписка</TableHead>
            <TableHead>Онбординг</TableHead>
            <TableHead>Telegram</TableHead>
            <TableHead className="text-right">Транзакции</TableHead>
            <TableHead>Последняя активность</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {users.map((user) => (
            <TableRow key={user.userId}>
              <TableCell className="font-medium text-foreground">
                {user.email ?? '—'}
              </TableCell>
              <TableCell>{resolveUserLabel(user.name, user.email)}</TableCell>
              <TableCell>
                <StatusBadge
                  label={user.isOwner ? 'Owner' : 'User'}
                  tone={user.isOwner ? 'info' : 'default'}
                />
              </TableCell>
              <TableCell>
                <StatusBadge
                  label={user.hasActiveSubscription ? 'Активна' : 'Неактивна'}
                  tone={user.hasActiveSubscription ? 'success' : 'warning'}
                />
              </TableCell>
              <TableCell>
                <StatusBadge
                  label={user.isOnboardingCompleted ? 'Пройден' : 'Не пройден'}
                  tone={user.isOnboardingCompleted ? 'success' : 'default'}
                />
              </TableCell>
              <TableCell>
                {user.isTelegramLinked ? 'Привязан' : 'Не привязан'}
              </TableCell>
              <TableCell className="text-right">
                {formatNumber(user.transactionsCount, 0)}
              </TableCell>
              <TableCell>{formatDateTimeSafe(user.lastTransactionAtUtc)}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

function hasOverviewData(overview: AdminOverviewDto | undefined): boolean {
  if (!overview) {
    return false;
  }

  return (
    overview.users.length > 0 ||
    Object.values(overview.kpis).some((value) => value > 0)
  );
}

export default function AdminPage() {
  const overviewQuery = useQuery({
    queryKey: queryKeys.admin.overview(),
    queryFn: adminApi.getAdminOverview,
    staleTime: 60_000,
  });

  const overview = overviewQuery.data;
  const kpis = overview?.kpis ?? EMPTY_KPIS;
  const showInlineError = overviewQuery.isError && Boolean(overview);
  const showBlockingError =
    overviewQuery.isError && !overviewQuery.isPending && !overview;
  const showEmptyState =
    !overviewQuery.isPending && !overviewQuery.isError && !hasOverviewData(overview);

  const kpiCards = [
    {
      key: 'users',
      label: 'Пользователи',
      value: formatNumber(kpis.totalUsers, 0),
      icon: <Users className="size-4" />,
      variant: 'default' as const,
      trend: null,
    },
    {
      key: 'subscriptions',
      label: 'Активные подписки',
      value: formatNumber(kpis.activeSubscriptions, 0),
      icon: <CreditCard className="size-4" />,
      variant: 'success' as const,
      trend: {
        value: kpis.activeSubscriptionsRatePercent,
        direction:
          kpis.activeSubscriptionsRatePercent > 0 ? 'up' : 'neutral',
        label: 'от всех пользователей',
      } as const,
    },
    {
      key: 'onboarding',
      label: 'Прошли онбординг',
      value: formatNumber(kpis.onboardingCompletedUsers, 0),
      icon: <CheckCircle2 className="size-4" />,
      variant: 'success' as const,
      trend: {
        value: kpis.onboardingCompletionRatePercent,
        direction:
          kpis.onboardingCompletionRatePercent > 0 ? 'up' : 'neutral',
        label: 'от всех пользователей',
      } as const,
    },
    {
      key: 'accounts',
      label: 'Счета',
      value: formatNumber(kpis.totalAccounts, 0),
      icon: <Wallet className="size-4" />,
      variant: 'default' as const,
      trend: null,
    },
    {
      key: 'transactions-all',
      label: 'Транзакции (всего)',
      value: formatNumber(kpis.totalTransactions, 0),
      icon: <BarChart3 className="size-4" />,
      variant: 'default' as const,
      trend: null,
    },
    {
      key: 'transactions-30d',
      label: 'Транзакции (30 дней)',
      value: formatNumber(kpis.transactionsLast30Days, 0),
      icon: <Clock3 className="size-4" />,
      variant: 'warning' as const,
      trend: null,
    },
  ];

  return (
    <ErrorBoundary>
      <div className="flex flex-col gap-5 p-4 sm:p-6 lg:px-8">
        <PageHeader
          title="Админ-панель"
          subtitle="Сводка по пользователям, транзакциям и активности сервиса"
          className="mb-0"
          actions={
            <Button
              className="min-h-[44px] rounded-lg px-4"
              onClick={() => void overviewQuery.refetch()}
              disabled={overviewQuery.isFetching}
            >
              <RefreshCw
                className={`size-4 ${overviewQuery.isFetching ? 'animate-spin' : ''}`}
              />
              Обновить
            </Button>
          }
        />

        {showBlockingError ? (
          <section className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-4 text-sm">
            <div className="font-medium text-foreground">
              Не удалось загрузить админ-панель
            </div>
            <div className="mt-1 text-muted-foreground">
              {resolveApiErrorMessage(
                overviewQuery.error,
                'Попробуйте повторить запрос.',
              )}
            </div>
            <Button
              className="mt-3 min-h-[44px] rounded-lg px-4"
              variant="outline"
              onClick={() => void overviewQuery.refetch()}
            >
              Повторить
            </Button>
          </section>
        ) : null}

        {showInlineError ? (
          <section className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-4 text-sm">
            <div className="font-medium text-foreground">
              Не удалось обновить админ-панель
            </div>
            <div className="mt-1 text-muted-foreground">
              {resolveApiErrorMessage(
                overviewQuery.error,
                'Показаны последние доступные данные.',
              )}
            </div>
          </section>
        ) : null}

        <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {kpiCards.map((card) => (
            <KPICard
              key={card.key}
              label={card.label}
              value={card.value}
              icon={card.icon}
              variant={card.variant}
              trend={card.trend}
              loading={overviewQuery.isPending}
            />
          ))}
        </section>

        {showEmptyState ? (
          <EmptyState
            icon={<Inbox />}
            title="Данных для админ-панели пока нет"
            description="Когда в приложении появятся пользователи и транзакции, здесь отобразится сводка."
            className="min-h-[320px] rounded-xl border border-border bg-card/70"
          />
        ) : null}

        {overviewQuery.isPending ? (
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <Shield className="size-4 text-primary" />
              <h2 className="text-lg font-semibold text-foreground">
                Пользователи (срез)
              </h2>
            </div>
            <Skeleton className="h-[280px] rounded-xl" />
          </section>
        ) : overview?.users.length ? (
          <section className="space-y-3">
            <header className="flex flex-wrap items-baseline justify-between gap-2">
              <h2 className="text-lg font-semibold text-foreground">
                Пользователи (срез)
              </h2>
              <span className="text-sm text-muted-foreground">
                Первые 20 по последней активности
              </span>
            </header>

            <AdminUsersTable users={overview.users} />
          </section>
        ) : null}
      </div>
    </ErrorBoundary>
  );
}

// vue-app/src/pages/AdminPage.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import Column from 'primevue/column';
import DataTable from 'primevue/datatable';
import Message from 'primevue/message';
import Skeleton from 'primevue/skeleton';
import Tag from 'primevue/tag';
import KPICard from '../components/common/KPICard.vue';
import PageHeader from '../components/common/PageHeader.vue';
import PageContainer from '../components/layout/PageContainer.vue';
import { useAdminOverviewData } from '../composables/useAdminOverviewData';
import UiButton from '../ui/UiButton.vue';

const {
  overview,
  error,
  isLoading,
  isEmpty,
  isError,
  isSuccess,
  loadOverview,
  retry,
} = useAdminOverviewData();

const kpis = computed(() => overview.value?.kpis ?? {
  totalUsers: 0,
  activeSubscriptions: 0,
  activeSubscriptionsRatePercent: 0,
  onboardingCompletedUsers: 0,
  onboardingCompletionRatePercent: 0,
  totalAccounts: 0,
  totalTransactions: 0,
  transactionsLast30Days: 0,
});

const kpiCards = computed(() => ([
  {
    key: 'total-users',
    title: 'Пользователи',
    value: formatNumber(kpis.value.totalUsers),
    icon: 'pi-users',
    trend: null,
    trendLabel: '',
    variant: 'default' as const,
  },
  {
    key: 'active-subscriptions',
    title: 'Активные подписки',
    value: formatNumber(kpis.value.activeSubscriptions),
    icon: 'pi-credit-card',
    trend: kpis.value.activeSubscriptionsRatePercent,
    trendLabel: 'от всех пользователей',
    variant: 'success' as const,
  },
  {
    key: 'onboarding-completed',
    title: 'Прошли онбординг',
    value: formatNumber(kpis.value.onboardingCompletedUsers),
    icon: 'pi-check-circle',
    trend: kpis.value.onboardingCompletionRatePercent,
    trendLabel: 'от всех пользователей',
    variant: 'success' as const,
  },
  {
    key: 'total-accounts',
    title: 'Счета',
    value: formatNumber(kpis.value.totalAccounts),
    icon: 'pi-wallet',
    trend: null,
    trendLabel: '',
    variant: 'default' as const,
  },
  {
    key: 'total-transactions',
    title: 'Транзакции (всего)',
    value: formatNumber(kpis.value.totalTransactions),
    icon: 'pi-chart-bar',
    trend: null,
    trendLabel: '',
    variant: 'default' as const,
  },
  {
    key: 'transactions-30d',
    title: 'Транзакции (30 дней)',
    value: formatNumber(kpis.value.transactionsLast30Days),
    icon: 'pi-clock',
    trend: null,
    trendLabel: '',
    variant: 'warning' as const,
  },
]));

const users = computed(() => overview.value?.users ?? []);

function formatNumber(value: number): string {
  return new Intl.NumberFormat('ru-RU', {
    maximumFractionDigits: 0,
  }).format(value);
}

function formatDateTime(value: string | null): string {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleString('ru-RU');
}

function resolveUserLabel(name: string, email: string | null): string {
  if (name && name.trim().length > 0) return name;
  if (email && email.trim().length > 0) return email;
  return 'Без имени';
}

function subscriptionStatusSeverity(isActive: boolean) {
  return isActive ? 'success' : 'warning';
}

function onboardingStatusSeverity(isCompleted: boolean) {
  return isCompleted ? 'success' : 'secondary';
}

function ownerStatusSeverity(isOwner: boolean) {
  return isOwner ? 'info' : 'secondary';
}

onMounted(() => {
  void loadOverview();
});
</script>

<template>
  <PageContainer class="admin-page">
    <PageHeader
      title="Админ-панель"
      subtitle="Сводка по пользователям, транзакциям и активности сервиса"
    >
      <template #actions>
        <UiButton
          label="Обновить"
          icon="pi pi-refresh"
          :loading="isLoading"
          @click="retry"
        />
      </template>
    </PageHeader>

    <Message
      v-if="isError"
      severity="error"
      :closable="false"
      icon="pi pi-exclamation-triangle"
    >
      <div class="admin-page__error-content">
        <span>{{ error ?? 'Не удалось загрузить админ-панель.' }}</span>
        <UiButton
          label="Повторить"
          icon="pi pi-refresh"
          size="sm"
          @click="retry"
        />
      </div>
    </Message>

    <section class="admin-page__kpis">
      <KPICard
        v-for="card in kpiCards"
        :key="card.key"
        :title="card.title"
        :value="card.value"
        :icon="card.icon"
        :variant="card.variant"
        :trend="card.trend"
        :trend-label="card.trendLabel"
        :loading="isLoading"
      />
    </section>

    <Message
      v-if="isEmpty && !isLoading"
      severity="info"
      :closable="false"
      icon="pi pi-inbox"
    >
      Данных для админ-панели пока нет.
    </Message>

    <section
      v-if="isSuccess && !isLoading"
      class="admin-page__section"
    >
      <header class="admin-page__section-header">
        <h2 class="admin-page__section-title">
          Пользователи (срез)
        </h2>
        <span class="admin-page__section-hint">Первые 20 по последней активности</span>
      </header>

      <DataTable
        :value="users"
        data-key="userId"
        class="admin-page__table"
        scrollable
      >
        <Column
          field="email"
          header="Email"
        />
        <Column header="Имя">
          <template #body="{ data }">
            {{ resolveUserLabel(data.name, data.email) }}
          </template>
        </Column>
        <Column header="Роль">
          <template #body="{ data }">
            <Tag
              :value="data.isOwner ? 'Owner' : 'User'"
              :severity="ownerStatusSeverity(data.isOwner)"
            />
          </template>
        </Column>
        <Column header="Подписка">
          <template #body="{ data }">
            <Tag
              :value="data.hasActiveSubscription ? 'Активна' : 'Неактивна'"
              :severity="subscriptionStatusSeverity(data.hasActiveSubscription)"
            />
          </template>
        </Column>
        <Column header="Онбординг">
          <template #body="{ data }">
            <Tag
              :value="data.isOnboardingCompleted ? 'Пройден' : 'Не пройден'"
              :severity="onboardingStatusSeverity(data.isOnboardingCompleted)"
            />
          </template>
        </Column>
        <Column header="Telegram">
          <template #body="{ data }">
            {{ data.isTelegramLinked ? 'Привязан' : 'Не привязан' }}
          </template>
        </Column>
        <Column header="Транзакции">
          <template #body="{ data }">
            {{ formatNumber(data.transactionsCount) }}
          </template>
        </Column>
        <Column header="Последняя активность">
          <template #body="{ data }">
            {{ formatDateTime(data.lastTransactionAtUtc) }}
          </template>
        </Column>
      </DataTable>
    </section>

    <section
      v-if="isLoading"
      class="admin-page__loading-tables"
    >
      <Skeleton
        height="260px"
        width="100%"
      />
    </section>
  </PageContainer>
</template>

<style scoped>
.admin-page {
  gap: var(--ft-space-6);
}

.admin-page__error-content {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-3);
  align-items: center;
  justify-content: space-between;
}

.admin-page__kpis {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: var(--ft-space-4);
}

.admin-page__section {
  display: grid;
  gap: var(--ft-space-3);
}

.admin-page__section-header {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-2);
  align-items: baseline;
  justify-content: space-between;
}

.admin-page__section-title {
  margin: 0;
  font-size: var(--ft-text-xl);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.admin-page__section-hint {
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.admin-page__table {
  overflow: hidden;
  border: 1px solid var(--ft-border-default);
  border-radius: var(--ft-radius-xl);
}

.admin-page__loading-tables {
  display: grid;
  gap: var(--ft-space-4);
}

/* stylelint-disable selector-pseudo-class-no-unknown */
.admin-page__table :deep(.p-datatable-table-container) {
  border-radius: var(--ft-radius-xl);
}

.admin-page__table :deep(.p-datatable-thead > tr > th) {
  white-space: nowrap;
}

@media (width <= 1024px) {
  .admin-page__kpis {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (width <= 768px) {
  .admin-page__kpis {
    grid-template-columns: 1fr;
  }
}
</style>
