// react-app/src/pages/LandingPage.tsx
import { Link } from '@tanstack/react-router';
import {
  ArrowRight,
  BarChart3,
  Bolt,
  ChevronRight,
  CreditCard,
  Send,
  ShieldCheck,
  TrendingDown,
  Wallet,
} from 'lucide-react';
import analyticsImage from '@/assets/landing/analytics.png';
import accountsImage from '@/assets/landing/accounts.png';
import forecastImage from '@/assets/landing/forecast.png';
import investmentsImage from '@/assets/landing/investments.png';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { PATHS } from '@/router/paths';

const dashboardScreens = [
  {
    title: 'Страница счетов',
    description: 'Все счета в одном месте, без ручной сводки по приложениям и картам.',
    image: accountsImage,
    alt: 'Скриншот страницы счетов в FinTree',
  },
  {
    title: 'Учет инвестиций',
    description: 'Портфель и динамика на одном экране, без таблиц и ручного суммирования.',
    image: investmentsImage,
    alt: 'Скриншот страницы инвестиций в FinTree',
  },
  {
    title: 'Прогноз расходов',
    description: 'Понимание, сколько денег нужно до конца месяца и где начинается риск.',
    image: forecastImage,
    alt: 'Скриншот прогноза расходов в FinTree',
  },
] as const;

const features = [
  {
    icon: Send,
    title: 'Запись через Telegram за 10 секунд',
    description:
      'Не нужно открывать приложение. Написали боту сумму — расход записан. Без форм, без лишних шагов.',
  },
  {
    icon: BarChart3,
    title: 'Детальная аналитика, а не просто диаграммы',
    description:
      'FinTree показывает тренды по категориям, прогноз до конца месяца и точки, где бюджет проседает.',
  },
  {
    icon: ShieldCheck,
    title: 'Без банковских интеграций',
    description:
      'Вы не привязываете карту и не даёте доступ к банку. Данные вводите вручную — полный контроль остаётся у вас.',
  },
] as const;

interface PricingPlan {
  name: string;
  price: string;
  period: string;
  note: string;
  description: string;
  accent: boolean;
  oldPrice?: string;
  badge?: string;
}

const pricing: PricingPlan[] = [
  {
    name: 'Месяц',
    price: '390 ₽',
    period: 'в месяц',
    note: 'После бесплатного месяца',
    description: 'Помесячная оплата без долгих обязательств.',
    accent: false,
  },
  {
    name: 'Год',
    oldPrice: '4 680 ₽',
    price: '3 900 ₽',
    period: 'в год',
    note: '325 ₽ в месяц после триала',
    description: 'Экономия 780 ₽ в год.',
    accent: true,
    badge: 'Лучший выбор',
  },
];

const howItWorksSteps = [
  {
    icon: Send,
    title: 'Запишите расход в Telegram',
    description: 'Напишите боту сумму и категорию. Он всё запомнит без форм и ручного ввода.',
  },
  {
    icon: BarChart3,
    title: 'Смотрите аналитику',
    description: 'FinTree автоматически строит картину расходов по категориям, счетам и периодам.',
  },
  {
    icon: TrendingDown,
    title: 'Оптимизируйте бюджет',
    description: 'Видите, где утечки, и принимаете решения на основе данных, а не ощущений.',
  },
] as const;

const trustPoints = [
  { icon: ShieldCheck, label: 'Данные под защитой' },
  { icon: Send, label: 'Запись через Telegram за 10 секунд' },
  { icon: Wallet, label: 'Без банковских интеграций' },
] as const;

function scrollToSection(sectionId: string) {
  document.getElementById(sectionId)?.scrollIntoView({
    behavior: 'smooth',
    block: 'start',
  });
}

export default function LandingPage() {
  return (
    <div className="relative isolate overflow-hidden">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-0 top-0 h-[32rem]"
        style={{
          background:
            'radial-gradient(circle at top, color-mix(in srgb, var(--ft-primary-400) 22%, transparent), transparent 58%)',
        }}
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-0 top-56 h-[28rem]"
        style={{
          background:
            'linear-gradient(180deg, transparent 0%, color-mix(in srgb, var(--ft-info-500) 10%, transparent) 45%, transparent 100%)',
        }}
      />

      <section className="mx-auto flex w-full max-w-6xl flex-col gap-16 px-4 py-12 sm:px-6 sm:py-16 lg:gap-24 lg:py-20">
        <div className="grid items-start gap-10 lg:grid-cols-[minmax(0,1.08fr)_minmax(24rem,0.92fr)]">
          <div className="space-y-8">
            <div className="inline-flex items-center gap-2 rounded-full border border-border/70 bg-background/70 px-3 py-1 text-xs font-semibold tracking-[0.18em] uppercase text-primary shadow-[var(--ft-shadow-sm)] backdrop-blur-sm">
              <CreditCard className="size-3.5" />
              0 ₽ в первый месяц
            </div>

            <div className="space-y-5">
              <h1 className="max-w-2xl text-4xl font-semibold tracking-tight text-foreground sm:text-5xl lg:text-6xl">
                Поймите, куда уходят деньги, без сложных таблиц.
              </h1>
              <p className="max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">
                FinTree собирает расходы в одном месте и сразу показывает, где можно сократить траты.
                Расходы записываются через Telegram за 10 секунд — без таблиц и ручного ввода.
              </p>
            </div>

            <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
              <Button asChild size="lg" className="min-h-12 rounded-xl px-5 shadow-[var(--ft-shadow-cta)]">
                <Link to={PATHS.REGISTER}>
                  Попробовать бесплатно
                  <ArrowRight className="size-4" />
                </Link>
              </Button>
              <Button asChild size="lg" variant="outline" className="min-h-12 rounded-xl px-5">
                <Link to={PATHS.LOGIN}>У меня уже есть аккаунт</Link>
              </Button>
            </div>

            <p className="text-sm text-muted-foreground">
              Без карты • 2 минуты на старт • отмена в любой момент
            </p>
          </div>

          <Card
            className="overflow-hidden rounded-[1.75rem] border border-border/60 bg-[color-mix(in_srgb,var(--ft-surface-raised)_82%,transparent)] py-0 shadow-[var(--ft-shadow-xl)]"
            style={{
              boxShadow:
                '0 28px 70px color-mix(in srgb, var(--ft-primary-900) 42%, transparent)',
            }}
          >
            <CardContent className="p-3 sm:p-4">
              <div className="overflow-hidden rounded-[1.35rem] border border-border/50 bg-[color-mix(in_srgb,var(--ft-surface-overlay)_78%,transparent)] p-2">
                <img
                  src={analyticsImage}
                  alt="Скриншот главной страницы аналитики в FinTree"
                  className="h-auto w-full rounded-[1rem] object-cover"
                />
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <div className="flex flex-wrap justify-center gap-3">
            <button
              type="button"
              onClick={() => scrollToSection('how-it-works')}
              className="inline-flex min-h-11 items-center gap-2 rounded-full border border-border/70 bg-background/70 px-4 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              Как работает
              <ChevronRight className="size-4" />
            </button>
            <button
              type="button"
              onClick={() => scrollToSection('screens')}
              className="inline-flex min-h-11 items-center gap-2 rounded-full border border-border/70 bg-background/70 px-4 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              Экраны
              <ChevronRight className="size-4" />
            </button>
            <button
              type="button"
              onClick={() => scrollToSection('features')}
              className="inline-flex min-h-11 items-center gap-2 rounded-full border border-border/70 bg-background/70 px-4 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              Возможности
              <ChevronRight className="size-4" />
            </button>
            <button
              type="button"
              onClick={() => scrollToSection('pricing')}
              className="inline-flex min-h-11 items-center gap-2 rounded-full border border-border/70 bg-background/70 px-4 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              Тарифы
              <ChevronRight className="size-4" />
            </button>
          </div>

          <div className="grid gap-3 sm:grid-cols-3">
            {trustPoints.map((item) => (
              <div
                key={item.label}
                className="rounded-2xl border border-border/60 bg-background/55 px-4 py-4 shadow-[var(--ft-shadow-sm)] backdrop-blur-sm"
              >
                <item.icon className="mb-3 size-5 text-primary" aria-hidden="true" />
                <p className="text-sm font-medium text-foreground">{item.label}</p>
              </div>
            ))}
          </div>
        </div>

        <section id="how-it-works" className="space-y-6 scroll-mt-24">
          <div className="max-w-2xl space-y-3">
            <p className="text-sm font-semibold tracking-[0.18em] text-primary uppercase">
              Как это работает
            </p>
            <h2 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
              Три шага до ясного бюджета.
            </h2>
          </div>

          <div className="grid gap-5 md:grid-cols-3">
            {howItWorksSteps.map((step, index) => (
              <Card
                key={step.title}
                className="rounded-[1.5rem] border border-border/60 bg-[color-mix(in_srgb,var(--ft-surface-raised)_78%,transparent)] shadow-[var(--ft-shadow-md)]"
              >
                <CardContent className="space-y-4 p-5">
                  <div className="flex items-center gap-3">
                    <div className="flex size-12 items-center justify-center rounded-2xl bg-primary/15 text-primary">
                      <step.icon className="size-5" aria-hidden="true" />
                    </div>
                    <span className="font-mono text-3xl font-semibold tracking-tight text-primary/40">
                      {String(index + 1).padStart(2, '0')}
                    </span>
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold text-foreground">{step.title}</h3>
                    <p className="text-sm leading-6 text-muted-foreground">{step.description}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <section id="screens" className="space-y-6 scroll-mt-24">
          <div className="max-w-2xl space-y-3">
            <p className="text-sm font-semibold tracking-[0.18em] text-primary uppercase">
              Реальные экраны
            </p>
            <h2 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
              Кабинет после регистрации, а не обещания на лендинге.
            </h2>
            <p className="text-base leading-7 text-muted-foreground">
              Живые экраны без мокапов: видно, как выглядят счета, инвестиции и прогноз расходов уже в работе.
            </p>
          </div>

          <div className="grid gap-5 lg:grid-cols-3">
            {dashboardScreens.map((screen) => (
              <Card
                key={screen.title}
                className="overflow-hidden rounded-[1.5rem] border border-border/60 bg-[color-mix(in_srgb,var(--ft-surface-raised)_78%,transparent)] py-0 shadow-[var(--ft-shadow-lg)]"
              >
                <CardContent className="space-y-4 p-4">
                  <div className="overflow-hidden rounded-[1.1rem] border border-border/50 bg-background/60">
                    <img src={screen.image} alt={screen.alt} className="h-auto w-full object-cover" />
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold text-foreground">{screen.title}</h3>
                    <p className="text-sm leading-6 text-muted-foreground">{screen.description}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <section id="features" className="space-y-6 scroll-mt-24">
          <div className="max-w-2xl space-y-3">
            <p className="text-sm font-semibold tracking-[0.18em] text-primary uppercase">
              Почему работает
            </p>
            <h2 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
              Минимум действий, максимум ясности.
            </h2>
            <p className="text-base leading-7 text-muted-foreground">
              Продукт создан для людей, которым нужна предсказуемость бюджета, а не еще один перегруженный сервис.
            </p>
          </div>

          <div className="grid gap-5 md:grid-cols-3">
            {features.map((feature) => (
              <Card
                key={feature.title}
                className="rounded-[1.5rem] border border-border/60 bg-[color-mix(in_srgb,var(--ft-surface-raised)_78%,transparent)] shadow-[var(--ft-shadow-md)]"
              >
                <CardContent className="space-y-4 p-5">
                  <div className="flex size-12 items-center justify-center rounded-2xl bg-primary/15 text-primary">
                    <feature.icon className="size-5" aria-hidden="true" />
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold text-foreground">{feature.title}</h3>
                    <p className="text-sm leading-6 text-muted-foreground">{feature.description}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <section
          id="pricing"
          className="scroll-mt-24 rounded-[2rem] border border-border/60 px-5 py-6 sm:px-6 sm:py-8 lg:px-8"
          style={{
            background:
              'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 88%, transparent) 0%, color-mix(in srgb, var(--ft-surface-base) 92%, transparent) 100%)',
          }}
        >
          <div className="grid gap-8 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] lg:items-start">
            <div className="space-y-4">
              <p className="text-sm font-semibold tracking-[0.18em] text-primary uppercase">
                Тарифы без сюрпризов
              </p>
              <h2 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
                Полный функционал в обоих тарифах.
              </h2>
              <p className="text-base leading-7 text-muted-foreground">
                Первый месяц бесплатный для всех новых пользователей. Сначала пользуетесь, потом решаете,
                какой режим оплаты удобнее.
              </p>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              {pricing.map((plan) => (
                <Card
                  key={plan.name}
                  className="rounded-[1.5rem] border py-0 shadow-[var(--ft-shadow-md)]"
                  style={{
                    borderColor: plan.accent
                      ? 'color-mix(in srgb, var(--ft-primary-400) 36%, var(--ft-border-default))'
                      : 'color-mix(in srgb, var(--ft-border-default) 78%, transparent)',
                    backgroundColor: plan.accent
                      ? 'color-mix(in srgb, var(--ft-primary-500) 12%, var(--ft-surface-raised))'
                      : 'color-mix(in srgb, var(--ft-surface-raised) 78%, transparent)',
                  }}
                >
                  <CardContent className="space-y-5 p-5">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <h3 className="text-xl font-semibold text-foreground">{plan.name}</h3>
                        <p className="mt-1 text-sm text-muted-foreground">{plan.note}</p>
                      </div>
                      {plan.badge ? (
                        <span className="rounded-full border border-primary/30 bg-primary/15 px-3 py-1 text-xs font-semibold text-primary">
                          {plan.badge}
                        </span>
                      ) : null}
                    </div>

                    <div className="space-y-1">
                      {'oldPrice' in plan ? (
                        <p className="text-sm text-muted-foreground line-through">{plan.oldPrice}</p>
                      ) : null}
                      <div className="flex items-end gap-2">
                        <strong className="text-4xl font-semibold tracking-tight text-foreground">
                          {plan.price}
                        </strong>
                        <span className="pb-1 text-sm text-muted-foreground">{plan.period}</span>
                      </div>
                    </div>

                    <p className="text-sm leading-6 text-muted-foreground">{plan.description}</p>
                    <Button
                      asChild
                      size="lg"
                      variant={plan.accent ? 'default' : 'secondary'}
                      className="w-full rounded-xl"
                    >
                      <Link to={PATHS.REGISTER}>Начать бесплатно</Link>
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </section>
    </div>
  );
}

// vue-app/src/pages/LandingPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const features = [
  {
    icon: 'pi-telegram',
    title: 'Учёт расходов в Telegram',
    description: 'Записывайте траты одной строкой через @financetree_bot. В среднем это занимает меньше 10 секунд.'
  },
  {
    icon: 'pi-chart-line',
    title: 'Честная аналитика бюджета',
    description: 'Доля сбережений, чистый поток, пики трат и необязательные расходы — все по делу.'
  },
  {
    icon: 'pi-wallet',
    title: 'Контроль ликвидного капитала',
    description: 'Счета, наличные и инвестиции в одном месте без лишних деталей.'
  },
  {
    icon: 'pi-shield',
    title: 'Безопасность без компромиссов',
    description: 'Мы не подключаемся к банкам и не продаем данные. Все вводится только вами.'
  }
] as const

const steps = [
  {
    number: '01',
    title: 'Привяжите Telegram',
    description: 'Отправьте `/id` боту @financetree_bot и вставьте цифры в профиле FinTree.'
  },
  {
    number: '02',
    title: 'Добавляйте операции',
    description: 'Пишите траты в бота @financetree_bot сразу или переносите пачкой из заметок.'
  },
  {
    number: '03',
    title: 'Анализируйте раз в неделю',
    description: 'Веб-кабинет покажет, где теряются деньги и сколько вы реально откладываете.'
  }
] as const

const pricing = [
  {
    name: 'Единый тариф',
    price: '1 месяц бесплатно',
    subprice: 'Далее 390 ₽/мес или 3 900 ₽/год (2 месяца в подарок)',
    accent: true,
    description: 'Полный доступ к FinTree без ограничений.',
    features: [
      'Telegram-бот для учёта расходов',
      'Полная аналитика бюджета и капитала',
      'Счета, категории и инвестиции'
    ],
    ctaLabel: 'Начать бесплатный месяц'
  }
] as const

const faq = [
  {
    question: 'Почему ввод вручную — это нормально?',
    answer: 'Так вы сохраняете точность и контролируете привычки. Telegram-бот делает ввод быстрым.'
  },
  {
    question: 'Как привязать Telegram?',
    answer: 'Отправьте боту @financetree_bot команду `/id`, скопируйте цифры и вставьте их в профиле FinTree.'
  },
  {
    question: 'Что с безопасностью данных?',
    answer: 'Мы не подключаемся к банкам. Доступ к данным есть только у вас.'
  },
  {
    question: 'Что будет после бесплатного месяца?',
    answer: 'Вы сможете продолжить пользоваться сервисом по подписке или оформить год со скидкой.'
  }
] as const

const expandedIndex = ref<number | null>(0)

const currentYear = new Date().getFullYear()

const toggleFaq = (index: number) => {
  expandedIndex.value = expandedIndex.value === index ? null : index
}

const scrollToSection = (sectionId: string) => {
  const element = document.getElementById(sectionId)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
}
</script>

<template>
  <div class="landing">
    <header class="landing__nav">
      <div class="landing__nav-inner">
        <router-link
          to="/"
          class="landing__brand"
        >
          <i class="pi pi-chart-bar" />
          <span>FinTree</span>
        </router-link>

        <nav class="landing__links">
          <button
            type="button"
            @click="scrollToSection('features')"
          >
            Возможности
          </button>
          <button
            type="button"
            @click="scrollToSection('steps')"
          >
            Как это работает
          </button>
          <button
            type="button"
            @click="scrollToSection('pricing')"
          >
            Тарифы
          </button>
          <button
            type="button"
            @click="scrollToSection('faq')"
          >
            FAQ
          </button>
        </nav>

        <div class="landing__actions">
          <ThemeToggle />
          <AppButton
            variant="ghost"
            label="Войти"
            @click="router.push('/login')"
          />
          <AppButton
            label="Регистрация"
            @click="router.push('/register')"
          />
        </div>
      </div>
    </header>

    <main class="landing__main">
      <section class="landing__hero">
        <div class="landing__container landing__hero-layout">
          <div class="landing__hero-copy">
            <span class="landing__hero-badge">
              <i
                class="pi pi-bolt"
                aria-hidden="true"
              />
              <span>Telegram для учёта · Веб для аналитики</span>
            </span>
            <h1 class="landing__hero-title">
              Финансы под контролем<br>
              без сложных таблиц
            </h1>
            <p class="landing__hero-subtitle">
              Вносите траты в Telegram за 10 секунд и получайте понятную аналитику на сайте раз в неделю.
            </p>

            <div class="landing__hero-actions">
              <AppButton
                label="Начать бесплатный месяц"
                icon="pi pi-arrow-right"
                icon-pos="right"
                size="lg"
                @click="router.push('/register')"
              />
              <AppButton
                label="Посмотреть аналитику"
                variant="ghost"
                size="lg"
                icon="pi pi-play"
                @click="scrollToSection('features')"
              />
            </div>

            <div class="landing__trust">
              <div class="landing__trust-item">
                <i class="pi pi-shield" />
                <span>Без подключения банков</span>
              </div>
              <div class="landing__trust-item">
                <i class="pi pi-check-circle" />
                <span>Данные не покидают FinTree</span>
              </div>
              <div class="landing__trust-item">
                <i class="pi pi-sparkles" />
                <span>Аналитика по делу, без шума</span>
              </div>
            </div>
          </div>

          <AppCard
            class="landing__hero-card"
            padding="lg"
            variant="muted"
            elevated
          >
            <template #header>
              <div class="landing__hero-card-header">
                <span>Превью аналитики</span>
                <i class="pi pi-chart-line" />
              </div>
            </template>
            <div class="landing__hero-card-body">
              <div class="landing__hero-metric">
                <span class="landing__hero-metric-label">Доля сбережений</span>
                <strong>24%</strong>
                <small>+6% за месяц</small>
              </div>
              <div class="landing__hero-metric landing__hero-metric--split">
                <article>
                  <span class="landing__hero-metric-label">Ликвидные месяцы</span>
                  <strong>5.1 мес</strong>
                  <small>цель: 6 месяцев</small>
                </article>
                <article>
                  <span class="landing__hero-metric-label">Чистый поток</span>
                  <strong>+32 400 ₽</strong>
                  <small>текущий месяц</small>
                </article>
              </div>
              <div class="landing__hero-chart">
                <div
                  class="landing__hero-chart-bar"
                  style="--progress: 68%"
                />
              </div>
            </div>
          </AppCard>
        </div>
      </section>

      <section
        id="features"
        class="landing__section"
      >
        <div class="landing__container">
          <header class="landing__section-header">
            <h2>Почему FinTree работает</h2>
            <p>Минимум действий каждый день — максимум ясности на отчётах.</p>
          </header>

          <div class="card-grid card-grid--balanced card-grid--dense landing__feature-grid">
            <AppCard
              v-for="feature in features"
              :key="feature.title"
              variant="muted"
              padding="lg"
              class="landing__feature-card"
            >
              <div class="landing__feature-icon">
                <i :class="['pi', feature.icon]" />
              </div>
              <h3>{{ feature.title }}</h3>
              <p>{{ feature.description }}</p>
            </AppCard>
          </div>
        </div>
      </section>

      <section
        id="steps"
        class="landing__section landing__section--alt"
      >
        <div class="landing__container">
          <header class="landing__section-header">
            <h2>Понятный процесс без лишних шагов</h2>
            <p>Телеграм закрывает ввод, веб — аналитику и выводы.</p>
          </header>

          <div class="card-grid card-grid--balanced landing__steps">
            <AppCard
              v-for="step in steps"
              :key="step.number"
              variant="outlined"
              padding="lg"
              class="landing__step-card"
            >
              <span class="landing__step-number">{{ step.number }}</span>
              <h3>{{ step.title }}</h3>
              <p>{{ step.description }}</p>
            </AppCard>
          </div>
        </div>
      </section>

      <section
        id="pricing"
        class="landing__section"
      >
        <div class="landing__container">
          <header class="landing__section-header">
            <h2>Прозрачная подписка</h2>
            <p>Один тариф, один месяц бесплатно и полный доступ ко всем возможностям.</p>
          </header>

          <div class="card-grid landing__pricing">
            <AppCard
              v-for="plan in pricing"
              :key="plan.name"
              :variant="plan.accent ? 'outlined' : 'muted'"
              padding="lg"
              class="landing__pricing-card"
              :class="{ 'landing__pricing-card--accent': plan.accent }"
              :elevated="plan.accent"
            >
              <header class="landing__pricing-header">
                <div>
                  <h3>{{ plan.name }}</h3>
                  <p>{{ plan.description }}</p>
                </div>
                <div class="landing__pricing-price">
                  <strong>{{ plan.price }}</strong>
                  <span v-if="plan.subprice">{{ plan.subprice }}</span>
                </div>
              </header>

              <ul class="landing__pricing-features">
                <li
                  v-for="feature in plan.features"
                  :key="feature"
                >
                  <i
                    class="pi pi-check"
                    aria-hidden="true"
                  />
                  <span>{{ feature }}</span>
                </li>
              </ul>

              <AppButton
                :label="plan.ctaLabel"
                block
                :variant="plan.accent ? 'primary' : 'ghost'"
                @click="router.push('/register')"
              />
            </AppCard>
          </div>
        </div>
      </section>

      <section
        id="faq"
        class="landing__section landing__section--alt"
      >
        <div class="landing__container landing__faq">
          <header class="landing__section-header">
            <h2>Частые вопросы</h2>
            <p>Если не нашли ответ — напишите нам, отвечаем в течение дня.</p>
          </header>

          <div class="landing__faq-list">
            <AppCard
              v-for="(item, index) in faq"
              :key="item.question"
              variant="muted"
              padding="md"
              class="landing__faq-item"
            >
              <button
                type="button"
                class="landing__faq-question"
                @click="toggleFaq(index)"
              >
                <span>{{ item.question }}</span>
                <i :class="['pi', expandedIndex === index ? 'pi-chevron-up' : 'pi-chevron-down']" />
              </button>
              <transition name="faq">
                <p
                  v-show="expandedIndex === index"
                  class="landing__faq-answer"
                >
                  {{ item.answer }}
                </p>
              </transition>
            </AppCard>
          </div>
        </div>
      </section>

      <section class="landing__cta">
        <div class="landing__container landing__cta-inner">
          <div>
            <h2>Готовы увидеть реальную картину бюджета?</h2>
            <p>Начните бесплатный месяц и получите первые выводы уже через неделю.</p>
          </div>
          <AppButton
            label="Создать аккаунт"
            icon="pi pi-arrow-right"
            icon-pos="right"
            size="lg"
            @click="router.push('/register')"
          />
        </div>
      </section>
    </main>

    <footer class="landing__footer">
      <div class="landing__container landing__footer-inner">
        <div class="landing__footer-brand">
          <router-link
            to="/"
            class="landing__brand"
          >
            <i class="pi pi-chart-bar" />
            <span>FinTree</span>
          </router-link>
          <p>Финансовый помощник для тех, кто хочет тратить осознанно.</p>
        </div>
        <nav class="landing__footer-links">
          <div>
            <h4>Продукт</h4>
            <button
              type="button"
              @click="scrollToSection('features')"
            >
              Возможности
            </button>
            <button
              type="button"
              @click="scrollToSection('pricing')"
            >
              Тарифы
            </button>
            <button
              type="button"
              @click="scrollToSection('faq')"
            >
              FAQ
            </button>
          </div>
          <div>
            <h4>Компания</h4>
            <a href="mailto:hello@fintree.app">Написать нам</a>
            <router-link to="/blog">
              Блог
            </router-link>
            <router-link to="/careers">
              Карьера
            </router-link>
          </div>
        </nav>
      </div>
      <div class="landing__footer-meta">
        <span>© {{ currentYear }} FinTree. Все права защищены.</span>
        <div class="landing__footer-meta-links">
          <router-link to="/privacy">
            Политика конфиденциальности
          </router-link>
          <router-link to="/terms">
            Условия использования
          </router-link>
        </div>
      </div>
    </footer>
  </div>
</template>

<style scoped>
.landing {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background:
    radial-gradient(
      900px 600px at 8% -15%,
      color-mix(in srgb, var(--ft-primary-500) 28%, transparent),
      transparent
    ),
    radial-gradient(
      700px 520px at 92% 8%,
      color-mix(in srgb, var(--ft-info-500) 14%, transparent),
      transparent
    ),
    linear-gradient(180deg, var(--ft-bg-base) 0%, var(--ft-bg-muted) 100%);
  color: var(--ft-text-primary);
}

.landing__container {
  width: 100%;
  max-width: var(--ft-container-2xl);
  margin: 0 auto;
  padding: clamp(var(--ft-space-6), 5vw, var(--ft-space-10)) clamp(var(--ft-space-4), 5vw, var(--ft-space-8));
}

.landing__nav {
  position: sticky;
  top: 0;
  z-index: var(--ft-z-sticky);
  backdrop-filter: blur(14px);
  border-bottom: 1px solid var(--ft-border-subtle);
  background: color-mix(in srgb, var(--ft-bg-base) 85%, transparent);
}

.landing__nav-inner {
  width: 100%;
  max-width: var(--ft-container-2xl);
  margin: 0 auto;
  padding: clamp(var(--ft-space-3), 4vw, var(--ft-space-5)) clamp(var(--ft-space-4), 5vw, var(--ft-space-8));
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--ft-space-5);
}

.landing__brand {
  display: inline-flex;
  align-items: center;
  gap: var(--ft-space-2);
  font-weight: var(--ft-font-bold);
  font-size: var(--ft-text-lg);
  font-family: var(--ft-font-display);
  letter-spacing: -0.01em;
  color: var(--ft-text-primary);
}

.landing__brand i {
  color: var(--ft-primary-600);
  font-size: 1.25rem;
}

.landing__links {
  display: flex;
  gap: var(--ft-space-4);
  align-items: center;
}

.landing__links button {
  background: transparent;
  border: none;
  color: var(--ft-text-tertiary);
  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
  transition: color var(--ft-transition-fast);
  cursor: pointer;
}

.landing__links button:hover {
  color: var(--ft-text-primary);
}

.landing__actions {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: var(--ft-space-3);
}

.landing__hero {
  position: relative;
  overflow: hidden;
}

.landing__hero::after {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(
      55% 55% at 75% 10%,
      color-mix(in srgb, var(--ft-primary-500) 20%, transparent),
      transparent
    ),
    radial-gradient(
      45% 45% at 15% 70%,
      color-mix(in srgb, var(--ft-info-500) 12%, transparent),
      transparent
    );
  opacity: 0.8;
  pointer-events: none;
}

.landing__hero-layout {
  position: relative;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: clamp(var(--ft-space-6), 5vw, var(--ft-space-10));
  align-items: center;
  z-index: 1;
}

.landing__hero-copy {
  display: flex;
  flex-direction: column;
  gap: clamp(var(--ft-space-4), 3vw, var(--ft-space-6));
  animation: fadeUp 720ms var(--ft-ease-in-out) both;
}

.landing__hero-badge {
  display: inline-flex;
  align-items: center;
  gap: var(--ft-space-2);
  border-radius: var(--ft-radius-full);
  padding: var(--ft-space-1) var(--ft-space-3);
  background: color-mix(in srgb, var(--ft-primary-500) 20%, transparent);
  border: 1px solid color-mix(in srgb, var(--ft-primary-500) 40%, transparent);
  color: var(--ft-primary-200);
  font-size: var(--ft-text-xs);
  text-transform: uppercase;
  letter-spacing: 0.16em;
  font-weight: var(--ft-font-semibold);
}

.landing__hero-title {
  margin: 0;
  font-size: clamp(2.6rem, 4vw, 3.6rem);
  line-height: 1.1;
  font-family: var(--ft-font-display);
  letter-spacing: var(--ft-letter-spacing-display);
}

.landing__hero-subtitle {
  margin: 0;
  color: var(--ft-text-secondary);
  font-size: clamp(var(--ft-text-base), 2.2vw, 1.1rem);
  max-width: 46ch;
}

.landing__hero-actions {
  display: flex;
  gap: var(--ft-space-3);
  flex-wrap: wrap;
}

.landing__trust {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: var(--ft-space-3);
}

.landing__trust-item {
  display: flex;
  align-items: center;
  gap: var(--ft-space-2);
  padding: var(--ft-space-3);
  border-radius: var(--ft-radius-lg);
  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  color: var(--ft-text-secondary);
}

.landing__hero-card {
  position: relative;
  overflow: hidden;
  border: 1px solid var(--ft-border-subtle);
  background: var(--ft-surface-base);
  animation: fadeUp 720ms var(--ft-ease-in-out) both;
  animation-delay: 120ms;
  box-shadow: var(--ft-shadow-2xl);
}

.landing__hero-card::after {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(
    135deg,
    color-mix(in srgb, var(--ft-primary-500) 24%, transparent),
    color-mix(in srgb, var(--ft-info-500) 12%, transparent)
  );
  opacity: 0.5;
  pointer-events: none;
}

.landing__hero-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  color: var(--ft-text-secondary);
}

.landing__hero-card-body {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);
  position: relative;
  z-index: 1;
}

.landing__hero-metric {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-1);
}

.landing__hero-metric strong {
  font-size: var(--ft-text-2xl);
  font-weight: var(--ft-font-bold);
  color: var(--ft-text-primary);
}

.landing__hero-metric small {
  color: var(--ft-success-400);
}

.landing__hero-metric--split {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: var(--ft-space-4);
}

.landing__hero-chart {
  position: relative;
  height: 6px;
  border-radius: var(--ft-radius-full);
  background: color-mix(in srgb, var(--ft-border-default) 65%, transparent);
  overflow: hidden;
}

.landing__hero-chart-bar {
  position: absolute;
  inset: 0;
  width: var(--progress);
  background: linear-gradient(90deg, var(--ft-primary-400), var(--ft-success-400));
}

.landing__section {
  position: relative;
  scroll-margin-top: 110px;
}

.landing__section--alt {
  background: var(--ft-bg-subtle);
  border-top: 1px solid var(--ft-border-subtle);
  border-bottom: 1px solid var(--ft-border-subtle);
}

.landing__section-header {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-2);
  text-align: center;
  margin-bottom: clamp(var(--ft-space-6), 4vw, var(--ft-space-8));
}

.landing__section-header h2 {
  margin: 0;
  font-size: clamp(1.85rem, 3vw, 2.6rem);
  font-family: var(--ft-font-display);
}

.landing__section-header p {
  margin: 0;
  color: var(--ft-text-secondary);
}

.landing__feature-card {
  gap: var(--ft-space-3);
  border: 1px solid var(--ft-border-subtle);
  background: var(--ft-surface-base);
  transition: transform var(--ft-transition-fast), border-color var(--ft-transition-fast), box-shadow var(--ft-transition-fast);
  animation: fadeUp 680ms var(--ft-ease-in-out) both;
}

.landing__feature-card:nth-child(1) {
  animation-delay: 60ms;
}

.landing__feature-card:nth-child(2) {
  animation-delay: 120ms;
}

.landing__feature-card:nth-child(3) {
  animation-delay: 180ms;
}

.landing__feature-card:nth-child(4) {
  animation-delay: 240ms;
}

.landing__feature-card:hover {
  transform: translateY(-4px);
  border-color: color-mix(in srgb, var(--ft-primary-500) 45%, var(--ft-border-subtle));
  box-shadow: var(--ft-shadow-lg);
}

.landing__feature-card h3 {
  margin: 0;
  font-size: var(--ft-text-lg);
  color: var(--ft-text-primary);
}

.landing__feature-card p {
  margin: 0;
  color: var(--ft-text-secondary);
}

.landing__feature-icon {
  width: 48px;
  height: 48px;
  display: grid;
  place-items: center;
  border-radius: var(--ft-radius-lg);
  background: color-mix(in srgb, var(--ft-primary-500) 20%, transparent);
  color: var(--ft-primary-500);
  font-size: 1.5rem;
}

.landing__steps {
  gap: var(--ft-space-4);
}

.landing__step-card {
  gap: var(--ft-space-3);
  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  transition: transform var(--ft-transition-fast), border-color var(--ft-transition-fast), box-shadow var(--ft-transition-fast);
}

.landing__step-card:hover {
  transform: translateY(-4px);
  border-color: color-mix(in srgb, var(--ft-primary-500) 40%, var(--ft-border-subtle));
  box-shadow: var(--ft-shadow-lg);
}

.landing__step-card h3 {
  margin: 0;
  font-size: var(--ft-text-lg);
}

.landing__step-card p {
  margin: 0;
  color: var(--ft-text-secondary);
}

.landing__step-number {
  font-size: var(--ft-text-sm);
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--ft-primary-300);
}

.landing__pricing {
  gap: var(--ft-space-4);
  align-items: stretch;
}

.landing__pricing-card {
  gap: var(--ft-space-4);
  border: 1px solid var(--ft-border-subtle);
  background: var(--ft-surface-base);
}

.landing__pricing-card--accent {
  border-width: 2px;
  border-color: color-mix(in srgb, var(--ft-primary-500) 70%, transparent);
  box-shadow: var(--ft-shadow-xl);
}

.landing__pricing-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: var(--ft-space-4);
}

.landing__pricing-header h3 {
  margin: 0;
  font-size: var(--ft-text-xl);
}

.landing__pricing-header p {
  margin: var(--ft-space-1) 0 0;
  color: var(--ft-text-secondary);
}

.landing__pricing-header strong {
  font-size: var(--ft-text-2xl);
  color: var(--ft-text-primary);
}

.landing__pricing-price {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: var(--ft-space-1);
  text-align: right;
}

.landing__pricing-price span {
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.landing__pricing-features {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-2);
  margin: 0;
  padding: 0;
  color: var(--ft-text-secondary);
}

.landing__pricing-features li {
  display: flex;
  align-items: center;
  gap: var(--ft-space-2);
}

.landing__pricing-features i {
  color: var(--ft-success-400);
}

.landing__faq {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-6);
}

.landing__faq-list {
  display: grid;
  gap: var(--ft-space-3);
}

.landing__faq-item {
  gap: var(--ft-space-2);
  border: 1px solid var(--ft-border-subtle);
  background: var(--ft-surface-base);
}

.landing__faq-question {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--ft-space-2);
  width: 100%;
  background: none;
  border: none;
  color: inherit;
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-medium);
  text-align: left;
  cursor: pointer;
}

.landing__faq-answer {
  margin: 0;
  color: var(--ft-text-secondary);
  line-height: 1.6;
}

.faq-enter-active,
.faq-leave-active {
  transition: opacity var(--ft-transition-base), transform var(--ft-transition-base);
}

.faq-enter-from,
.faq-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}

.landing__cta {
  padding-block: clamp(var(--ft-space-8), 6vw, var(--ft-space-12));
  background: linear-gradient(
    135deg,
    color-mix(in srgb, var(--ft-primary-500) 26%, transparent),
    color-mix(in srgb, var(--ft-primary-500) 8%, transparent)
  );
  border-top: 1px solid var(--ft-border-subtle);
  border-bottom: 1px solid var(--ft-border-subtle);
}

.landing__cta-inner {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: var(--ft-space-6);
  align-items: center;
}

.landing__cta-inner h2 {
  margin: 0;
  font-size: clamp(1.85rem, 3vw, 2.4rem);
  font-family: var(--ft-font-display);
}

.landing__cta-inner p {
  margin: var(--ft-space-2) 0 0;
  color: var(--ft-text-secondary);
}

.landing__footer {
  margin-top: auto;
  border-top: 1px solid var(--ft-border-subtle);
  background: var(--ft-bg-base);
}

.landing__footer-inner {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: var(--ft-space-6);
  align-items: start;
}

.landing__footer-brand p {
  margin: var(--ft-space-2) 0 0;
  color: var(--ft-text-secondary);
}

.landing__footer-links {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: var(--ft-space-4);
}

.landing__footer-links h4 {
  margin: 0 0 var(--ft-space-2);
  font-size: var(--ft-text-sm);
  text-transform: uppercase;
  letter-spacing: 0.12em;
  color: var(--ft-text-tertiary);
}

.landing__footer-links button,
.landing__footer-links a {
  display: inline-flex;
  align-items: center;
  gap: var(--ft-space-1);
  background: none;
  border: none;
  padding: 0;
  color: var(--ft-text-secondary);
  font-size: var(--ft-text-sm);
  cursor: pointer;
  text-decoration: none;
  transition: color var(--ft-transition-fast);
}

.landing__footer-links button:hover,
.landing__footer-links a:hover {
  color: var(--ft-text-primary);
}

.landing__footer-meta {
  padding: var(--ft-space-4) clamp(var(--ft-space-4), 5vw, var(--ft-space-8));
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: var(--ft-space-3);
  font-size: var(--ft-text-sm);
  color: var(--ft-text-tertiary);
  border-top: 1px solid color-mix(in srgb, var(--ft-border-default) 50%, transparent);
}

.light-mode .landing__hero-badge {
  color: var(--ft-primary-700);
}

.landing__footer-meta-links {
  display: flex;
  gap: var(--ft-space-3);
  flex-wrap: wrap;
}

.landing__footer-meta-links a {
  color: inherit;
  text-decoration: none;
}

.landing__footer-meta-links a:hover {
  color: var(--ft-text-primary);
}

@keyframes fadeUp {
  from {
    opacity: 0;
    transform: translateY(14px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (max-width: 960px) {
  .landing__links {
    display: none;
  }

  .landing__hero-metric--split {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 640px) {
  .landing__nav-inner {
    flex-direction: column;
    align-items: stretch;
  }

  .landing__actions {
    justify-content: flex-start;
  }

  .landing__hero-actions {
    flex-direction: column;
  }
}
</style>
