// react-app/src/pages/ProfilePage.tsx
import { AlertCircle, Check, CreditCard, Shield } from 'lucide-react';
import { type ReactNode } from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Controller } from 'react-hook-form';
import { ErrorBoundary } from '@/components/common/ErrorBoundary';
import { FormField } from '@/components/common/FormField';
import { PageHeader } from '@/components/common/PageHeader';
import type { CurrentUserDto, Currency, SubscriptionPaymentDto, SubscriptionPlan } from '@/types';
import { resolveApiErrorMessage } from '@/utils/errors';
import { formatCurrency } from '@/utils/format';
import { cn } from '@/utils/cn';
import { PATHS } from '@/router/paths';
import { useProfilePage } from '@/features/profile/useProfilePage';

function formatDateLabel(value: string | null): string {
  if (!value) return '—';
  return new Intl.DateTimeFormat('ru-RU', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  }).format(new Date(value));
}

function formatDateTimeLabel(value: string): string {
  return new Intl.DateTimeFormat('ru-RU', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(value));
}

function getPlanTitle(plan: SubscriptionPlan): string {
  return plan === 'Year' ? '12 месяцев' : '1 месяц';
}

function getPaymentStatusLabel(status: SubscriptionPaymentDto['status']): string {
  switch (status) {
    case 'Succeeded': return 'Успешно';
    case 'Failed': return 'Ошибка';
    case 'Refunded': return 'Возврат';
    case 'Canceled': return 'Отменено';
    default: return status;
  }
}

function SubscriptionStatusBadge({ user }: { user: CurrentUserDto }) {
  const isActive = user.subscription.isActive;

  return (
    <Badge
      variant="outline"
      className={cn(
        'rounded-full px-3 py-1 text-xs font-semibold',
        isActive
          ? 'border-[var(--ft-success-500)]/30 bg-[color-mix(in_srgb,var(--ft-success-500)_12%,transparent)] text-[var(--ft-success-400)]'
          : 'border-[var(--ft-warning-500)]/30 bg-[color-mix(in_srgb,var(--ft-warning-500)_10%,transparent)] text-[var(--ft-warning-300)]',
      )}
    >
      {isActive ? 'Активна' : 'Только просмотр'}
    </Badge>
  );
}

function PageCard({
  title,
  description,
  actions,
  children,
  muted = false,
}: {
  title?: string;
  description?: string;
  actions?: ReactNode;
  children: ReactNode;
  muted?: boolean;
}) {
  return (
    <section
      className="rounded-xl border px-5 py-5 shadow-[var(--ft-shadow-sm)]"
      style={{
        borderColor: 'color-mix(in srgb, var(--ft-primary-400) 10%, var(--ft-border-default))',
        backgroundColor: muted
          ? 'color-mix(in srgb, var(--ft-surface-raised) 62%, var(--ft-surface-base))'
          : 'color-mix(in srgb, var(--ft-surface-raised) 74%, var(--ft-surface-base))',
      }}
    >
      {title ? (
        <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h2 className="text-lg font-semibold text-foreground">{title}</h2>
            {description ? (
              <p className="mt-1 text-sm text-muted-foreground">{description}</p>
            ) : null}
          </div>
          {actions ? <div className="flex shrink-0 items-center">{actions}</div> : null}
        </div>
      ) : null}

      {children}
    </section>
  );
}

function PaymentHistoryList({
  payments,
  loading,
}: {
  payments: SubscriptionPaymentDto[];
  loading: boolean;
}) {
  if (loading) {
    return (
      <div className="space-y-3 pt-2">
        {Array.from({ length: 3 }, (_, index) => (
          <Skeleton key={index} className="h-[58px] rounded-lg" />
        ))}
      </div>
    );
  }

  if (payments.length === 0) {
    return (
      <p className="pt-2 text-sm text-muted-foreground">
        Оплат пока нет. После mock-оплаты запись появится здесь.
      </p>
    );
  }

  return (
    <ul className="space-y-3 pt-2">
      {payments.map((payment) => (
        <li
          key={payment.id}
          className="flex flex-col gap-3 rounded-lg border border-border bg-background/35 px-4 py-3 sm:flex-row sm:items-start sm:justify-between"
        >
          <div>
            <p className="text-sm font-semibold text-foreground">
              {getPlanTitle(payment.plan)} · {getPaymentStatusLabel(payment.status)}
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              {formatDateTimeLabel(payment.paidAtUtc)} · Период:{' '}
              {formatDateLabel(payment.subscriptionStartsAtUtc)} - {formatDateLabel(payment.subscriptionEndsAtUtc)}
            </p>
          </div>
          <div className="text-sm text-muted-foreground sm:text-right">
            <p className="font-semibold text-foreground">
              Списано: {formatCurrency(payment.chargedPriceRub, 'RUB')}
            </p>
            <p className="mt-1 text-xs">
              Тариф: {formatCurrency(payment.listedPriceRub, 'RUB')}
            </p>
          </div>
        </li>
      ))}
    </ul>
  );
}

export default function ProfilePage() {
  const {
    navigate,
    currentUserQuery,
    currentUser,
    form,
    telegramUserIdValue,
    currenciesQuery,
    paymentsQuery,
    saveProfileMutation,
    simulatePaymentMutation,
    handleProfileSubmit,
    handlePay,
    subscriptionError,
    isReadOnlyMode,
    isSubscriptionActive,
    initials,
    paymentPlans,
  } = useProfilePage();

  if (currentUserQuery.isPending && !currentUser) {
    return (
      <ErrorBoundary>
        <div className="flex flex-col gap-5 p-4 sm:p-6 lg:px-8">
          <PageHeader title="Настройки" className="mb-0" />
          <Skeleton className="h-[140px] rounded-xl" />
          <Skeleton className="h-[280px] rounded-xl" />
          <Skeleton className="h-[320px] rounded-xl" />
        </div>
      </ErrorBoundary>
    );
  }

  if (!currentUser) {
    return (
      <ErrorBoundary>
        <div className="flex flex-col gap-5 p-4 sm:p-6 lg:px-8">
          <PageHeader title="Настройки" className="mb-0" />
          <PageCard
            title="Не удалось загрузить настройки"
            description={resolveApiErrorMessage(
              currentUserQuery.error,
              'Попробуйте обновить данные пользователя ещё раз.',
            )}
            actions={
              <Button
                className="min-h-[44px] rounded-lg px-4"
                onClick={() => void currentUserQuery.refetch()}
              >
                Повторить
              </Button>
            }
          >
            <div className="flex items-start gap-3 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
              <AlertCircle className="mt-0.5 size-4 shrink-0" />
              <span>Данные профиля недоступны. Остальные действия временно заблокированы.</span>
            </div>
          </PageCard>
        </div>
      </ErrorBoundary>
    );
  }

  return (
    <ErrorBoundary>
      <div className="flex flex-col gap-5 p-4 sm:p-6 lg:px-8">
        <PageHeader title="Настройки" className="mb-0" />

        {currentUser.isOwner ? (
          <PageCard
            title="Админ-панель"
            description="Просматривайте ключевые метрики сервиса: пользователей, транзакции и операционную активность."
            actions={
              <Button className="min-h-[44px] rounded-lg px-4" onClick={() => void navigate({ to: PATHS.ADMIN })}>
                <Shield className="size-4" />
                Открыть админ-панель
              </Button>
            }
          >
            <div className="flex items-center gap-3 rounded-lg border border-border bg-background/35 px-4 py-3 text-sm text-muted-foreground">
              <Shield className="size-4 text-primary" />
              Владелец аккаунта имеет доступ к административному разделу.
            </div>
          </PageCard>
        ) : null}

        <PageCard muted>
          <div className="flex items-center gap-4">
            <div
              className="flex size-14 shrink-0 items-center justify-center rounded-full text-lg font-semibold shadow-[var(--ft-shadow-sm)]"
              style={{ backgroundColor: 'var(--ft-primary-500)', color: 'var(--ft-text-inverse)' }}
              aria-hidden="true"
            >
              {initials}
            </div>
            <div className="min-w-0">
              <p className="truncate text-lg font-semibold text-foreground">{currentUser.name ?? '—'}</p>
              <p className="truncate text-sm text-muted-foreground">{currentUser.email ?? '—'}</p>
            </div>
          </div>
        </PageCard>

        <PageCard title="Основные настройки" description="Управляйте базовой валютой и Telegram-ботом.">
          <form className="space-y-5" onSubmit={handleProfileSubmit} noValidate>
            <div className="grid gap-4 lg:grid-cols-2">
              <FormField
                label="Базовая валюта"
                required
                error={form.formState.errors.baseCurrencyCode?.message}
                hint={
                  currenciesQuery.isLoading
                    ? 'Загрузка доступных валют…'
                    : currenciesQuery.isError
                      ? 'Не удалось загрузить валюты. Повторите позже.'
                      : 'В этой валюте считается вся аналитика и отчеты.'
                }
              >
                <Controller
                  control={form.control}
                  name="baseCurrencyCode"
                  render={({ field }) => (
                    <Select
                      value={field.value}
                      onValueChange={field.onChange}
                      disabled={
                        currenciesQuery.isLoading ||
                        currenciesQuery.isError ||
                        saveProfileMutation.isPending ||
                        isReadOnlyMode
                      }
                    >
                      <SelectTrigger className="h-11 w-full rounded-lg">
                        <SelectValue placeholder="Выберите валюту" />
                      </SelectTrigger>
                      <SelectContent>
                        {(currenciesQuery.data ?? []).map((currency: Currency) => (
                          <SelectItem key={currency.code} value={currency.code}>
                            {currency.symbol} {currency.code} · {currency.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                />
              </FormField>

              <FormField
                label="Telegram-бот"
                error={form.formState.errors.telegramUserId?.message}
                hint="Отправьте /id боту @financetree_bot и вставьте цифры сюда. Оставьте пустым, чтобы отвязать."
              >
                <div className="flex gap-2">
                  <Input
                    placeholder="123456789"
                    autoComplete="off"
                    disabled={saveProfileMutation.isPending || isReadOnlyMode}
                    {...form.register('telegramUserId')}
                  />
                  <Button
                    type="button"
                    variant="outline"
                    className="min-h-[44px] shrink-0 rounded-lg px-4"
                    disabled={!telegramUserIdValue || saveProfileMutation.isPending || isReadOnlyMode}
                    onClick={() => form.setValue('telegramUserId', '', { shouldDirty: true, shouldValidate: true })}
                  >
                    Очистить
                  </Button>
                </div>
              </FormField>
            </div>

            {form.formState.errors.root?.message ? (
              <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
                <AlertCircle className="mt-0.5 size-4 shrink-0" />
                <span>{form.formState.errors.root.message}</span>
              </div>
            ) : null}

            <div className="flex flex-wrap justify-end gap-3">
              <Button
                type="button"
                variant="outline"
                className="min-h-[44px] rounded-lg px-4"
                disabled={!form.formState.isDirty || saveProfileMutation.isPending || isReadOnlyMode}
                onClick={() =>
                  form.reset({
                    baseCurrencyCode: currentUser.baseCurrencyCode,
                    telegramUserId: currentUser.telegramUserId != null ? String(currentUser.telegramUserId) : '',
                  })
                }
              >
                Сбросить
              </Button>
              <Button
                type="submit"
                className="min-h-[44px] rounded-lg px-4"
                disabled={!form.formState.isDirty || saveProfileMutation.isPending || isReadOnlyMode}
              >
                <Check className="size-4" />
                Сохранить
              </Button>
            </div>
          </form>
        </PageCard>

        <PageCard
          title="Подписка"
          description="Управляйте доступом к полному режиму приложения."
          actions={<SubscriptionStatusBadge user={currentUser} />}
        >
          <p className="text-sm text-muted-foreground">
            {isSubscriptionActive ? (
              <>
                Активна до <strong className="text-foreground">{formatDateLabel(currentUser.subscription.expiresAtUtc)}</strong>
              </>
            ) : (
              'Сейчас доступен только режим просмотра.'
            )}
          </p>

          <div className="mt-5 grid gap-4 lg:grid-cols-2">
            {paymentPlans.map((plan) => (
              <article
                key={plan.plan}
                className="rounded-xl border border-border bg-background/35 p-4 shadow-[var(--ft-shadow-sm)]"
              >
                <h3 className="text-base font-semibold text-foreground">{plan.title}</h3>
                <p className="mt-2 text-3xl font-semibold tracking-tight text-primary">
                  {formatCurrency(plan.price, 'RUB')}
                </p>
                <p className="mt-2 text-sm leading-6 text-muted-foreground">{plan.hint}</p>
                <Button
                  className="mt-4 min-h-[44px] rounded-lg px-4"
                  disabled={simulatePaymentMutation.isPending || isSubscriptionActive}
                  onClick={() => void handlePay(plan.plan)}
                >
                  <CreditCard className="size-4" />
                  Оплатить
                </Button>
              </article>
            ))}
          </div>

          {subscriptionError ? (
            <div className="mt-4 flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
              <AlertCircle className="mt-0.5 size-4 shrink-0" />
              <span>{subscriptionError}</span>
            </div>
          ) : null}

          <p className="mt-4 text-sm text-muted-foreground">
            Сейчас оплата имитируется: при нажатии «Оплатить» выдается бесплатный доступ на 1 месяц.
          </p>
        </PageCard>

        <PageCard muted>
          <Accordion type="single" collapsible defaultValue="payments">
            <AccordionItem value="payments" className="border-none bg-transparent shadow-none">
              <AccordionTrigger className="px-0 py-0 hover:text-foreground">
                <div className="flex items-center gap-3">
                  <span className="text-lg font-semibold text-foreground">История оплат</span>
                  {paymentsQuery.data?.length ? (
                    <Badge variant="outline" className="rounded-full px-2.5">
                      {paymentsQuery.data.length}
                    </Badge>
                  ) : null}
                </div>
              </AccordionTrigger>
              <AccordionContent className="px-0 pb-0">
                {paymentsQuery.isError ? (
                  <div className="space-y-3 pt-2">
                    <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
                      <AlertCircle className="mt-0.5 size-4 shrink-0" />
                      <span>
                        {resolveApiErrorMessage(
                          paymentsQuery.error,
                          'Не удалось загрузить историю оплат.',
                        )}
                      </span>
                    </div>
                    <Button
                      className="min-h-[44px] rounded-lg px-4"
                      variant="outline"
                      onClick={() => void paymentsQuery.refetch()}
                    >
                      Повторить
                    </Button>
                  </div>
                ) : (
                  <PaymentHistoryList
                    payments={paymentsQuery.data ?? []}
                    loading={paymentsQuery.isLoading}
                  />
                )}
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </PageCard>
      </div>
    </ErrorBoundary>
  );
}

// vue-app/src/pages/ProfilePage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { storeToRefs } from 'pinia';
import { useToast } from 'primevue/usetoast';
import { useRoute, useRouter } from 'vue-router';
import { useFinanceStore } from '../stores/finance';
import { useUserStore } from '../stores/user';
import CategoryManager from '../components/CategoryManager.vue';
import type { SubscriptionPlan } from '../types';

const financeStore = useFinanceStore();
const userStore = useUserStore();
const toast = useToast();
const router = useRouter();
const route = useRoute();

const { currencies, areCurrenciesLoading } = storeToRefs(financeStore);
const {
  currentUser,
  isLoading: isUserLoading,
  isSaving: isUserSaving,
  isReadOnlyMode,
  hasActiveSubscription,
  isSubscriptionProcessing,
  subscriptionPayments,
  areSubscriptionPaymentsLoading,
} = storeToRefs(userStore);

const form = reactive({
  baseCurrencyCode: '',
  telegramUserId: '',
});

const isPaymentHistoryOpen = ref(false);

const isLoading = computed(() => isUserLoading.value || areCurrenciesLoading.value);
const isSaving = computed(() => isUserSaving.value);
const isSubscriptionActive = computed(() => hasActiveSubscription.value);
const subscriptionExpiresAtLabel = computed(() => {
  const raw = currentUser.value?.subscription?.expiresAtUtc;
  if (!raw) return null;
  const date = new Date(raw);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleDateString('ru-RU');
});

const userInitials = computed(() => {
  const name = currentUser.value?.name;
  if (!name) return '?';
  const parts = name.trim().split(/\s+/);
  if (parts.length >= 2) {
    return (parts[0][0] + parts[1][0]).toUpperCase();
  }
  return parts[0].slice(0, 2).toUpperCase();
});

const subscriptionPlans = computed(() => {
  const monthPrice = currentUser.value?.subscription?.monthPriceRub ?? 390;
  const yearPrice = currentUser.value?.subscription?.yearPriceRub ?? 3900;

  return [
    {
      plan: 'Month' as SubscriptionPlan,
      title: '1 месяц',
      price: monthPrice,
      hint: 'Стандартная цена 390 ₽',
    },
    {
      plan: 'Year' as SubscriptionPlan,
      title: '1 год',
      price: yearPrice,
      hint: 'Стандартная цена 3 900 ₽',
    },
  ];
});

const formattedSubscriptionPayments = computed(() =>
  subscriptionPayments.value.map(payment => {
    const paidAt = new Date(payment.paidAtUtc);
    const periodStart = new Date(payment.subscriptionStartsAtUtc);
    const periodEnd = new Date(payment.subscriptionEndsAtUtc);

    return {
      ...payment,
      paidAtLabel: Number.isNaN(paidAt.getTime()) ? '—' : paidAt.toLocaleString('ru-RU'),
      periodLabel:
        Number.isNaN(periodStart.getTime()) || Number.isNaN(periodEnd.getTime())
          ? '—'
          : `${periodStart.toLocaleDateString('ru-RU')} - ${periodEnd.toLocaleDateString('ru-RU')}`,
      planLabel: payment.plan === 'Year' ? '1 год' : '1 месяц',
      chargedLabel: `${Math.round(payment.chargedPriceRub)} ₽`,
      listedLabel: `${Math.round(payment.listedPriceRub)} ₽`,
      statusLabel: payment.status === 'Succeeded'
        ? 'Успешно'
        : payment.status === 'Failed'
          ? 'Ошибка'
          : payment.status === 'Refunded'
            ? 'Возврат'
            : 'Отменено',
    };
  })
);

const activeTab = ref<'profile' | 'categories'>('profile');

const resolveTabFromHash = (hash: string) =>
  hash === '#categories' ? 'categories' : 'profile';

const setActiveTab = (tab: 'profile' | 'categories') => {
  activeTab.value = tab;
  const nextHash = tab === 'categories' ? '#categories' : '';
  if (route.hash !== nextHash) {
    router.replace({ hash: nextHash });
  }
};

const currencyOptions = computed(() =>
  currencies.value.map(currency => ({
    label: `${currency.symbol} ${currency.code} · ${currency.name}`,
    value: currency.code,
  }))
);

function normalizeTelegramId(value: string | null | undefined): string {
  if (!value) return '';
  const trimmed = value.trim();
  if (!trimmed.length) return '';
  return trimmed.replace(/\s+/g, '');
}

const sanitizedFormTelegramId = computed(() => normalizeTelegramId(form.telegramUserId));
const isTelegramIdValid = computed(() =>
  !sanitizedFormTelegramId.value || /^\d+$/.test(sanitizedFormTelegramId.value)
);

const hasChanges = computed(() => {
  if (!currentUser.value) return false;
  const currentCurrency = currentUser.value.baseCurrencyCode ?? '';
  const currentTelegram = currentUser.value.telegramUserId?.toString() ?? '';

  return (
    currentCurrency !== (form.baseCurrencyCode || '') ||
    currentTelegram !== sanitizedFormTelegramId.value
  );
});

const canSubmit = computed(() =>
  Boolean(form.baseCurrencyCode) && hasChanges.value && !isSaving.value && !isReadOnlyMode.value
);

function resetForm() {
  if (!currentUser.value) return;
  form.baseCurrencyCode = currentUser.value.baseCurrencyCode ?? '';
  form.telegramUserId = currentUser.value.telegramUserId?.toString() ?? '';
}

watch(currentUser, user => {
  if (user) {
    resetForm();
  }
}, { immediate: true });

watch(
  () => route.hash,
  hash => {
    activeTab.value = resolveTabFromHash(hash);
  },
  { immediate: true }
);

onMounted(async () => {
  await Promise.all([
    financeStore.fetchCurrencies(),
    financeStore.fetchCategories(),
    userStore.fetchCurrentUser(),
  ]);
  await userStore.fetchSubscriptionPayments();

  if (currentUser.value) {
    resetForm();
  }
});

async function handleSubmit() {
  if (isReadOnlyMode.value) {
    toast.add({
      severity: 'warn',
      summary: 'Режим просмотра',
      detail: 'Изменение профиля доступно только при активной подписке.',
      life: 3000,
    });
    return;
  }

  if (!form.baseCurrencyCode) {
    toast.add({
      severity: 'warn',
      summary: 'Выберите валюту',
      detail: 'Выберите базовую валюту перед обновлением профиля.',
      life: 2500,
    });
    return;
  }

  if (!isTelegramIdValid.value) {
    toast.add({
      severity: 'warn',
      summary: 'Некорректный Telegram ID',
      detail: 'Введите только цифры или оставьте поле пустым.',
      life: 3000,
    });
    return;
  }

  const parsedTelegramId = sanitizedFormTelegramId.value
    ? Number(sanitizedFormTelegramId.value)
    : null;

  const success = await userStore.saveProfileSettings({
    baseCurrencyCode: form.baseCurrencyCode,
    telegramUserId: parsedTelegramId,
  });

  if (success) {
    toast.add({
      severity: 'success',
      summary: 'Профиль обновлен',
      detail: 'Ваши изменения применены.',
      life: 2500,
    });
    resetForm();
  } else {
    toast.add({
      severity: 'error',
      summary: 'Ошибка сохранения',
      detail: 'Не удалось обновить профиль. Пожалуйста, попробуйте еще раз.',
      life: 3000,
    });
  }
}

function handleClearTelegram() {
  form.telegramUserId = '';
}

async function handlePay(plan: SubscriptionPlan) {
  const success = await userStore.simulateSubscriptionPayment(plan);
  if (success) {
    toast.add({
      severity: 'success',
      summary: 'Подписка активирована',
      detail: 'Оплата имитирована успешно. Выдан бесплатный доступ на 1 месяц.',
      life: 3500,
    });
    return;
  }

  toast.add({
    severity: 'error',
    summary: 'Не удалось активировать подписку',
    detail: 'Пожалуйста, попробуйте еще раз.',
    life: 3000,
  });
}
</script>

<template>
  <PageContainer class="profile-page">
    <PageHeader
      title="Настройки"
      subtitle="Управляйте профилем и подпиской"
      :breadcrumbs="[
        { label: 'Главная', to: '/analytics' },
        { label: 'Настройки' }
      ]"
    />

    <div class="profile-tabs">
      <div
        class="profile-tabs__bar"
        role="tablist"
        aria-label="Разделы настроек"
      >
        <button
          id="profile-tab"
          class="profile-tab"
          type="button"
          role="tab"
          :class="{ 'is-active': activeTab === 'profile' }"
          :aria-selected="activeTab === 'profile'"
          :tabindex="activeTab === 'profile' ? 0 : -1"
          aria-controls="profile-panel"
          @click="setActiveTab('profile')"
        >
          <i
            class="pi pi-cog"
            aria-hidden="true"
          />
          <span>Настройки</span>
        </button>
        <button
          id="categories-tab"
          class="profile-tab"
          type="button"
          role="tab"
          :class="{ 'is-active': activeTab === 'categories' }"
          :aria-selected="activeTab === 'categories'"
          :tabindex="activeTab === 'categories' ? 0 : -1"
          aria-controls="categories"
          @click="setActiveTab('categories')"
        >
          <i
            class="pi pi-tags"
            aria-hidden="true"
          />
          <span>Категории</span>
        </button>
      </div>

      <section
        v-show="activeTab === 'profile'"
        id="profile-panel"
        class="profile-tab-panel"
        role="tabpanel"
        aria-labelledby="profile-tab"
      >
        <!-- Card 1: Profile (read-only, muted) -->
        <UiCard
          class="profile-card"
          variant="muted"
          padding="lg"
        >
          <div class="profile-identity">
            <div
              class="profile-avatar"
              aria-hidden="true"
            >
              {{ userInitials }}
            </div>
            <div class="profile-identity__info">
              <p class="profile-identity__name">
                {{ currentUser?.name ?? '—' }}
              </p>
              <p class="profile-identity__email">
                {{ currentUser?.email ?? '—' }}
              </p>
            </div>
          </div>
        </UiCard>

        <!-- Card 2: App settings (editable) -->
        <UiCard
          id="telegram"
          class="profile-card"
          padding="lg"
        >
          <template #header>
            <div class="card-header">
              <div>
                <h3 class="card-title">
                  Основные настройки
                </h3>
              </div>
            </div>
          </template>

          <form
            class="settings-form"
            @submit.prevent="handleSubmit"
          >
            <div class="settings-grid">
              <div class="settings-field">
                <label
                  class="settings-label"
                  for="profileCurrency"
                >Базовая валюта</label>
                <UiSelect
                  id="profileCurrency"
                  v-model="form.baseCurrencyCode"
                  :options="currencyOptions"
                  option-label="label"
                  option-value="value"
                  placeholder="Выберите валюту"
                  :disabled="isLoading || isReadOnlyMode"
                />
                <small class="helper-text">
                  <template v-if="isLoading">Загрузка доступных валют…</template>
                  <template v-else>В этой валюте считается вся аналитика и отчёты</template>
                </small>
              </div>

              <div class="settings-field">
                <label
                  class="settings-label"
                  for="profileTelegram"
                >Telegram-бот</label>
                <div class="telegram-input">
                  <UiInputText
                    id="profileTelegram"
                    v-model="form.telegramUserId"
                    placeholder="123456789"
                    autocomplete="off"
                    :disabled="isSaving || isReadOnlyMode"
                  />
                  <UiButton
                    type="button"
                    label="Очистить"
                    variant="ghost"
                    size="sm"
                    :disabled="!form.telegramUserId || isSaving || isReadOnlyMode"
                    @click="handleClearTelegram"
                  />
                </div>
                <small class="helper-text">
                  Отправьте <code>/id</code> боту
                  <a
                    href="https://t.me/financetree_bot"
                    target="_blank"
                    rel="noopener noreferrer"
                  >@financetree_bot</a>
                  и вставьте цифры сюда. Оставьте пустым, чтобы отвязать.
                </small>
              </div>
            </div>

            <div class="settings-actions">
              <UiButton
                type="button"
                label="Сбросить"
                variant="ghost"
                :disabled="!hasChanges || isSaving || isReadOnlyMode"
                @click="resetForm"
              />
              <UiButton
                type="submit"
                label="Сохранить"
                icon="pi pi-check"
                :loading="isSaving"
                :disabled="!canSubmit"
              />
            </div>
          </form>
        </UiCard>

        <!-- Card 3: Subscription (outlined) -->
        <UiCard
          id="subscription"
          class="profile-card"
          variant="outlined"
          padding="lg"
        >
          <template #header>
            <div class="card-header">
              <h3 class="card-title">
                Подписка
              </h3>
              <StatusBadge
                :label="isSubscriptionActive ? 'Активна' : 'Только просмотр'"
                :severity="isSubscriptionActive ? 'success' : 'warning'"
                :icon="isSubscriptionActive ? 'pi-check-circle' : 'pi-lock'"
              />
            </div>
          </template>

          <p
            v-if="isSubscriptionActive"
            class="subscription-status-line"
          >
            Активна до <strong>{{ subscriptionExpiresAtLabel ?? '—' }}</strong>
          </p>
          <p
            v-else
            class="subscription-status-line"
          >
            Доступен только просмотр
          </p>

          <div class="subscription-plans">
            <article
              v-for="plan in subscriptionPlans"
              :key="plan.plan"
              class="subscription-plan"
            >
              <h4>{{ plan.title }}</h4>
              <p class="subscription-plan__price">
                {{ plan.price }} ₽
              </p>
              <p class="subscription-plan__hint">
                {{ plan.hint }}
              </p>
              <UiButton
                label="Оплатить"
                icon="pi pi-credit-card"
                :loading="isSubscriptionProcessing"
                :disabled="isSubscriptionProcessing || isSubscriptionActive"
                @click="handlePay(plan.plan)"
              />
            </article>
          </div>

          <p class="subscription-sim-note">
            Сейчас оплата имитируется: при нажатии «Оплатить» выдается бесплатный доступ на 1 месяц.
          </p>
        </UiCard>

        <!-- Card 4: Payment history (muted, collapsible) -->
        <UiCard
          class="profile-card"
          variant="muted"
          padding="lg"
        >
          <button
            type="button"
            class="collapsible-header"
            :aria-expanded="isPaymentHistoryOpen"
            aria-controls="payment-history-content"
            @click="isPaymentHistoryOpen = !isPaymentHistoryOpen"
          >
            <h3 class="card-title">
              История оплат
            </h3>
            <span
              v-if="formattedSubscriptionPayments.length > 0"
              class="payment-count-badge"
            >
              {{ formattedSubscriptionPayments.length }}
            </span>
            <i
              class="pi collapsible-chevron"
              :class="isPaymentHistoryOpen ? 'pi-chevron-up' : 'pi-chevron-down'"
              aria-hidden="true"
            />
          </button>

          <div
            id="payment-history-content"
            v-show="isPaymentHistoryOpen"
            class="payment-history-body"
          >
            <div
              v-if="areSubscriptionPaymentsLoading"
              class="payment-history__skeleton"
            >
              <UiSkeleton
                v-for="i in 3"
                :key="i"
                height="52px"
              />
            </div>

            <div
              v-else-if="formattedSubscriptionPayments.length === 0"
              class="payment-history__empty"
            >
              Оплат пока нет. Когда вы нажмете «Оплатить», запись появится здесь.
            </div>

            <ul
              v-else
              class="payment-history__list"
            >
              <li
                v-for="payment in formattedSubscriptionPayments"
                :key="payment.id"
                class="payment-history__item"
              >
                <div>
                  <p class="payment-history__title">
                    {{ payment.planLabel }} · {{ payment.statusLabel }}
                  </p>
                  <p class="payment-history__meta">
                    {{ payment.paidAtLabel }} · Период: {{ payment.periodLabel }}
                  </p>
                </div>
                <div class="payment-history__amounts">
                  <span>Списано: {{ payment.chargedLabel }}</span>
                  <small>Тариф: {{ payment.listedLabel }}</small>
                </div>
              </li>
            </ul>
          </div>
        </UiCard>
      </section>

      <section
        v-show="activeTab === 'categories'"
        id="categories"
        class="profile-tab-panel profile-tab-panel--categories"
        role="tabpanel"
        aria-labelledby="categories-tab"
      >
        <CategoryManager :readonly="isReadOnlyMode" />
      </section>
    </div>
  </PageContainer>
</template>

<style scoped>
.profile-page {
  gap: var(--ft-space-6, var(--space-6));
}

.profile-tabs {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-5, var(--space-5));
}

.profile-tabs__bar {
  display: inline-flex;
  gap: var(--ft-space-2, var(--space-2));
  align-items: center;

  padding: var(--ft-space-2, var(--space-2));

  background: linear-gradient(135deg, color-mix(in srgb, var(--surface-2) 70%, transparent), var(--surface-1));
  border: 1px solid var(--border);
  border-radius: var(--ft-radius-lg, var(--radius-lg));
  box-shadow: var(--shadow-soft);
}

.profile-tab {
  cursor: pointer;

  display: inline-flex;
  gap: var(--ft-space-2, var(--space-2));
  align-items: center;

  padding: 0.6rem 1.4rem;

  font-size: var(--ft-text-base);
  font-weight: 600;
  color: var(--text);

  background: transparent;
  border: none;
  border-radius: var(--ft-radius-lg, var(--radius-lg));

  transition:
    background-color var(--ft-transition-fast),
    color var(--ft-transition-fast),
    box-shadow var(--ft-transition-fast);
}

.profile-tab.is-active {
  color: var(--ft-text-inverse);
  background: color-mix(in srgb, var(--accent) 75%, transparent);
  box-shadow: var(--ft-shadow-md);
}

.profile-tab i {
  font-size: 1rem;
}

.profile-tab:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--accent) 60%, transparent);
  outline-offset: 2px;
}

.profile-tab-panel {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-5, var(--space-5));
}

.profile-tab-panel--categories {
  scroll-margin-top: 120px;
}

.profile-card {
  gap: var(--ft-space-5, var(--space-5));
}

:deep(.profile-card .ui-card__body) {
  gap: var(--ft-space-5, var(--space-5));
}

/* Card 1: Profile identity */
.profile-identity {
  display: flex;
  gap: var(--ft-space-4, var(--space-4));
  align-items: center;
}

.profile-avatar {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  justify-content: center;

  width: 48px;
  height: 48px;

  font-size: var(--ft-text-base);
  font-weight: 700;
  color: var(--ft-text-inverse);
  letter-spacing: 0.04em;

  background: linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 70%, #000));
  border-radius: 50%;
}

.profile-identity__info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.profile-identity__name {
  margin: 0;
  font-size: var(--ft-text-base);
  font-weight: 600;
  color: var(--text);
}

.profile-identity__email {
  margin: 0;
  font-size: var(--ft-text-sm);
  color: var(--text-muted);
}

/* Card 2: Settings form */
.card-header {
  display: flex;
  gap: 1rem;
  align-items: center;
  justify-content: space-between;
}

.card-title {
  margin: 0;
  font-size: var(--ft-text-xl);
  font-weight: var(--ft-font-semibold);
  color: var(--text);
}

.settings-form {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-5, var(--space-5));
}

.settings-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: var(--ft-space-4, var(--space-4));
}

.settings-field {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-2, var(--space-2));
}

.settings-label {
  font-size: var(--ft-text-xs);
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.16em;
}

.helper-text {
  font-size: var(--ft-text-xs);
  color: var(--text-muted);
}

.helper-text code {
  padding: 0.1em 0.35em;

  font-family: var(--ft-font-mono, 'JetBrains Mono', monospace);
  font-size: 0.9em;

  background: var(--surface-2);
  border-radius: var(--ft-radius-sm, var(--radius-sm));
}

.telegram-input {
  display: flex;
  gap: var(--ft-space-3, var(--space-3));
  align-items: center;
}

.settings-actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-3, var(--space-3));
  justify-content: flex-end;
}

.settings-actions :deep(.ui-button) {
  min-width: 140px;
}

/* Card 3: Subscription */
.subscription-status-line {
  margin: 0;
  font-size: var(--ft-text-sm);
  color: var(--text-muted);
}

.subscription-plans {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: var(--ft-space-3, var(--space-3));
}

.subscription-plan {
  display: grid;
  gap: var(--ft-space-2, var(--space-2));

  padding: var(--ft-space-3, var(--space-3));

  background: var(--surface-1);
  border: 1px solid var(--border);
  border-radius: var(--ft-radius-md, var(--radius-md));
}

.subscription-plan h4 {
  margin: 0;
}

.subscription-plan__price {
  margin: 0;
  font-size: var(--ft-text-xl);
  font-weight: 700;
}

.subscription-plan__hint {
  margin: 0;
  font-size: var(--ft-text-sm);
  color: var(--text-muted);
}

.subscription-sim-note {
  margin: 0;
  font-size: var(--ft-text-xs);
  color: var(--text-muted);
}

/* Card 4: Collapsible payment history */
.collapsible-header {
  cursor: pointer;

  display: flex;
  gap: var(--ft-space-3, var(--space-3));
  align-items: center;

  width: 100%;
  padding: 0;

  color: inherit;

  background: none;
  border: none;
}

.collapsible-header:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--accent) 60%, transparent);
  outline-offset: 2px;
  border-radius: var(--ft-radius-sm, var(--radius-sm));
}

.payment-count-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;

  min-width: 22px;
  height: 22px;
  padding: 0 6px;

  font-size: var(--ft-text-xs);
  font-weight: 600;
  color: var(--ft-text-inverse);

  background: color-mix(in srgb, var(--accent) 80%, transparent);
  border-radius: 11px;
}

.collapsible-chevron {
  margin-left: auto;
  font-size: 0.875rem;
  color: var(--text-muted);
  transition: transform var(--ft-transition-fast);
}

.payment-history-body {
  margin-top: var(--ft-space-4, var(--space-4));
}

.payment-history__skeleton {
  display: grid;
  gap: var(--ft-space-2, var(--space-2));
}

.payment-history__empty {
  padding: var(--ft-space-3, var(--space-3));

  color: var(--text-muted);

  background: var(--surface-1);
  border: 1px dashed var(--border);
  border-radius: var(--ft-radius-md, var(--radius-md));
}

.payment-history__list {
  display: grid;
  gap: var(--ft-space-2, var(--space-2));

  margin: 0;
  padding: 0;

  list-style: none;
}

.payment-history__item {
  display: flex;
  gap: var(--ft-space-3, var(--space-3));
  align-items: flex-start;
  justify-content: space-between;

  padding: var(--ft-space-3, var(--space-3));

  background: var(--surface-1);
  border: 1px solid var(--border);
  border-radius: var(--ft-radius-md, var(--radius-md));
}

.payment-history__title {
  margin: 0;
  font-weight: 600;
}

.payment-history__meta {
  margin: var(--ft-space-1, var(--space-1)) 0 0;
  font-size: var(--ft-text-sm);
  color: var(--text-muted);
}

.payment-history__amounts {
  display: grid;
  gap: 2px;
  text-align: right;
}

.payment-history__amounts small {
  color: var(--text-muted);
}

@media (width <= 768px) {
  .profile-tabs__bar {
    justify-content: space-between;
    width: 100%;
  }

  .profile-tab {
    flex: 1;
    text-align: center;
  }

  .telegram-input {
    flex-direction: column;
    align-items: stretch;
  }

  .settings-actions {
    flex-direction: column-reverse;
    align-items: stretch;
  }

  .payment-history__item {
    flex-direction: column;
  }

  .payment-history__amounts {
    text-align: left;
  }
}
</style>
