// react-app/src/features/accounts/AccountCard.tsx
import { MoreVertical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Switch } from '@/components/ui/switch';
import { cn } from '@/utils/cn';
import { formatCurrency } from '@/utils/format';
import type { ManagedAccount } from './accountModels';

interface AccountCardProps {
  account: ManagedAccount;
  baseCurrencyCode: string;
  readonly?: boolean;
  interactionLocked?: boolean;
  isPrimaryLoading?: boolean;
  isLiquidityLoading?: boolean;
  isArchiveLoading?: boolean;
  onSetPrimary: () => void;
  onEdit: () => void;
  onArchive: () => void;
  onUnarchive: () => void;
  onAdjustBalance: () => void;
  onLiquidityChange: (value: boolean) => void;
}

export function AccountCard({
  account,
  baseCurrencyCode,
  readonly = false,
  interactionLocked = false,
  isPrimaryLoading = false,
  isLiquidityLoading = false,
  isArchiveLoading = false,
  onSetPrimary,
  onEdit,
  onArchive,
  onUnarchive,
  onAdjustBalance,
  onLiquidityChange,
}: AccountCardProps) {
  const showSecondaryBalance = account.currencyCode !== baseCurrencyCode;
  const showMenu = !interactionLocked && (!readonly || account.isArchived);
  const liquidityLabel = account.isLiquid ? 'Ликвидный' : 'Неликвидный';

  return (
    <article
      className={cn(
        'flex min-h-[180px] flex-col rounded-xl border border-border/80 bg-card/95 px-5 py-5 text-foreground shadow-[var(--ft-shadow-sm)] transition-[border-color,box-shadow,background-color] duration-200',
        !readonly && 'hover:border-primary/35 hover:shadow-[var(--ft-shadow-md)]',
        account.isMain &&
          !readonly &&
          'border-primary/45 bg-primary/5',
      )}
    >
      <div className="flex items-start gap-3">
        <div className="min-w-0 flex-1">
          <h3 className="truncate text-xl font-semibold tracking-tight text-foreground">
            {account.name}
          </h3>
          <p className="mt-1 text-sm text-muted-foreground">Банковский счёт</p>
        </div>

        {showMenu ? (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon-lg"
                className="size-11 rounded-xl border border-border/70 bg-background/30 shadow-[var(--ft-shadow-sm)] hover:bg-muted/80"
                aria-label={`Действия для счёта ${account.name}`}
                disabled={isArchiveLoading || isPrimaryLoading}
              >
                <MoreVertical className="size-5" />
              </Button>
            </DropdownMenuTrigger>

            <DropdownMenuContent align="end" className="w-56">
              {!readonly ? (
                <>
                  <DropdownMenuItem onSelect={onAdjustBalance}>
                    Корректировать баланс
                  </DropdownMenuItem>
                  <DropdownMenuItem onSelect={onEdit}>Переименовать</DropdownMenuItem>
                  {!account.isMain ? (
                    <DropdownMenuItem
                      onSelect={onSetPrimary}
                      disabled={isPrimaryLoading}
                    >
                      Сделать основным
                    </DropdownMenuItem>
                  ) : null}
                  {!account.isArchived ? (
                    <DropdownMenuItem
                      onSelect={onArchive}
                      disabled={isArchiveLoading}
                      destructive
                    >
                      Архивировать
                    </DropdownMenuItem>
                  ) : null}
                </>
              ) : null}

              {account.isArchived ? (
                <DropdownMenuItem
                  onSelect={onUnarchive}
                  disabled={isArchiveLoading}
                >
                  Разархивировать
                </DropdownMenuItem>
              ) : null}
            </DropdownMenuContent>
          </DropdownMenu>
        ) : null}
      </div>

      <div className="mt-6 space-y-1.5">
        <p className="text-3xl font-semibold tracking-tight text-foreground [font-variant-numeric:tabular-nums]">
          {formatCurrency(account.balanceInBaseCurrency, baseCurrencyCode)}
        </p>
        {showSecondaryBalance ? (
          <p className="text-sm text-muted-foreground [font-variant-numeric:tabular-nums]">
            {formatCurrency(account.balance, account.currencyCode)}
          </p>
        ) : null}
      </div>

      <div className="mt-auto flex items-end justify-between gap-4 border-t border-border/70 pt-4">
        <div className="text-xl font-medium text-primary [font-variant-numeric:tabular-nums]">
          {account.currency?.symbol ?? '¤'} {account.currencyCode}
        </div>

        {readonly || interactionLocked ? (
          <span className="text-sm text-muted-foreground">{liquidityLabel}</span>
        ) : (
          <label className="flex min-h-[44px] items-center gap-3 text-sm text-muted-foreground">
            <span>{liquidityLabel}</span>
            <Switch
              checked={account.isLiquid}
              onCheckedChange={onLiquidityChange}
              disabled={isLiquidityLoading}
              aria-label={
                account.isLiquid ? 'Сделать счёт неликвидным' : 'Сделать счёт ликвидным'
              }
            />
          </label>
        )}
      </div>
    </article>
  );
}

// vue-app/src/components/AccountCard.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import UiToggleSwitch from '@/ui/UiToggleSwitch.vue'
import UiMenu from '@/ui/UiMenu.vue'
import type { MenuItem } from 'primevue/menuitem'
import type { Account } from '../types'
import { formatCurrency } from '../utils/formatters'
import { useUserStore } from '../stores/user'
import UiButton from '../ui/UiButton.vue'

const props = withDefaults(defineProps<{
  account: Account
  readonly?: boolean
  interactionLocked?: boolean
  isPrimaryLoading?: boolean
  isLiquidityLoading?: boolean
  isArchiveLoading?: boolean
}>(), {
  readonly: false,
  interactionLocked: false,
  isPrimaryLoading: false,
  isLiquidityLoading: false,
  isArchiveLoading: false,
})

const emit = defineEmits<{
  setPrimary: []
  edit: []
  archive: []
  unarchive: []
  open: []
  updateLiquidity: [value: boolean]
}>()

const menuRef = ref()
const userStore = useUserStore()

const currencyDisplay = computed(() => {
  const symbol = props.account.currency?.symbol || ''
  const code = props.account.currency?.code || props.account.currencyCode
  return `${symbol} ${code}`
})

const baseCurrencyCode = computed(() => userStore.baseCurrencyCode ?? props.account.currencyCode)
const balanceInBase = computed(() => props.account.balanceInBaseCurrency ?? 0)
const balanceInAccount = computed(() => props.account.balance ?? 0)

const showSecondaryBalance = computed(() =>
  baseCurrencyCode.value.toUpperCase() !== props.account.currencyCode.toUpperCase()
)

const formattedBaseBalance = computed(() =>
  formatCurrency(balanceInBase.value, baseCurrencyCode.value)
)

const formattedAccountBalance = computed(() =>
  formatCurrency(balanceInAccount.value, props.account.currencyCode)
)

const liquidityModel = computed({
  get: () => props.account.isLiquid,
  set: (value: boolean) => emit('updateLiquidity', value),
})

const liquidityLabel = computed(() => (props.account.isLiquid ? 'Ликвидный' : 'Неликвидный'))

const menuItems = computed<MenuItem[]>(() => {
  if (props.readonly || props.interactionLocked) return []

  const items: MenuItem[] = [
    {
      label: 'Корректировать баланс',
      icon: 'pi pi-sliders-h',
      command: () => emit('open'),
    },
    {
      label: 'Переименовать',
      icon: 'pi pi-pencil',
      command: () => emit('edit')
    },
  ]

  if (!props.account.isMain) {
    items.push({
      label: 'Сделать основным',
      icon: 'pi pi-star',
      command: () => emit('setPrimary'),
    })
  }

  if (props.account.isArchived) {
    items.push({
      label: 'Разархивировать',
      icon: 'pi pi-box',
      command: () => emit('unarchive'),
    })
  } else {
    items.push({
      label: 'Архивировать',
      icon: 'pi pi-inbox',
      command: () => emit('archive'),
    })
  }

  return items
})

const toggleMenu = (event: Event) => {
  menuRef.value.toggle(event)
}
</script>

<template>
  <article
    class="account-card ft-card"
    :class="{
      'account-card--primary': account.isMain && !readonly,
      'account-card--readonly': readonly
    }"
  >
    <header class="account-card__header">
      <div class="account-card__title">
        <h3>{{ account.name }}</h3>
        <p>Банковский счет</p>
      </div>

      <div class="account-card__header-actions">
        <UiButton
          v-if="menuItems.length > 0"
          class="account-card__icon-button"
          variant="ghost"
          size="sm"
          icon="pi pi-ellipsis-v"
          :aria-label="`Действия для счета ${account.name}`"
          @click.stop="toggleMenu"
        />
        <UiMenu
          ref="menuRef"
          :model="menuItems"
          :popup="true"
          :pt="{
            root: { class: 'account-menu' },
          }"
        />
      </div>
    </header>

    <div class="account-card__current-balance">
      <p class="account-card__current-balance-main">
        {{ formattedBaseBalance }}
      </p>
      <p
        v-if="showSecondaryBalance"
        class="account-card__current-balance-secondary"
      >
        {{ formattedAccountBalance }}
      </p>
    </div>

    <div class="account-card__footer-compact">
      <div class="currency-display-compact">
        {{ currencyDisplay }}
      </div>
      <div
        class="liquidity-control-compact"
        @click.stop
      >
        <UiToggleSwitch
          v-if="!readonly && !interactionLocked"
          v-model="liquidityModel"
          :disabled="isLiquidityLoading"
        />
        <span
          v-else
          class="account-card__readonly-value"
        >
          {{ liquidityLabel }}
        </span>
        <span
          v-if="!readonly && !interactionLocked"
          class="liquidity-label-compact"
        >
          {{ liquidityLabel }}
        </span>
      </div>
    </div>
  </article>
</template>

<style scoped>
.account-card {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-2);

  min-height: 180px;

  background: var(--ft-surface-soft);
  border: 1px solid var(--ft-border-soft);

  transition:
    border-color var(--ft-transition-base),
    box-shadow var(--ft-transition-base);
}

.account-card:hover {
  border-color: var(--ft-primary-200);
  box-shadow: var(--ft-shadow-md);
}

.account-card--primary {
  background: linear-gradient(
    135deg,
    color-mix(in srgb, var(--ft-primary-500) 5%, transparent) 0%,
    color-mix(in srgb, var(--ft-primary-500) 10%, transparent) 100%
  );
  border-color: var(--ft-primary-300);
}

.account-card--readonly {
  cursor: default;
}

.account-card--readonly:hover {
  border-color: var(--ft-border-soft);
  box-shadow: none;
}

.account-card__header {
  display: flex;
  gap: var(--ft-space-3);
  align-items: center;
}

.account-card__title {
  flex: 1;
  min-width: 0;
}

.account-card__title h3 {
  overflow: hidden;

  margin: 0;

  font-size: var(--ft-text-lg);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-heading);
  text-overflow: ellipsis;
  white-space: nowrap;
}

.account-card__title p {
  margin: var(--ft-space-1) 0 0;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-muted);
}

.account-card__header-actions {
  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;
}

.account-card__icon-button {
  width: 44px;
  min-width: 44px;
  height: 44px;
  border-radius: var(--ft-radius-lg);
}

.account-card__badges {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-2);
  align-items: center;


}

.account-card__current-balance {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  gap: var(--ft-space-1);
}

.account-card__current-balance-main {
  margin: 0;

  font-size: clamp(1.1rem, 1.5vw, 1.4rem);
  font-weight: var(--ft-font-semibold);
  font-variant-numeric: tabular-nums;
  color: var(--ft-heading);
}

.account-card__current-balance-secondary {
  margin: 0;
  font-size: var(--ft-text-sm); /* Smaller font */
  font-variant-numeric: tabular-nums;
  color: var(--ft-text-muted);
}

.account-card__footer-compact {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: auto;
  padding-top: var(--ft-space-2);
  border-top: 1px solid var(--ft-border-soft);
}

.currency-display-compact {
  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-primary-500);
}

.liquidity-control-compact {
  display: flex;
  gap: var(--ft-space-2);
  align-items: center;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-muted);
}

.liquidity-label-compact {
  font-weight: var(--ft-font-medium);
}
</style>
