// react-app/src/features/goals/GoalParametersPanel.tsx
import { FormField } from '@/components/common/FormField';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import type { GoalSimulationParametersDto } from '@/types';
import { formatEditableNumber } from '@/utils/format';
import type { GoalParameterField, GoalParameterOverrides } from './goalModels';
import { resolveGoalParamValue } from './goalUtils';

const GOAL_PARAMETER_FIELDS: GoalParameterField[] = [
  {
    key: 'initialCapital',
    label: 'Начальный капитал',
    min: 0,
    max: 1_000_000_000_000,
    step: 1_000,
  },
  {
    key: 'monthlyIncome',
    label: 'Ежемесячный доход',
    min: 0,
    max: 1_000_000_000,
    step: 1_000,
  },
  {
    key: 'monthlyExpenses',
    label: 'Ежемесячные расходы',
    min: 0,
    max: 1_000_000_000,
    step: 1_000,
  },
  {
    key: 'annualReturnRate',
    label: 'Доходность инвестиций',
    hint: '% годовых',
    isPercent: true,
    min: 0,
    max: 100,
    step: 0.1,
  },
];

function getDisplayValue(
  field: GoalParameterField,
  overrides: GoalParameterOverrides,
  resolvedParams: GoalSimulationParametersDto
): string {
  const currentValue = overrides[field.key] ?? resolveGoalParamValue(resolvedParams, field.key);
  const displayValue = field.isPercent ? currentValue * 100 : currentValue;

  if (!Number.isFinite(displayValue)) {
    return '';
  }

  return formatEditableNumber(displayValue, field.isPercent ? 1 : 2);
}

interface GoalParametersPanelProps {
  resolvedParams: GoalSimulationParametersDto;
  overrides: GoalParameterOverrides;
  onChange: (nextOverrides: GoalParameterOverrides) => void;
}

export function GoalParametersPanel({
  resolvedParams,
  overrides,
  onChange,
}: GoalParametersPanelProps) {
  return (
    <Card className="rounded-2xl border border-border/80 bg-card/95 shadow-[var(--ft-shadow-sm)]">
      <CardHeader className="border-b border-border/70 pb-4">
        <CardTitle className="text-lg font-semibold text-foreground">
          Параметры симуляции
        </CardTitle>
        <CardDescription>
          Значения можно оставить автоматическими или скорректировать вручную.
        </CardDescription>
      </CardHeader>

      <CardContent className="pt-6">
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {GOAL_PARAMETER_FIELDS.map((field) => {
            const isOverridden = overrides[field.key] != null;

            return (
              <div
                key={field.key}
                className="rounded-2xl border border-border/70 bg-muted/15 p-4"
              >
                <div className="mb-3 flex min-h-[44px] flex-wrap items-center gap-2">
                  <span className="min-w-0 flex-1 text-sm font-semibold text-foreground">
                    {field.label}
                  </span>
                  {!isOverridden ? (
                    <span className="rounded-full bg-[color-mix(in_srgb,var(--ft-success-500)_16%,transparent)] px-2.5 py-1 text-xs font-medium text-[var(--ft-success-400)]">
                      авто
                    </span>
                  ) : (
                    <Button
                      type="button"
                      variant="ghost"
                      className="min-h-[32px] rounded-full px-3 text-xs"
                      onClick={() =>
                        onChange({
                          ...overrides,
                          [field.key]: null,
                        })
                      }
                    >
                      Сбросить
                    </Button>
                  )}
                </div>

                <FormField
                  label={field.label}
                  labelSrOnly
                  hint={field.hint}
                >
                  <Input
                    type="number"
                    min={field.min}
                    max={field.max}
                    step={field.step ?? 1}
                    inputMode="decimal"
                    className="h-11 rounded-xl"
                    value={getDisplayValue(field, overrides, resolvedParams)}
                    onChange={(event) => {
                      const raw = event.target.value.trim();

                      if (raw.length === 0) {
                        onChange({
                          ...overrides,
                          [field.key]: null,
                        });
                        return;
                      }

                      const parsed = Number(raw);
                      if (Number.isNaN(parsed)) {
                        return;
                      }

                      onChange({
                        ...overrides,
                        [field.key]: field.isPercent ? parsed / 100 : parsed,
                      });
                    }}
                  />
                </FormField>
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}

// vue-app/src/features/goals/components/GoalParametersPanel.vue
<script setup lang="ts">
import { reactive, watch } from 'vue'
import InputNumber from 'primevue/inputnumber'
import type { GoalParameterOverrides, GoalSimulationParametersDto } from '@/types.ts'

type OverrideField = keyof GoalParameterOverrides

type ParameterField = {
  key: OverrideField
  label: string
  hint: string
  isPercent: boolean
  min: number
  max: number
}

const props = defineProps<{
  resolvedParams: GoalSimulationParametersDto | null
  modelValue: GoalParameterOverrides
}>()

const emit = defineEmits<{
  'update:modelValue': [overrides: GoalParameterOverrides]
}>()

const overrides = reactive<GoalParameterOverrides>({ ...props.modelValue })
const overrideKeys: OverrideField[] = ['initialCapital', 'monthlyIncome', 'monthlyExpenses', 'annualReturnRate']

watch(
  () => props.modelValue,
  value => {
    for (const key of overrideKeys)
      overrides[key] = value[key] ?? null
  },
  { deep: true },
)

const fields: ParameterField[] = [
  {
    key: 'initialCapital',
    label: 'Начальный капитал',
    hint: '',
    isPercent: false,
    min: 0,
    max: 1_000_000_000_000,
  },
  {
    key: 'monthlyIncome',
    label: 'Ежемесячный доход',
    hint: '',
    isPercent: false,
    min: 0,
    max: 1_000_000_000,
  },
  {
    key: 'monthlyExpenses',
    label: 'Ежемесячные расходы',
    hint: '',
    isPercent: false,
    min: 0,
    max: 1_000_000_000,
  },
  {
    key: 'annualReturnRate',
    label: 'Доходность инвестиций',
    hint: '(% годовых)',
    isPercent: true,
    min: 0,
    max: 100,
  },
]

function isOverridden(field: OverrideField): boolean {
  return overrides[field] != null
}

function getResolvedValue(field: OverrideField): number {
  if (!props.resolvedParams)
    return 0

  switch (field) {
    case 'initialCapital':
      return props.resolvedParams.initialCapital
    case 'monthlyIncome':
      return props.resolvedParams.monthlyIncome
    case 'monthlyExpenses':
      return props.resolvedParams.monthlyExpenses
    case 'annualReturnRate':
      return props.resolvedParams.annualReturnRate
    default:
      return 0
  }
}

function getDisplayValue(field: ParameterField): number {
  const rawValue = overrides[field.key] ?? getResolvedValue(field.key)
  return field.isPercent ? rawValue * 100 : rawValue
}

function areSameNumber(a: number | null | undefined, b: number | null | undefined): boolean {
  if (a == null || b == null)
    return a == null && b == null

  return Math.abs(a - b) < 0.000001
}

function onFieldChange(field: ParameterField, value: number | null) {
  const normalizedValue =
    value == null
      ? null
      : field.isPercent
        ? value / 100
        : value

  const currentOverride = overrides[field.key] ?? null
  if (areSameNumber(currentOverride, normalizedValue))
    return

  if (currentOverride == null && normalizedValue != null && areSameNumber(normalizedValue, getResolvedValue(field.key)))
    return

  overrides[field.key] = normalizedValue
  emit('update:modelValue', { ...overrides })
}

function resetField(field: OverrideField) {
  overrides[field] = null
  emit('update:modelValue', { ...overrides })
}
</script>

<template>
  <div class="params-panel">
    <div
      v-for="field in fields"
      :key="field.key"
      class="param-row"
    >
      <div class="param-label">
        <span>{{ field.label }}</span>
        <span
          v-if="field.hint"
          class="param-hint"
        >{{ field.hint }}</span>
        <span
          v-if="!isOverridden(field.key)"
          class="badge badge--auto"
        >авто</span>
        <button
          v-else
          type="button"
          class="reset-btn"
          :aria-label="`Сбросить параметр ${field.label}`"
          @click="resetField(field.key)"
        >
          сбросить
        </button>
      </div>

      <InputNumber
        :model-value="getDisplayValue(field)"
        :min="field.min"
        :max="field.max"
        :min-fraction-digits="field.isPercent ? 1 : 0"
        :max-fraction-digits="field.isPercent ? 1 : 0"
        :suffix="field.isPercent ? '%' : ''"
        locale="ru-RU"
        fluid
        @update:model-value="(value) => onFieldChange(field, value)"
      />
    </div>
  </div>
</template>

<style scoped>
.params-panel {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--ft-space-4);
}

.param-row {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-2);
}

.param-label {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-2);
  align-items: center;

  font-size: var(--ft-text-sm);
  color: var(--ft-text-muted);
}

.param-hint {
  color: var(--ft-text-tertiary);
}

.badge {
  padding: 1px 5px;

  font-size: var(--ft-text-xs);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.03em;

  border-radius: var(--ft-radius-sm);
}

.badge--auto {
  color: var(--ft-success-500);
  background: color-mix(in srgb, var(--ft-success-500) 15%, transparent);
}

.reset-btn {
  cursor: pointer;

  padding: 0;

  font-size: var(--ft-text-xs);
  font-weight: 600;
  color: var(--ft-warning-500);
  text-transform: uppercase;
  letter-spacing: 0.03em;
  text-decoration: none;

  background: color-mix(in srgb, var(--ft-warning-500) 15%, transparent);
  border: none;
  border-radius: var(--ft-radius-sm);
  padding: 1px 5px;
}

.reset-btn:hover {
  background: color-mix(in srgb, var(--ft-warning-500) 25%, transparent);
}

.reset-btn:focus-visible {
  outline: 2px solid var(--ft-primary-400);
  outline-offset: 2px;
}

@media (width <= 900px) {
  .params-panel {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (width <= 540px) {
  .params-panel {
    grid-template-columns: 1fr;
  }
}
</style>
