// react-app/src/features/investments/InvestmentsAccountsSection.tsx
import { BriefcaseBusiness, Inbox, SearchX } from 'lucide-react';
import { AccountsToolbar } from '@/features/accounts/AccountsToolbar';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/common/EmptyState';
import { Skeleton } from '@/components/ui/skeleton';
import type { InvestmentAccountViewModel, InvestmentsView } from './investmentModels';
import { InvestmentAccountCard } from './InvestmentAccountCard';

interface InvestmentsAccountsSectionProps {
  activeCount: number;
  archivedCount: number;
  accounts: InvestmentAccountViewModel[];
  view: InvestmentsView;
  searchInput: string;
  hasAnyInvestmentAccounts: boolean;
  hasSearch: boolean;
  loading: boolean;
  error: string | null;
  showInlineError: boolean;
  showBlockingError: boolean;
  baseCurrencyCode: string;
  canCreateAccount: boolean;
  isReadOnlyMode: boolean;
  onCreateAccount: () => void;
  onSearchChange: (value: string) => void;
  onViewChange: (view: InvestmentsView) => void;
  onRetry: () => void;
  onEditAccount: (account: InvestmentAccountViewModel) => void;
  onAdjustBalance: (account: InvestmentAccountViewModel) => void;
  onLiquidityChange: (account: InvestmentAccountViewModel, nextValue: boolean) => void;
  onArchive: (account: InvestmentAccountViewModel) => void;
  onUnarchive: (account: InvestmentAccountViewModel) => void;
  isLiquidityLoading: (accountId: string) => boolean;
  isArchiveLoading: (accountId: string) => boolean;
}

export function InvestmentsAccountsSection({
  activeCount,
  archivedCount,
  accounts,
  view,
  searchInput,
  hasAnyInvestmentAccounts,
  hasSearch,
  loading,
  error,
  showInlineError,
  showBlockingError,
  baseCurrencyCode,
  canCreateAccount,
  isReadOnlyMode,
  onCreateAccount,
  onSearchChange,
  onViewChange,
  onRetry,
  onEditAccount,
  onAdjustBalance,
  onLiquidityChange,
  onArchive,
  onUnarchive,
  isLiquidityLoading,
  isArchiveLoading,
}: InvestmentsAccountsSectionProps) {
  return (
    <section className="flex flex-col gap-4 rounded-2xl border border-border/80 bg-card/95 p-4 shadow-[var(--ft-shadow-sm)] sm:p-5">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Счета</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Управляйте инвестиционными счетами и следите за их статусом.
          </p>
        </div>

        <Button
          className="min-h-[44px] rounded-xl px-5"
          onClick={onCreateAccount}
          disabled={!canCreateAccount}
        >
          Добавить счёт
        </Button>
      </div>

      <AccountsToolbar
        view={view}
        activeCount={activeCount}
        archivedCount={archivedCount}
        searchValue={searchInput}
        onSearchChange={onSearchChange}
        onViewChange={onViewChange}
      />

      {showInlineError ? (
        <div className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm">
          <div className="font-medium text-foreground">Не удалось обновить список счетов</div>
          <div className="mt-1 text-muted-foreground">{error}</div>
          <Button className="mt-3 min-h-[44px]" variant="outline" onClick={onRetry}>
            Повторить
          </Button>
        </div>
      ) : null}

      {loading ? (
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
          {Array.from({ length: 4 }, (_, index) => (
            <Skeleton key={`investment-card-${index + 1}`} className="h-[168px] rounded-2xl" />
          ))}
        </div>
      ) : showBlockingError ? (
        <div className="rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm">
          <div className="font-medium text-foreground">Не удалось загрузить инвестиционные счета</div>
          <div className="mt-1 text-muted-foreground">{error}</div>
          <Button className="mt-3 min-h-[44px]" variant="outline" onClick={onRetry}>
            Повторить
          </Button>
        </div>
      ) : !hasAnyInvestmentAccounts ? (
        <EmptyState
          icon={<BriefcaseBusiness />}
          title="Нет инвестиционных счетов"
          description="Добавьте брокерский счёт, депозит или криптовалютный аккаунт, чтобы начать отслеживать капитал и доходность."
          action={
            isReadOnlyMode || !canCreateAccount
              ? undefined
              : {
                  label: 'Добавить счёт',
                  onClick: onCreateAccount,
                }
          }
        />
      ) : view === 'active' && activeCount === 0 ? (
        <EmptyState
          icon={<Inbox />}
          title="Нет активных инвестиционных счетов"
          description="Все инвестиционные счета находятся в архиве. Откройте архив и верните нужные счета в активную часть портфеля."
          action={{ label: 'Открыть архив', onClick: () => onViewChange('archived') }}
        />
      ) : view === 'archived' && archivedCount === 0 ? (
        <EmptyState
          icon={<Inbox />}
          title="Архив инвестиций пуст"
          description="Здесь появятся инвестиционные счета после архивации."
          action={{ label: 'К активным счетам', onClick: () => onViewChange('active') }}
        />
      ) : accounts.length === 0 && hasSearch ? (
        <EmptyState
          icon={<SearchX />}
          title="Ничего не найдено"
          description="По текущему запросу нет подходящих инвестиционных счетов."
          action={{ label: 'Сбросить поиск', onClick: () => onSearchChange('') }}
        />
      ) : (
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
          {accounts.map((account) => (
            <InvestmentAccountCard
              key={account.id}
              account={account}
              baseCurrencyCode={baseCurrencyCode}
              readonly={view === 'archived'}
              interactionLocked={isReadOnlyMode}
              isLiquidityLoading={isLiquidityLoading(account.id)}
              isArchiveLoading={isArchiveLoading(account.id)}
              onEdit={() => onEditAccount(account)}
              onAdjustBalance={() => onAdjustBalance(account)}
              onLiquidityChange={(nextValue) => onLiquidityChange(account, nextValue)}
              onArchive={() => onArchive(account)}
              onUnarchive={() => onUnarchive(account)}
            />
          ))}
        </div>
      )}
    </section>
  );
}

// vue-app/src/components/Investments/InvestmentsAccountsSection.vue
<script setup lang="ts">
import type { Account, AccountType } from '../../types';
import type { ViewState } from '../../types/view-state';
import InvestmentAccountCard from './InvestmentAccountCard.vue';
import UiButton from '@/ui/UiButton.vue';
import Message from 'primevue/message';
import Skeleton from 'primevue/skeleton';
import EmptyState from '@/components/common/EmptyState.vue';
import ListToolbar from '@/components/common/ListToolbar.vue';

type InvestmentsView = 'active' | 'archived';

interface InvestmentAccount {
  id: string;
  name: string;
  currencyCode: string;
  type: AccountType;
  isLiquid: boolean;
  isArchived: boolean;
  isMain: boolean;
  balance: number;
  balanceInBaseCurrency: number;
  lastAdjustedAt: string | null;
  returnPercent: number | null;
  currency?: Account['currency'];
}

defineProps<{
  activeAccounts: InvestmentAccount[];
  archivedAccounts: InvestmentAccount[];
  filteredAccounts: InvestmentAccount[];
  view: InvestmentsView;
  isReadOnlyMode: boolean;
  searchText: string;
  hasVisibleAccounts: boolean;
  hasAnyInvestmentAccounts: boolean;
  hasActiveFilters: boolean;
  shouldShowAccountsSkeleton: boolean;
  shouldShowAccountsErrorState: boolean;
  currentAccountsState: ViewState;
  currentAccountsError: string | null;
  pendingLiquidityId: string | null;
  pendingArchiveId: string | null;
  pendingUnarchiveId: string | null;
  baseCurrency: string;
}>();

const emit = defineEmits<{
  (e: 'update:view', value: InvestmentsView): void;
  (e: 'update:searchText', value: string): void;
  (e: 'openModal'): void;
  (e: 'clearFilters'): void;
  (e: 'retryCurrentView'): void;
  (e: 'openAdjustments', account: InvestmentAccount): void;
  (e: 'updateLiquidity', payload: { account: InvestmentAccount; value: boolean }): void;
  (e: 'archiveAccount', account: InvestmentAccount): void;
  (e: 'unarchiveAccount', account: InvestmentAccount): void;
  (e: 'renameAccount', account: InvestmentAccount): void;
}>();

const setView = (value: InvestmentsView) => {
  emit('update:view', value);
};
</script>

<template>
  <div class="investments-accounts">
    <div class="investments-accounts__header">
      <h2 class="investments-accounts__title">
        Счета
      </h2>
      <UiButton
        label="Добавить счет"
        icon="pi pi-plus"
        size="sm"
        :disabled="isReadOnlyMode"
        @click="emit('openModal')"
      />
    </div>

    <ListToolbar
      :model-value="view"
      :search-text="searchText"
      :active-count="activeAccounts.length"
      :archived-count="archivedAccounts.length"
      search-placeholder="Поиск"
      @update:model-value="emit('update:view', $event)"
      @update:search-text="emit('update:searchText', $event)"
    />

    <div
      v-if="currentAccountsState === 'error' && hasVisibleAccounts"
      class="investments-accounts__message investments-accounts__message--inline"
    >
      <Message
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        {{ currentAccountsError || 'Не удалось загрузить счета.' }}
      </Message>
      <UiButton
        label="Повторить"
        icon="pi pi-refresh"
        variant="secondary"
        @click="emit('retryCurrentView')"
      />
    </div>

    <div
      v-if="shouldShowAccountsSkeleton"
      class="investments-accounts__skeleton"
    >
      <Skeleton
        v-for="i in 4"
        :key="i"
        height="180px"
      />
    </div>

    <div
      v-else-if="shouldShowAccountsErrorState"
      class="investments-accounts__message"
    >
      <Message
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        {{ currentAccountsError || 'Не удалось загрузить счета.' }}
      </Message>
      <UiButton
        label="Повторить"
        icon="pi pi-refresh"
        variant="secondary"
        @click="emit('retryCurrentView')"
      />
    </div>

    <EmptyState
      v-else-if="!hasAnyInvestmentAccounts"
      icon="pi pi-briefcase"
      title="Нет инвестиционных счетов"
      description="Добавьте брокерский счет, вклад или криптовалютный аккаунт, чтобы следить за доходностью."
      :action-label="isReadOnlyMode ? '' : 'Добавить счет'"
      action-icon="pi pi-plus"
      @action="emit('openModal')"
    />

    <EmptyState
      v-else-if="view === 'active' && activeAccounts.length === 0"
      icon="pi pi-chart-line"
      title="Нет активных инвестиционных счетов"
      description="Все инвестиционные счета находятся в архиве. Разархивируйте нужные счета, чтобы вернуть их в метрики."
      action-label="Открыть архив"
      action-icon="pi pi-inbox"
      @action="setView('archived')"
    />

    <EmptyState
      v-else-if="view === 'archived' && archivedAccounts.length === 0"
      icon="pi pi-inbox"
      title="Архив инвестиций пуст"
      description="Здесь появятся инвестиционные счета после архивации."
      action-label="К активным счетам"
      action-icon="pi pi-arrow-left"
      @action="setView('active')"
    />

    <EmptyState
      v-else-if="filteredAccounts.length === 0 && hasActiveFilters"
      icon="pi pi-filter-slash"
      title="Ничего не найдено"
      description="По выбранным фильтрам нет счетов. Попробуйте изменить параметры."
      action-label="Сбросить фильтры"
      action-icon="pi pi-refresh"
      @action="emit('clearFilters')"
    />

    <div
      v-else
      class="investments-accounts__grid"
    >
      <InvestmentAccountCard
        v-for="account in filteredAccounts"
        :key="account.id"
        :account="account"
        :base-currency-code="baseCurrency"
        :readonly="view === 'archived'"
        :interaction-locked="isReadOnlyMode"
        :is-liquidity-loading="pendingLiquidityId === account.id"
        :is-archive-loading="pendingArchiveId === account.id || pendingUnarchiveId === account.id"
        @open="emit('openAdjustments', account)"
        @update-liquidity="emit('updateLiquidity', { account, value: $event })"
        @archive="emit('archiveAccount', account)"
        @unarchive="emit('unarchiveAccount', account)"
        @rename="emit('renameAccount', account)"
      />
    </div>
  </div>
</template>

<style scoped>
.investments-accounts {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);
}

.investments-accounts__header {
  display: flex;
  gap: var(--ft-space-4);
  align-items: center;
  justify-content: space-between;
}

.investments-accounts__title {
  margin: 0;
  font-size: var(--ft-text-xl);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.investments-accounts__skeleton {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: var(--ft-space-4);
}

.investments-accounts__grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: var(--ft-space-4);
}

.investments-accounts__message {
  display: grid;
  gap: var(--ft-space-3);
  justify-items: start;
}

.investments-accounts__message--inline {
  margin-bottom: var(--ft-space-2);
}

@media (width <= 640px) {
  .investments-accounts__header {
    flex-direction: column;
    align-items: stretch;
  }

  .investments-accounts__grid,
  .investments-accounts__skeleton {
    grid-template-columns: 1fr;
  }
}
</style>
