// react-app/src/components/analytics/CategoryDeltaCard.tsx
import { AlertCircle, ArrowDown, ArrowUp } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import type { CategoryDeltaItemDto } from '@/types';

import { InfoTooltip } from './InfoTooltip';
import { formatAnalyticsMetaMoney, formatAnalyticsPercent, ANALYTICS_CARD_BG } from './models';

interface CategoryDeltaCardProps {
  loading: boolean;
  error: string | null;
  periodLabel: string;
  increased: CategoryDeltaItemDto[];
  decreased: CategoryDeltaItemDto[];
  currency: string;
  onRetry: () => void;
}

const SKELETON_KEYS = ['alpha', 'beta', 'gamma', 'delta'] as const;

function DeltaSkeleton() {
  return (
    <div
      role="status"
      aria-busy="true"
      aria-label="Загрузка изменений по категориям"
      className="space-y-7 px-7 pb-7"
    >
      <div className="space-y-4">
        <Skeleton className="h-5 w-20" />
        {SKELETON_KEYS.slice(0, 2).map((key) => (
          <div key={key} className="space-y-3">
            <div className="flex items-center justify-between gap-4">
              <Skeleton className="h-7 w-40" />
              <Skeleton className="h-7 w-32" />
            </div>
            <Skeleton className="h-1.5 w-full rounded-full" />
          </div>
        ))}
      </div>

      <div className="space-y-4">
        <Skeleton className="h-5 w-28" />
        {SKELETON_KEYS.slice(2).map((key) => (
          <div key={key} className="space-y-3">
            <div className="flex items-center justify-between gap-4">
              <Skeleton className="h-7 w-40" />
              <Skeleton className="h-7 w-32" />
            </div>
            <Skeleton className="h-1.5 w-full rounded-full" />
          </div>
        ))}
      </div>
    </div>
  );
}

function getMaxDelta(items: CategoryDeltaItemDto[]): number {
  if (items.length === 0) {
    return 1;
  }

  return Math.max(...items.map((item) => Math.abs(item.deltaAmount)), 1);
}

function barWidth(item: CategoryDeltaItemDto, maxDelta: number): string {
  const ratio = maxDelta <= 0 ? 0 : Math.abs(item.deltaAmount) / maxDelta;
  return `${Math.max(10, Math.min(100, ratio * 100))}%`;
}

function formatDelta(item: CategoryDeltaItemDto, direction: 'up' | 'down', currency: string): string {
  const sign = direction === 'up' ? '+' : '−';
  return `${sign}${formatAnalyticsMetaMoney(Math.abs(item.deltaAmount), currency)}`;
}

function toneColor(direction: 'up' | 'down'): string {
  return direction === 'up' ? 'var(--ft-danger-400)' : 'var(--ft-success-400)';
}

function toneFill(direction: 'up' | 'down'): string {
  return direction === 'up'
    ? 'color-mix(in srgb, var(--ft-danger-500) 86%, var(--ft-danger-300))'
    : 'color-mix(in srgb, var(--ft-success-500) 86%, var(--ft-success-300))';
}

interface DeltaRowProps {
  item: CategoryDeltaItemDto;
  currency: string;
  direction: 'up' | 'down';
  maxDelta: number;
}

function DeltaRow({ item, currency, direction, maxDelta }: DeltaRowProps) {
  const percentLabel = formatAnalyticsPercent(
    item.deltaPercent === null ? null : Math.abs(item.deltaPercent),
  );

  return (
    <div className="space-y-2.5">
      <div className="grid grid-cols-[minmax(0,1fr)_minmax(8rem,8.75rem)] items-start gap-4">
        <div className="flex min-w-0 items-center gap-3">
          <span
            className="inline-block size-3 shrink-0 rounded-full"
            style={{ backgroundColor: item.color }}
            aria-hidden="true"
          />
          <span className="truncate text-base font-semibold text-foreground">
            {item.name}
          </span>
        </div>

        <div className="text-right" style={{ color: toneColor(direction) }}>
          <p className="text-base font-semibold tabular-nums">
            {formatDelta(item, direction, currency)}
          </p>
          {percentLabel !== '—' && (
            <p className="text-sm font-medium tabular-nums opacity-90">{percentLabel}</p>
          )}
        </div>
      </div>

      <div
        className="h-1.5 overflow-hidden rounded-full"
        style={{ backgroundColor: 'color-mix(in srgb, var(--ft-primary-500) 10%, transparent)' }}
      >
        <div
          className="h-full rounded-full"
          style={{
            width: barWidth(item, maxDelta),
            backgroundColor: toneFill(direction),
          }}
        />
      </div>
    </div>
  );
}

interface DeltaSectionProps {
  title: string;
  items: CategoryDeltaItemDto[];
  currency: string;
  direction: 'up' | 'down';
}

function DeltaSection({ title, items, currency, direction }: DeltaSectionProps) {
  if (items.length === 0) {
    return null;
  }

  const maxDelta = getMaxDelta(items);
  const Icon = direction === 'up' ? ArrowUp : ArrowDown;

  return (
    <section className="space-y-4">
      <div
        className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.08em]"
        style={{ color: direction === 'up' ? 'var(--ft-danger-300)' : 'var(--ft-success-300)' }}
      >
        <Icon className="size-4" aria-hidden="true" />
        <span>{title}</span>
      </div>

      <div className="space-y-4">
        {items.map((item) => (
          <DeltaRow
            key={item.id}
            item={item}
            currency={currency}
            direction={direction}
            maxDelta={maxDelta}
          />
        ))}
      </div>
    </section>
  );
}

export function CategoryDeltaCard({
  loading,
  error,
  periodLabel,
  increased,
  decreased,
  currency,
  onRetry,
}: CategoryDeltaCardProps) {
  const isEmpty = increased.length === 0 && decreased.length === 0;

  return (
    <Card
      className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background: ANALYTICS_CARD_BG,
      }}
      aria-label={`Изменения по категориям за ${periodLabel}`}
    >
      <div className="flex items-start gap-2 px-6 py-6">
        <h2 className="text-[1.75rem] font-semibold leading-tight text-foreground">
          Изменения по категориям
        </h2>
        <InfoTooltip
          content="Какие категории выросли или снизились по сравнению с предыдущим месяцем."
          className="-mt-1"
          ariaLabel="Подробнее об изменениях по категориям"
        />
      </div>

      {loading ? (
        <DeltaSkeleton />
      ) : error ? (
        <div
          className="flex min-h-[320px] flex-col items-center justify-center gap-4 px-7 pb-7 text-center"
          role="alert"
        >
          <AlertCircle className="size-8 text-destructive" aria-hidden="true" />
          <div className="space-y-1">
            <p className="text-base font-medium text-foreground">Не удалось загрузить сравнение</p>
            <p className="text-sm text-[var(--ft-text-secondary)]">{error}</p>
          </div>
          <Button variant="outline" className="min-h-[44px]" onClick={onRetry}>
            Повторить
          </Button>
        </div>
      ) : isEmpty ? (
        <div className="px-7 pb-7">
          <div className="flex min-h-[320px] items-center justify-center rounded-[24px] border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-surface-base)_75%,transparent)] px-8 text-center">
            <p className="max-w-md text-base leading-7 text-[var(--ft-text-secondary)]">
              Нет данных для сравнения. Нужен предыдущий период расходов, чтобы показать заметные изменения по категориям.
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-7 px-6 pb-6">
          <DeltaSection title="Рост" items={increased} currency={currency} direction="up" />
          <DeltaSection title="Снижение" items={decreased} currency={currency} direction="down" />
        </div>
      )}
    </Card>
  );
}

// vue-app/src/components/analytics/CategoryDeltaCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import Skeleton from 'primevue/skeleton';
import Message from 'primevue/message';
import UiButton from '../../ui/UiButton.vue';

interface CategoryDeltaItem {
  id: string;
  name: string;
  color: string;
  currentAmount: number;
  previousAmount: number;
  deltaAmount: number;
  deltaPercent: number | null;
}

const props = defineProps<{
  loading: boolean;
  error: string | null;
  increased: CategoryDeltaItem[];
  decreased: CategoryDeltaItem[];
  currency: string;
  periodLabel: string;
}>();

const emit = defineEmits<{
  (event: 'retry'): void;
}>();

const showEmpty = computed(
  () =>
    !props.loading &&
    !props.error &&
    props.increased.length === 0 &&
    props.decreased.length === 0
);

const getMaxDelta = (items: CategoryDeltaItem[]) => {
  if (!items.length) return 1;
  return Math.max(...items.map(item => Math.abs(item.deltaAmount)), 1);
};

const maxIncreaseDelta = computed(() => getMaxDelta(props.increased));
const maxDecreaseDelta = computed(() => getMaxDelta(props.decreased));

const clampBarPercent = (value: number) => Math.max(4, Math.min(value, 100));

const barWidth = (item: CategoryDeltaItem, direction: 'up' | 'down') => {
  if (item.deltaPercent != null && Number.isFinite(item.deltaPercent)) {
    return `${clampBarPercent(Math.abs(item.deltaPercent))}%`;
  }

  const maxDelta = direction === 'up' ? maxIncreaseDelta.value : maxDecreaseDelta.value;
  const amountPercent = (Math.abs(item.deltaAmount) / maxDelta) * 100;
  return `${clampBarPercent(amountPercent)}%`;
};

const formatMoney = (value: number) =>
  value.toLocaleString('ru-RU', {
    style: 'currency',
    currency: props.currency,
    minimumFractionDigits: 0,
  });

const formatDelta = (value: number) =>
  `${value > 0 ? '+' : '−'}${formatMoney(Math.abs(value))}`;

const formatPercent = (value: number | null) =>
  value == null ? '' : `${Math.abs(value).toFixed(0)}%`;
</script>

<template>
  <div class="delta-card">
    <div class="delta-card__head">
      <div class="delta-card__title-row">
        <h3 class="delta-card__title">
          Изменения по категориям
        </h3>
        <button
          v-tooltip="{ value: 'Какие категории расходов выросли или снизились по сравнению с прошлым месяцем. Помогает увидеть тренды.', event: 'click', autoHide: false }"
          type="button"
          class="delta-card__hint"
          aria-label="Подсказка"
        >
          <i class="pi pi-question-circle" />
        </button>
      </div>
    </div>

    <div
      v-if="loading"
      class="delta-card__loading"
    >
      <Skeleton
        v-for="i in 4"
        :key="i"
        height="36px"
        width="90%"
      />
    </div>

    <div
      v-else-if="error"
      class="delta-card__message"
    >
      <Message
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        <div class="delta-card__message-body">
          <p class="delta-card__message-title">
            Не удалось загрузить сравнение
          </p>
          <p class="delta-card__message-text">
            {{ error }}
          </p>
          <UiButton
            label="Повторить"
            icon="pi pi-refresh"
            size="sm"
            @click="emit('retry')"
          />
        </div>
      </Message>
    </div>

    <div
      v-else-if="showEmpty"
      class="delta-card__message"
    >
      <Message
        severity="info"
        icon="pi pi-inbox"
        :closable="false"
      >
        <div class="delta-card__message-body delta-card__message-body--compact">
          <p class="delta-card__message-title">
            Нет данных для сравнения
          </p>
          <p class="delta-card__message-text">
            Нужен предыдущий период расходов, чтобы увидеть изменения.
          </p>
        </div>
      </Message>
    </div>

    <div
      v-else
      class="delta-card__body"
    >
      <div
        v-if="increased.length"
        class="delta-card__section"
      >
        <p class="delta-card__section-title">
          <i class="pi pi-arrow-up" />
          Рост
        </p>
        <div class="delta-card__list">
          <div
            v-for="item in increased"
            :key="item.id"
            class="delta-item"
          >
            <div class="delta-item__info">
              <span
                class="delta-item__color"
                :style="{ backgroundColor: item.color }"
              />
              <span class="delta-item__name">{{ item.name }}</span>
              <span class="delta-item__delta delta-item__delta--up">
                {{ formatDelta(item.deltaAmount) }}
                <span
                  v-if="formatPercent(item.deltaPercent)"
                  class="delta-item__pct"
                >{{ formatPercent(item.deltaPercent) }}</span>
              </span>
            </div>
            <div class="delta-item__bar-track">
              <div
                class="delta-item__bar delta-item__bar--up"
                :style="{ width: barWidth(item, 'up') }"
              />
            </div>
          </div>
        </div>
      </div>

      <div
        v-if="decreased.length"
        class="delta-card__section"
      >
        <p class="delta-card__section-title">
          <i class="pi pi-arrow-down" />
          Снижение
        </p>
        <div class="delta-card__list">
          <div
            v-for="item in decreased"
            :key="item.id"
            class="delta-item"
          >
            <div class="delta-item__info">
              <span
                class="delta-item__color"
                :style="{ backgroundColor: item.color }"
              />
              <span class="delta-item__name">{{ item.name }}</span>
              <span class="delta-item__delta delta-item__delta--down">
                {{ formatDelta(item.deltaAmount) }}
                <span
                  v-if="formatPercent(item.deltaPercent)"
                  class="delta-item__pct"
                >{{ formatPercent(item.deltaPercent) }}</span>
              </span>
            </div>
            <div class="delta-item__bar-track">
              <div
                class="delta-item__bar delta-item__bar--down"
                :style="{ width: barWidth(item, 'down') }"
              />
            </div>
          </div>
        </div>
      </div>

      <p
        v-if="!increased.length && !decreased.length"
        class="delta-card__none"
      >
        Существенных изменений нет
      </p>
    </div>
  </div>
</template>

<style scoped>
.delta-card {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);

  padding: clamp(1rem, 2vw, 1.5rem);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-xl);
  box-shadow: var(--ft-shadow-sm);
}

.delta-card__head {
  display: grid;
  gap: var(--ft-space-1);
}

.delta-card__title-row {
  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;
}

.delta-card__title {
  margin: 0;
  font-size: var(--ft-text-lg);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.delta-card__hint {
  cursor: pointer;

  display: inline-flex;
  align-items: center;
  justify-content: center;

  /* Ensure minimum touch target size */
  min-width: var(--ft-control-height);
  min-height: var(--ft-control-height);
  padding: 0;

  font-size: 1rem;
  color: var(--ft-text-muted);

  background: none;
  border: none;

  transition: color var(--ft-transition-fast);
}

.delta-card__hint:hover {
  color: var(--ft-text-secondary);
}

.delta-card__hint:active {
  color: var(--ft-accent-primary);
}

.delta-card__loading {
  display: grid;
  gap: var(--ft-space-3);
}

.delta-card__message {
  display: grid;
}

.delta-card__message-body {
  display: grid;
  gap: var(--ft-space-3);
}

.delta-card__message-body--compact {
  gap: var(--ft-space-2);
}

.delta-card__message-title {
  margin: 0;
  font-weight: var(--ft-font-semibold);
}

.delta-card__message-text {
  margin: 0;
}

.delta-card__body {
  display: grid;
  gap: var(--ft-space-4);
}

.delta-card__section {
  display: grid;
  gap: var(--ft-space-2);
}

.delta-card__section-title {
  display: inline-flex;
  gap: var(--ft-space-1);
  align-items: center;

  margin: 0;

  font-size: var(--ft-text-xs);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.delta-card__section-title .pi-arrow-up {
  font-size: 0.7rem;
  color: var(--ft-danger-400);
}

.delta-card__section-title .pi-arrow-down {
  font-size: 0.7rem;
  color: var(--ft-success-400);
}

.delta-card__list {
  display: grid;
  gap: var(--ft-space-2);
}

.delta-item {
  display: grid;
  gap: var(--ft-space-1);
}

.delta-item__info {
  display: flex;
  gap: var(--ft-space-2);
  align-items: center;
}

.delta-item__color {
  flex-shrink: 0;
  width: 8px;
  height: 8px;
  border-radius: var(--ft-radius-full);
}

.delta-item__name {
  overflow: hidden;
  flex: 1;

  min-width: 0;

  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-primary);
  text-overflow: ellipsis;
  white-space: nowrap;
}

.delta-item__delta {
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-bold);
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
}

.delta-item__delta--up {
  color: var(--ft-danger-400);
}

.delta-item__delta--down {
  color: var(--ft-success-400);
}

.delta-item__pct {
  margin-left: 2px;
  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
  opacity: 0.7;
}

.delta-item__bar-track {
  overflow: hidden;
  height: 4px;
  background: color-mix(in srgb, var(--ft-surface-raised) 70%, transparent);
  border-radius: var(--ft-radius-full);
}

.delta-item__bar {
  height: 100%;
  border-radius: var(--ft-radius-full);
  transition: width var(--ft-transition-slow);
}

.delta-item__bar--up {
  background: var(--ft-danger-400);
}

.delta-item__bar--down {
  background: var(--ft-success-400);
}

.delta-card__none {
  margin: 0;
  padding: var(--ft-space-4);

  font-size: var(--ft-text-sm);
  color: var(--ft-text-tertiary);
  text-align: center;
}
</style>
