// react-app/src/components/analytics/ForecastCard.tsx
import {
  Area,
  CartesianGrid,
  ComposedChart,
  Line,
  ReferenceLine,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { AlertCircle, ArrowDown, ArrowUp, Info } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import type { ForecastDto } from '@/types';

import { InfoTooltip } from './InfoTooltip';
import {
  formatAnalyticsHeroMoney,
  formatAnalyticsMetaMoney,
  formatAnalyticsMoneyRange,
} from './models';

interface ForecastCardProps {
  loading: boolean;
  error: string | null;
  forecast: ForecastDto | null;
  currency: string;
  isCurrentMonth: boolean;
  readinessMet: boolean;
  readinessMessage: string;
  observedExpenseDays: number;
  requiredExpenseDays: number;
  onRetry: () => void;
}

interface ChartDataPoint {
  day: number;
  actual: number | null;
  corridorBase: number | null;
  corridorBand: number | null;
  optimistic: number | null;
  risk: number | null;
}

function hasActualData(forecast: ForecastDto): boolean {
  return forecast.series.actual.some((value) => value !== null);
}

function buildChartData(forecast: ForecastDto, showCorridor: boolean): ChartDataPoint[] {
  const { days, actual, optimistic, risk } = forecast.series;

  return days.map((day, index) => {
    const optimisticValue = showCorridor ? (optimistic[index] ?? null) : null;
    const riskValue = showCorridor ? (risk[index] ?? null) : null;

    return {
      day,
      actual: actual[index] ?? null,
      corridorBase: optimisticValue,
      corridorBand:
        optimisticValue !== null && riskValue !== null
          ? Math.max(0, riskValue - optimisticValue)
          : null,
      optimistic: optimisticValue,
      risk: riskValue,
    };
  });
}

function buildXAxisTicks(days: number[]): number[] {
  if (days.length <= 1) {
    return days;
  }

  const ticks = days.filter((day) => (day - 1) % 3 === 0);
  const last = days[days.length - 1];

  if (ticks[ticks.length - 1] !== last) {
    ticks.push(last);
  }

  return ticks;
}

function formatYAxisTick(value: number, currency: string): string {
  return formatAnalyticsMetaMoney(value, currency);
}

function getChartMax(forecast: ForecastDto, showCorridor: boolean): number | undefined {
  const values = [
    ...forecast.series.actual.filter((value): value is number => value !== null),
  ];

  if (showCorridor) {
    values.push(
      ...forecast.series.optimistic.filter((value): value is number => value !== null),
      ...forecast.series.risk.filter((value): value is number => value !== null),
    );
  }

  if (forecast.series.baseline !== null) {
    values.push(forecast.series.baseline);
  }

  if (values.length === 0) {
    return undefined;
  }

  const maxValue = Math.max(...values);
  if (maxValue <= 0) {
    return undefined;
  }

  const padded = maxValue * 1.12;
  if (padded <= 50_000) return Math.ceil(padded / 5_000) * 5_000;
  if (padded <= 150_000) return Math.ceil(padded / 10_000) * 10_000;
  return Math.ceil(padded / 25_000) * 25_000;
}

function buildBaselineNote(
  forecast: ForecastDto,
  currency: string,
  showForecastCorridor: boolean,
) {
  const { optimisticTotal, riskTotal, baselineLimit, currentSpent } = forecast.summary;
  const comparisonTarget =
    showForecastCorridor && optimisticTotal !== null && riskTotal !== null
      ? (optimisticTotal + riskTotal) / 2
      : currentSpent;

  if (baselineLimit === null || comparisonTarget === null || baselineLimit <= 0) {
    return null;
  }

  const diff = comparisonTarget - baselineLimit;

  return {
    tone: diff <= 0 ? 'below' : 'above',
    text:
      diff <= 0
        ? `Ниже базового уровня на ${formatAnalyticsMetaMoney(Math.abs(diff), currency)}`
        : `Выше базового уровня на ${formatAnalyticsMetaMoney(Math.abs(diff), currency)}`,
  } as const;
}

function ForecastTooltip({
  active,
  label,
  payload,
  currency,
  showCorridor,
}: {
  active?: boolean;
  label?: number | string;
  payload?: Array<{ payload: ChartDataPoint }>;
  currency: string;
  showCorridor: boolean;
}) {
  const point = payload?.find((entry) => entry?.payload)?.payload;

  if (!active || !point) {
    return null;
  }

  return (
    <div className="rounded-2xl border border-border bg-popover px-4 py-3 text-sm text-popover-foreground shadow-md">
      <p className="mb-2 text-[var(--ft-text-secondary)]">День {label}</p>

      {point.actual !== null && (
        <p className="tabular-nums">
          Факт: <span className="font-semibold">{formatAnalyticsMetaMoney(point.actual, currency)}</span>
        </p>
      )}

      {showCorridor &&
        point.optimistic !== null &&
        point.risk !== null &&
        point.risk !== point.optimistic && (
          <>
            <p className="tabular-nums">
              Нижняя граница:{' '}
              <span className="font-semibold">{formatAnalyticsMetaMoney(point.optimistic, currency)}</span>
            </p>
            <p className="tabular-nums">
              Верхняя граница:{' '}
              <span className="font-semibold">{formatAnalyticsMetaMoney(point.risk, currency)}</span>
            </p>
          </>
        )}
    </div>
  );
}

function ChartLegend({
  hasBaseline,
  showCorridor,
}: {
  hasBaseline: boolean;
  showCorridor: boolean;
}) {
  if (!hasBaseline && !showCorridor) {
    return null;
  }

  return (
    <div className="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-[var(--ft-text-secondary)]">
      <span className="flex items-center gap-2">
        <span
          className="inline-block h-0.5 w-7 rounded"
          style={{ backgroundColor: 'var(--ft-warning-300)' }}
        />
        Факт
      </span>

      {showCorridor && (
        <span className="flex items-center gap-2">
          <span
            className="inline-block h-3 w-7 rounded-md border"
            style={{
              borderColor: 'var(--ft-success-400)',
              backgroundColor: 'color-mix(in srgb, var(--ft-success-500) 14%, transparent)',
            }}
          />
          Коридор прогноза
        </span>
      )}

      {hasBaseline && (
        <span className="flex items-center gap-2">
          <span
            className="inline-block h-0.5 w-7 rounded border-t-2"
            style={{
              borderStyle: 'dashed',
              borderColor: 'var(--ft-primary-200)',
              background: 'none',
            }}
          />
          Базовый уровень
        </span>
      )}
    </div>
  );
}

export function ForecastCard({
  loading,
  error,
  forecast,
  currency,
  isCurrentMonth,
  readinessMet,
  readinessMessage,
  observedExpenseDays,
  requiredExpenseDays,
  onRetry,
}: ForecastCardProps) {
  const title = isCurrentMonth ? 'Прогноз расходов' : 'Расходы за месяц';
  const tooltipText = isCurrentMonth
    ? 'Прогноз до конца месяца на основе текущего темпа трат и исторического окна расходов.'
    : 'Фактические расходы за выбранный месяц и сравнение с базовым уровнем.';

  if (!readinessMet) {
    return (
      <Card
        className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
        style={{
          background:
            'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
        }}
      >
        <div className="flex items-start gap-2 px-6 py-6">
          <h2 className="text-[1.75rem] font-semibold leading-tight text-foreground">{title}</h2>
          <InfoTooltip content={tooltipText} className="-mt-1" ariaLabel="Подробнее о прогнозе расходов" />
        </div>

        <div className="px-6 pb-6">
          <div className="flex min-h-[280px] gap-3 rounded-[24px] border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-surface-base)_75%,transparent)] p-5 text-base leading-7 text-[var(--ft-text-secondary)]">
            <Info className="mt-1 size-5 shrink-0" aria-hidden="true" />
            <p>
              {readinessMessage}. Нужны расходы минимум в {requiredExpenseDays} днях. Сейчас есть данные за{' '}
              {observedExpenseDays}.
            </p>
          </div>
        </div>
      </Card>
    );
  }

  if (loading) {
    return (
      <Card
        className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
        style={{
          background:
            'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
        }}
      >
        <div className="space-y-5 px-6 py-6">
          <div className="flex items-start gap-2">
            <Skeleton className="h-9 w-56" />
            <Skeleton className="mt-1 size-10 rounded-full" />
          </div>
          <Skeleton className="h-4 w-40" />
          <Skeleton className="h-14 w-[22rem]" />
          <Skeleton className="h-[408px] rounded-[24px]" />
        </div>
      </Card>
    );
  }

  if (error) {
    return (
      <Card
        className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
        style={{
          background:
            'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
        }}
      >
        <div className="flex items-start gap-2 px-6 py-6">
          <h2 className="text-[1.75rem] font-semibold leading-tight text-foreground">{title}</h2>
          <InfoTooltip content={tooltipText} className="-mt-1" ariaLabel="Подробнее о прогнозе расходов" />
        </div>

        <div className="flex min-h-[280px] flex-col items-center justify-center gap-4 px-6 pb-6 text-center">
          <AlertCircle className="size-8 text-destructive" aria-hidden="true" />
          <div className="space-y-1">
            <p className="text-base font-medium text-foreground">Не удалось построить график</p>
            <p className="text-sm text-[var(--ft-text-secondary)]">{error}</p>
          </div>
          <Button variant="outline" className="min-h-[44px]" onClick={onRetry}>
            Повторить
          </Button>
        </div>
      </Card>
    );
  }

  if (!forecast || !hasActualData(forecast)) {
    return (
      <Card
        className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
        style={{
          background:
            'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
        }}
      >
        <div className="flex items-start gap-2 px-6 py-6">
          <h2 className="text-[1.75rem] font-semibold leading-tight text-foreground">{title}</h2>
          <InfoTooltip content={tooltipText} className="-mt-1" ariaLabel="Подробнее о прогнозе расходов" />
        </div>

        <div className="px-6 pb-6">
          <div className="flex min-h-[280px] items-center justify-center rounded-[24px] border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-surface-base)_75%,transparent)] px-8 text-center">
            <p className="max-w-md text-base leading-7 text-[var(--ft-text-secondary)]">
              {isCurrentMonth
                ? 'Недостаточно данных для прогноза. Продолжайте добавлять транзакции в течение месяца.'
                : 'Недостаточно данных, чтобы показать итог и сравнение с базовым уровнем.'}
            </p>
          </div>
        </div>
      </Card>
    );
  }

  const showForecastCorridor =
    isCurrentMonth &&
    forecast.summary.optimisticTotal !== null &&
    forecast.summary.riskTotal !== null;
  const data = buildChartData(forecast, showForecastCorridor);
  const baseline = forecast.series.baseline;
  const xTicks = buildXAxisTicks(forecast.series.days);
  const yMax = getChartMax(forecast, showForecastCorridor);
  const heroLabel = showForecastCorridor ? 'До конца месяца' : 'Итог за месяц';
  const heroValue = showForecastCorridor
    ? formatAnalyticsMoneyRange(
        forecast.summary.optimisticTotal,
        forecast.summary.riskTotal,
        currency,
      )
    : formatAnalyticsHeroMoney(forecast.summary.currentSpent, currency);
  const baselineNote = buildBaselineNote(forecast, currency, showForecastCorridor);
  const baselineLabel =
    forecast.summary.baselineLimit !== null
      ? `Базовый уровень · ${formatAnalyticsMetaMoney(forecast.summary.baselineLimit, currency)}`
      : baseline !== null
        ? `Базовый уровень · ${formatAnalyticsMetaMoney(baseline, currency)}`
        : null;

  return (
    <Card
      className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
      }}
    >
      <div className="space-y-5 px-6 py-6">
        <div className="flex items-start gap-2">
          <h2 className="text-[1.75rem] font-semibold leading-tight text-foreground">{title}</h2>
          <InfoTooltip content={tooltipText} className="-mt-1" ariaLabel="Подробнее о прогнозе расходов" />
        </div>

        <div className="space-y-3">
          <p className="text-base text-[var(--ft-text-secondary)]">{heroLabel}</p>
          <p
            className="text-[clamp(2.45rem,5vw,3.5rem)] font-bold leading-none text-[var(--ft-warning-300)]"
            style={{ fontVariantNumeric: 'tabular-nums' }}
          >
            {heroValue}
          </p>

          {(baselineNote || baselineLabel) && (
            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm">
              {baselineNote && (
                <div
                  className="flex items-center gap-2 font-medium"
                  style={{
                    color:
                      baselineNote.tone === 'below'
                        ? 'var(--ft-success-400)'
                        : 'var(--ft-warning-400)',
                  }}
                >
                  {baselineNote.tone === 'below' ? (
                    <ArrowDown className="size-4" aria-hidden="true" />
                  ) : (
                    <ArrowUp className="size-4" aria-hidden="true" />
                  )}
                  <span>{baselineNote.text}</span>
                </div>
              )}

              {baselineLabel && (
                <span className="text-[var(--ft-text-tertiary)]">{baselineLabel}</span>
              )}
            </div>
          )}
        </div>

        <div role="img" aria-label="График расходов по дням месяца">
          <ResponsiveContainer width="100%" height={showForecastCorridor ? 500 : 476}>
            <ComposedChart data={data} margin={{ top: 24, right: 14, left: 4, bottom: 12 }}>
              <defs>
                <linearGradient id="ft-forecast-actual-fill" x1="0" y1="0" x2="0" y2="1">
                  <stop
                    offset="0%"
                    stopColor="color-mix(in srgb, var(--ft-warning-300) 24%, transparent)"
                  />
                  <stop
                    offset="100%"
                    stopColor="color-mix(in srgb, var(--ft-warning-300) 5%, transparent)"
                  />
                </linearGradient>
              </defs>

              <CartesianGrid
                vertical={false}
                stroke="color-mix(in srgb, var(--ft-border-subtle) 92%, transparent)"
              />
              <XAxis
                dataKey="day"
                ticks={xTicks}
                tick={{ fontSize: 13, fill: 'var(--ft-text-secondary)' }}
                tickLine={false}
                axisLine={false}
                interval={0}
              />
              <YAxis
                domain={yMax != null ? [0, yMax] : [0, 'auto']}
                tickFormatter={(value: number) => formatYAxisTick(value, currency)}
                tick={{ fontSize: 13, fill: 'var(--ft-text-secondary)' }}
                tickLine={false}
                axisLine={false}
                width={88}
              />
              <Tooltip
                content={(props) => {
                  const { active, label, payload } = props as unknown as {
                    active?: boolean;
                    label?: number | string;
                    payload?: Array<{ payload: ChartDataPoint }>;
                  };

                  return (
                    <ForecastTooltip
                      active={active}
                      label={label}
                      payload={payload}
                      currency={currency}
                      showCorridor={showForecastCorridor}
                    />
                  );
                }}
              />

              <Area
                type="monotone"
                dataKey="actual"
                stroke="none"
                fill="url(#ft-forecast-actual-fill)"
                isAnimationActive={false}
              />

              {showForecastCorridor && (
                <>
                  <Area
                    type="monotone"
                    dataKey="corridorBase"
                    stackId="forecast"
                    stroke="none"
                    fill="transparent"
                    isAnimationActive={false}
                  />
                  <Area
                    type="monotone"
                    dataKey="corridorBand"
                    stackId="forecast"
                    stroke="none"
                    fill="color-mix(in srgb, var(--ft-success-500) 18%, transparent)"
                    isAnimationActive={false}
                  />
                </>
              )}

              <Line
                type="monotone"
                dataKey="actual"
                stroke="var(--ft-warning-300)"
                strokeWidth={3}
                connectNulls={false}
                dot={{
                  r: 4,
                  fill: 'var(--ft-warning-300)',
                  stroke: 'var(--ft-surface-base)',
                  strokeWidth: 2,
                }}
                activeDot={{
                  r: 5.5,
                  fill: 'var(--ft-warning-300)',
                  stroke: 'var(--ft-surface-base)',
                  strokeWidth: 2,
                }}
                isAnimationActive={false}
              />

              {baseline !== null && (
                <ReferenceLine
                  y={baseline}
                  stroke="var(--ft-primary-200)"
                  strokeDasharray="6 5"
                />
              )}
            </ComposedChart>
          </ResponsiveContainer>
        </div>

        <ChartLegend hasBaseline={baseline !== null} showCorridor={showForecastCorridor} />
      </div>
    </Card>
  );
}

// vue-app/src/components/analytics/ForecastCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ChartData, TooltipItem } from 'chart.js';
import UiBadge from '@/ui/UiBadge.vue';
import UiSkeleton from '@/ui/UiSkeleton.vue';
import UiMessage from '@/ui/UiMessage.vue';
import UiButton from '../../ui/UiButton.vue';
import UiChart from '@/ui/UiChart.vue';
import type { ForecastSummary } from '@/types/analytics.ts';
import { useChartColors } from '../../composables/useChartColors';

const props = withDefaults(defineProps<{
  loading: boolean;
  error: string | null;
  forecast: ForecastSummary | null;
  chartData: ChartData<'line', Array<number | null>, string> | null;
  currency: string;
  readinessMet?: boolean;
  readinessMessage?: string;
  observedExpenseDays?: number;
  requiredExpenseDays?: number;
}>(), {
  readinessMet: true,
  readinessMessage: 'Недостаточно данных, продолжайте добавлять транзакции',
  observedExpenseDays: 0,
  requiredExpenseDays: 7,
});

const emit = defineEmits<{
  (event: 'retry'): void;
}>();

const { colors, tooltipConfig } = useChartColors();

const showEmpty = computed(
  () =>
    props.readinessMet &&
    !props.loading &&
    !props.error &&
    (!props.forecast ||
      props.forecast.forecastTotal == null ||
      props.forecast.currentSpent == null ||
      !props.chartData)
);

const fmt = (value: number | null | undefined) => {
  if (value == null) return '—';
  return value.toLocaleString('ru-RU', {
    style: 'currency',
    currency: props.currency,
    minimumFractionDigits: 0,
  });
};

const formattedForecast = computed(() => fmt(props.forecast?.forecastTotal));
const formattedOptimistic = computed(() => fmt(props.forecast?.optimisticTotal));
const formattedRisk = computed(() => fmt(props.forecast?.riskTotal));
const formattedCurrent = computed(() => fmt(props.forecast?.currentSpent));
const formattedLimit = computed(() => fmt(props.forecast?.baselineLimit));
const hasBaseline = computed(() => props.forecast?.baselineLimit != null);

const statusLabel = computed(() => {
  switch (props.forecast?.status) {
    case 'good': return 'Ниже лимита';
    case 'average': return 'Близко к лимиту';
    case 'poor': return 'Превышает лимит';
    default: return null;
  }
});

const statusClass = computed(() => {
  switch (props.forecast?.status) {
    case 'good': return 'forecast-chip--good';
    case 'average': return 'forecast-chip--average';
    case 'poor': return 'forecast-chip--poor';
    default: return null;
  }
});

const chartOptions = computed(() => ({
  maintainAspectRatio: false,
  scales: {
    x: {
      grid: { color: colors.grid },
      ticks: { color: colors.text, font: { size: 12 } },
    },
    y: {
      grid: { color: colors.grid, drawBorder: false },
      ticks: {
        color: colors.text,
        font: { size: 12 },
        callback(value: number | string) {
          const numeric = typeof value === 'string' ? Number(value) : value;
          return numeric.toLocaleString('ru-RU', {
            style: 'currency',
            currency: props.currency,
            maximumFractionDigits: 0,
          });
        },
      },
    },
  },
  plugins: {
    legend: { display: false },
    tooltip: {
      ...tooltipConfig(),
      callbacks: {
        label(context: TooltipItem<'line'>) {
          const label = context.dataset.label ?? '';
          const value = context.parsed.y ?? 0;
          const formatted = value.toLocaleString('ru-RU', {
            style: 'currency',
            currency: props.currency,
            minimumFractionDigits: 0,
          });
          return `${label}: ${formatted}`;
        },
      },
    },
  },
}));
</script>

<template>
  <div class="forecast-card">
    <div class="forecast-card__head">
      <div>
        <div class="forecast-card__title-row">
          <h3 class="forecast-card__title">
            Прогноз расходов
          </h3>
          <i
            v-tooltip.top="'Оценка расходов до конца месяца на основе текущего темпа трат. Три сценария: оптимистичный, базовый и рисковый.'"
            class="pi pi-question-circle forecast-card__hint"
          />
        </div>
        <p class="forecast-card__subtitle">
          Оценка расходов до конца месяца
        </p>
      </div>
      <UiBadge
        v-if="readinessMet && statusLabel"
        :class="['forecast-chip', statusClass]"
      >
        {{ statusLabel }}
      </UiBadge>
    </div>

    <div
      v-if="loading"
      class="forecast-card__loading"
    >
      <div class="forecast-card__loading-chips">
        <UiSkeleton
          v-for="i in 3"
          :key="i"
          width="120px"
          height="32px"
          border-radius="999px"
        />
      </div>
      <UiSkeleton
        width="100%"
        height="300px"
        border-radius="16px"
      />
    </div>

    <div
      v-else-if="error"
      class="forecast-card__message"
    >
      <UiMessage
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        <div class="forecast-card__message-body">
          <p class="forecast-card__message-title">
            Не удалось построить прогноз
          </p>
          <p class="forecast-card__message-text">
            {{ error }}
          </p>
          <UiButton
            label="Повторить"
            icon="pi pi-refresh"
            size="sm"
            @click="emit('retry')"
          />
        </div>
      </UiMessage>
    </div>

    <div
      v-else-if="!readinessMet"
      class="forecast-card__message"
    >
      <UiMessage
        severity="info"
        icon="pi pi-info-circle"
        :closable="false"
      >
        <div class="forecast-card__message-body forecast-card__message-body--compact">
          <p class="forecast-card__message-title">
            {{ readinessMessage }}
          </p>
          <p class="forecast-card__message-text">
            Нужны расходы минимум в {{ requiredExpenseDays }} днях. Сейчас: {{ observedExpenseDays }}.
          </p>
        </div>
      </UiMessage>
    </div>

    <div
      v-else-if="showEmpty"
      class="forecast-card__message"
    >
      <UiMessage
        severity="info"
        icon="pi pi-inbox"
        :closable="false"
      >
        <div class="forecast-card__message-body forecast-card__message-body--compact">
          <p class="forecast-card__message-title">
            Недостаточно данных для прогноза
          </p>
          <p class="forecast-card__message-text">
            Нужны ежедневные расходы за текущий месяц.
          </p>
        </div>
      </UiMessage>
    </div>

    <template v-else>
      <div class="forecast-card__chips">
        <div class="forecast-chip forecast-chip--accent">
          <span class="forecast-chip__label">Потрачено</span>
          <span class="forecast-chip__value">{{ formattedCurrent }}</span>
        </div>
        <div class="forecast-chip forecast-chip--primary">
          <span class="forecast-chip__label">Прогноз</span>
          <span class="forecast-chip__value">{{ formattedForecast }}</span>
        </div>
        <div class="forecast-chip forecast-chip--muted">
          <span class="forecast-chip__label">Оптимист.</span>
          <span class="forecast-chip__value">{{ formattedOptimistic }}</span>
        </div>
        <div class="forecast-chip forecast-chip--warning">
          <span class="forecast-chip__label">Риск</span>
          <span class="forecast-chip__value">{{ formattedRisk }}</span>
        </div>
        <div
          v-if="hasBaseline"
          class="forecast-chip forecast-chip--outline"
        >
          <span class="forecast-chip__label">Базовые расходы</span>
          <span class="forecast-chip__value">{{ formattedLimit }}</span>
        </div>
      </div>

      <div
        class="forecast-card__chart"
        role="img"
        aria-label="График прогноза расходов"
      >
        <div class="forecast-card__chart-container">
          <UiChart
            v-if="chartData"
            type="line"
            :data="chartData"
            :options="chartOptions"
          />
        </div>
      </div>

      <div class="forecast-card__legend">
        <span class="forecast-legend__item">
          <span class="forecast-legend__line forecast-legend__line--actual" />
          Факт
        </span>
        <span class="forecast-legend__item">
          <span class="forecast-legend__line forecast-legend__line--forecast" />
          Прогноз
        </span>
        <span class="forecast-legend__item">
          <span class="forecast-legend__line forecast-legend__line--optimistic" />
          Оптимистичный
        </span>
        <span class="forecast-legend__item">
          <span class="forecast-legend__line forecast-legend__line--risk" />
          Риск
        </span>
        <span
          v-if="hasBaseline"
          class="forecast-legend__item"
        >
          <span class="forecast-legend__line forecast-legend__line--baseline" />
          Базовые расходы
        </span>
      </div>
    </template>
  </div>
</template>

<style scoped>
.forecast-card {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);

  padding: clamp(1rem, 2vw, 1.5rem);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-2xl);
  box-shadow: var(--ft-shadow-sm);
}

.forecast-card__head {
  display: flex;
  gap: var(--ft-space-4);
  align-items: flex-start;
  justify-content: space-between;
}

.forecast-card__title-row {
  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;
}

.forecast-card__title {
  margin: 0;
  font-size: var(--ft-text-lg);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.forecast-card__hint {
  cursor: pointer;

  display: inline-flex;
  align-items: center;
  justify-content: center;

  /* Ensure minimum touch target size */
  min-width: var(--ft-control-height);
  min-height: var(--ft-control-height);

  font-size: 1rem;
  color: var(--ft-text-muted);

  transition: color var(--ft-transition-fast);
}

.forecast-card__hint:hover {
  color: var(--ft-text-secondary);
}

.forecast-card__hint:active {
  color: var(--ft-accent-primary);
}

.forecast-card__subtitle {
  margin: var(--ft-space-1) 0 0;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.forecast-card__loading {
  display: grid;
  gap: var(--ft-space-3);
}

.forecast-card__loading-chips {
  display: flex;
  gap: var(--ft-space-2);
}

.forecast-card__message {
  display: grid;
}

.forecast-card__message-body {
  display: grid;
  gap: var(--ft-space-3);
}

.forecast-card__message-body--compact {
  gap: var(--ft-space-2);
}

.forecast-card__message-title {
  margin: 0;
  font-weight: var(--ft-font-semibold);
}

.forecast-card__message-text {
  margin: 0;
}

/* Chips */
.forecast-card__chips {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-2);
}

.forecast-chip {
  display: inline-flex;
  flex-direction: column;
  gap: 2px;

  padding: var(--ft-space-3) var(--ft-space-4);

  font-size: var(--ft-text-sm);

  background: color-mix(in srgb, var(--ft-surface-raised) 60%, transparent);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-lg);
}

.forecast-chip__label {
  font-size: var(--ft-text-lg);
  color: var(--ft-text-secondary);
}

.forecast-chip__value {
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-bold);
  font-variant-numeric: tabular-nums;
  color: var(--ft-text-primary);
}

.forecast-chip--accent {
  border-color: color-mix(in srgb, var(--ft-info-400) 30%, var(--ft-border-subtle));
}

.forecast-chip--accent .forecast-chip__value {
  color: var(--ft-info-400);
}

.forecast-chip--primary {
  border-color: color-mix(in srgb, var(--ft-primary-400) 30%, var(--ft-border-subtle));
}

.forecast-chip--primary .forecast-chip__value {
  color: var(--ft-primary-400);
}

.forecast-chip--warning {
  border-color: color-mix(in srgb, var(--ft-warning-400) 30%, var(--ft-border-subtle));
}

.forecast-chip--warning .forecast-chip__value {
  color: var(--ft-warning-400);
}

.forecast-chip--outline {
  background: transparent;
  border-style: dashed;
}

.forecast-chip--good {
  flex-direction: row;

  padding: 0.35rem 0.85rem;

  font-weight: var(--ft-font-semibold);
  color: var(--ft-success-700) !important;

  background: color-mix(in srgb, var(--ft-success-200) 55%, transparent) !important;
  border: none;
  border-radius: var(--ft-radius-full);
}

.forecast-chip--average {
  flex-direction: row;

  padding: 0.35rem 0.85rem;

  font-weight: var(--ft-font-semibold);
  color: var(--ft-warning-700) !important;

  background: color-mix(in srgb, var(--ft-warning-200) 55%, transparent) !important;
  border: none;
  border-radius: var(--ft-radius-full);
}

.forecast-chip--poor {
  flex-direction: row;

  padding: 0.35rem 0.85rem;

  font-weight: var(--ft-font-semibold);
  color: var(--ft-danger-700) !important;

  background: color-mix(in srgb, var(--ft-danger-200) 55%, transparent) !important;
  border: none;
  border-radius: var(--ft-radius-full);
}

/* Chart */
.forecast-card__chart {
  aspect-ratio: 16 / 9;
  width: 100%;
  max-height: 400px;
}

.forecast-card__chart-container {
  position: relative;
  width: 100%;
  height: 100%;
}

.forecast-card__chart-container :deep(.p-chart) {
  width: 100%;
  height: 100%;
}

.forecast-card__chart-container :deep(canvas) {
  height: 100%;
  max-height: 100%;
}

/* Integrated legend */
.forecast-card__legend {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-3);
  padding-top: var(--ft-space-1);
}

.forecast-legend__item {
  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;

  font-size: var(--ft-text-lg);
  color: var(--ft-text-secondary);
}

.forecast-legend__line {
  display: inline-block;
  width: 20px;
  height: 2px;
  border-radius: 999px;
}

.forecast-legend__line--actual {
  background: var(--ft-info-400);
}

.forecast-legend__line--forecast {
  height: 0;
  background: var(--ft-primary-400);
  border-top: 2px dashed var(--ft-primary-400);
}

.forecast-legend__line--optimistic {
  height: 0;
  background: var(--ft-info-400);
  border-top: 2px dashed var(--ft-info-400);
}

.forecast-legend__line--risk {
  height: 0;
  background: var(--ft-chart-risk);
  border-top: 2px dashed var(--ft-chart-risk);
}

.forecast-legend__line--baseline {
  height: 0;
  background: var(--ft-border-subtle);
  border-top: 2px dashed var(--ft-border-subtle);
}

@media (width <= 640px) {
  .forecast-card__head {
    flex-direction: column;
    align-items: flex-start;
  }

  .forecast-card__chips {
    gap: var(--ft-space-1);
  }

  .forecast-chip {
    padding: var(--ft-space-1) var(--ft-space-2);
  }

  .forecast-chip__label {
    font-size: var(--ft-text-sm);
  }

  .forecast-chip__value {
    font-size: var(--ft-text-xs);
  }

  .forecast-card__chart {
    aspect-ratio: 4 / 3;
    max-height: 280px;
  }

  .forecast-legend__item {
    font-size: var(--ft-text-sm);
  }
}
</style>
