// react-app/src/components/analytics/GlobalMonthScoreCard.tsx
import type { ReactNode } from 'react';
import { AlertCircle, Info } from 'lucide-react';

import { cn } from '@/utils/cn';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

import type { GlobalScoreModel } from './models';

interface GlobalMonthScoreCardProps {
  loading: boolean;
  error: string | null;
  model: GlobalScoreModel;
  children?: ReactNode;
  onRetry: () => void;
}

function scoreColor(accent: GlobalScoreModel['accent']): string {
  switch (accent) {
    case 'excellent':
      return 'var(--ft-success-400)';
    case 'good':
      return 'var(--ft-primary-400)';
    case 'average':
      return 'var(--ft-warning-300)';
    case 'poor':
      return 'var(--ft-warning-400)';
    case 'critical':
      return 'var(--ft-danger-400)';
    default:
      return 'var(--ft-text-primary)';
  }
}

function deltaColor(tone: GlobalScoreModel['deltaTone']): string {
  switch (tone) {
    case 'better':
      return 'var(--ft-success-400)';
    case 'worse':
      return 'var(--ft-danger-400)';
    default:
      return 'var(--ft-text-secondary)';
  }
}

const CHILD_SKELETON_KEYS = ['sk-a', 'sk-b', 'sk-c', 'sk-d'] as const;

function ScoreLoadingSkeleton() {
  return (
    <div
      className="overflow-hidden rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
      }}
      role="status"
      aria-busy="true"
      aria-label="Загрузка данных"
    >
      <div className="grid grid-cols-1 gap-4 px-7 py-7 lg:grid-cols-[minmax(260px,0.9fr)_minmax(0,1.6fr)]">
        <div className="flex flex-col justify-between gap-6">
          <div className="space-y-3">
            <Skeleton className="h-4 w-40" />
            <Skeleton className="h-16 w-44" />
            <Skeleton className="h-8 w-full" />
            <Skeleton className="h-8 w-3/4" />
          </div>
          <Skeleton className="h-6 w-44" />
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {CHILD_SKELETON_KEYS.map((key) => (
            <Skeleton key={key} className="h-[210px] rounded-[24px]" />
          ))}
        </div>
      </div>
    </div>
  );
}

function EmptyState() {
  return (
    <div
      className="flex flex-col items-center gap-3 rounded-[28px] border border-border bg-card p-6 text-center"
      role="status"
    >
      <Info className="size-8 text-muted-foreground" aria-hidden="true" />
      <p className="text-sm text-muted-foreground">
        Добавьте несколько транзакций, чтобы увидеть метрики
      </p>
    </div>
  );
}

function ScoreMainBlock({ model }: { model: GlobalScoreModel }) {
  return (
    <div className="flex min-w-0 flex-col justify-between gap-5">
      <div className="space-y-4">
        <p className="text-xs font-semibold uppercase tracking-[0.08em] text-[var(--ft-text-secondary)]">
          Общий рейтинг месяца
        </p>

        <p
          className="text-[clamp(3rem,6vw,4.2rem)] font-bold leading-none"
          style={{
            color: scoreColor(model.accent),
            fontVariantNumeric: 'tabular-nums',
          }}
        >
          {model.scoreLabel}
        </p>

        <p className="max-w-[24rem] text-base leading-7 text-[var(--ft-text-secondary)]">
          {model.description}
        </p>
      </div>

      <p
        className="text-sm font-semibold"
        style={{ color: deltaColor(model.deltaTone) }}
      >
        {model.deltaLabel ?? 'Нет данных для сравнения с предыдущим месяцем'}
      </p>
    </div>
  );
}

export function GlobalMonthScoreCard({
  loading,
  error,
  model,
  children,
  onRetry,
}: GlobalMonthScoreCardProps) {
  if (loading) {
    return <ScoreLoadingSkeleton />;
  }

  if (error) {
    return (
      <div
        className="flex min-h-[220px] flex-col items-center justify-center gap-4 rounded-[28px] border border-destructive/30 bg-destructive/10 p-6 text-center"
        role="alert"
      >
        <AlertCircle className="size-8 text-destructive" aria-hidden="true" />
        <div className="flex flex-col gap-1">
          <p className="font-medium text-foreground">Не удалось загрузить общий рейтинг месяца</p>
          <p className="text-sm text-muted-foreground">{error}</p>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="min-h-[44px]"
          onClick={onRetry}
        >
          Повторить
        </Button>
      </div>
    );
  }

  if (model.score === null) {
    return <EmptyState />;
  }

  return (
    <section
      className="overflow-hidden rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 88%, var(--ft-bg-base)) 0%, color-mix(in srgb, var(--ft-surface-base) 96%, var(--ft-bg-base)) 100%)',
      }}
    >
      <div className="grid grid-cols-1 gap-5 px-6 py-6 lg:grid-cols-[minmax(260px,0.9fr)_minmax(0,1.55fr)]">
        <ScoreMainBlock model={model} />

        {children && (
          <div className={cn('grid grid-cols-1 gap-4 sm:grid-cols-2')}>
            {children}
          </div>
        )}
      </div>
    </section>
  );
}

// vue-app/src/components/analytics/GlobalMonthScoreCard.vue
<script setup lang="ts">
import Message from 'primevue/message'
import Skeleton from 'primevue/skeleton'
import UiButton from '@/ui/UiButton.vue'

type GlobalMonthScoreAccent = 'good' | 'average' | 'poor' | 'neutral'
type GlobalMonthScoreDeltaTone = 'better' | 'worse' | 'neutral' | null

interface GlobalMonthScoreModel {
  score: number | null
  scoreLabel: string
  statusLabel: string
  statusDescription: string
  accent: GlobalMonthScoreAccent
  deltaLabel: string | null
  deltaTone: GlobalMonthScoreDeltaTone
}

defineProps<{
  loading: boolean
  error: string | null
  model: GlobalMonthScoreModel
}>()

const emit = defineEmits<{
  (event: 'retry'): void
}>()

const accentClass = (accent: GlobalMonthScoreAccent) => `global-score--${accent}`
const statusClass = (accent: GlobalMonthScoreAccent) => `global-score__status--${accent}`

function deltaClass(tone: GlobalMonthScoreDeltaTone): string {
  if (tone === 'better') return 'global-score__delta--better'
  if (tone === 'worse') return 'global-score__delta--worse'
  return 'global-score__delta--neutral'
}
</script>

<template>
  <section
    class="global-score"
    :class="accentClass(model.accent)"
  >
    <template v-if="loading">
      <div class="global-score__loading">
        <Skeleton
          width="220px"
          height="18px"
        />
        <Skeleton
          width="180px"
          height="56px"
        />
        <Skeleton
          width="100%"
          height="16px"
        />
      </div>
    </template>

    <template v-else-if="error">
      <Message
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        <div class="global-score__error">
          <p class="global-score__error-title">
            Не удалось загрузить общий рейтинг месяца
          </p>
          <UiButton
            label="Повторить"
            icon="pi pi-refresh"
            size="sm"
            @click="emit('retry')"
          />
        </div>
      </Message>
    </template>

    <template v-else>
      <div class="global-score__main">
        <p class="global-score__label">
          Общий рейтинг месяца
        </p>

        <div class="global-score__headline">
          <p class="global-score__value">
            {{ model.scoreLabel }}
          </p>
          <p
            class="global-score__status"
            :class="statusClass(model.accent)"
          >
            {{ model.statusLabel }}
          </p>
        </div>

        <p class="global-score__description">
          {{ model.statusDescription }}
        </p>

        <p
          class="global-score__delta"
          :class="deltaClass(model.deltaTone)"
        >
          {{ model.deltaLabel ?? 'Нет данных для сравнения с предыдущим месяцем' }}
        </p>
      </div>
    </template>
  </section>
</template>

<style scoped>
.global-score {
  display: grid;
  gap: var(--ft-space-4);

  padding: clamp(1.25rem, 2.2vw, 1.85rem);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-xl);
  box-shadow: var(--ft-shadow-sm);
}

.global-score__loading {
  display: grid;
  gap: var(--ft-space-3);
}

.global-score__error {
  display: flex;
  gap: var(--ft-space-3);
  align-items: center;
}

.global-score__error-title {
  margin: 0;
  font-weight: var(--ft-font-semibold);
}

.global-score__main {
  display: grid;
  gap: var(--ft-space-2);
}

.global-score__label {
  margin: 0;

  font-size: var(--ft-text-xs);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.global-score__headline {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ft-space-2);
  align-items: center;
}

.global-score__value {
  margin: 0;

  font-size: clamp(2.1rem, 5vw, 3.1rem);
  font-weight: var(--ft-font-bold);
  line-height: 1;
  color: var(--ft-text-primary);
}

.global-score__status {
  margin: 0;
  padding: var(--ft-space-1) var(--ft-space-2);

  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);

  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-full);
}

.global-score__status--good {
  color: var(--ft-success-400);
  background: color-mix(in srgb, var(--ft-success-400) 10%, transparent);
  border-color: color-mix(in srgb, var(--ft-success-400) 30%, transparent);
}

.global-score__status--average {
  color: var(--ft-warning-400);
  background: color-mix(in srgb, var(--ft-warning-400) 12%, transparent);
  border-color: color-mix(in srgb, var(--ft-warning-400) 34%, transparent);
}

.global-score__status--poor {
  color: var(--ft-danger-400);
  background: color-mix(in srgb, var(--ft-danger-400) 12%, transparent);
  border-color: color-mix(in srgb, var(--ft-danger-400) 34%, transparent);
}

.global-score__status--neutral {
  color: var(--ft-text-secondary);
  background: color-mix(in srgb, var(--ft-surface-raised) 88%, transparent);
}

.global-score__description {
  margin: 0;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.global-score__delta {
  margin: 0;
  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
}

.global-score__delta--better {
  color: var(--ft-success-400);
}

.global-score__delta--worse {
  color: var(--ft-danger-400);
}

.global-score__delta--neutral {
  color: var(--ft-text-muted);
}

.global-score--good .global-score__value {
  color: var(--ft-success-400);
}

.global-score--average .global-score__value {
  color: var(--ft-warning-400);
}

.global-score--poor .global-score__value {
  color: var(--ft-danger-400);
}

@media (width <= 640px) {
  .global-score {
    gap: var(--ft-space-3);
    padding: var(--ft-space-4);
  }

  .global-score__error {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
