// react-app/src/components/analytics/HealthScoreCard.tsx
import { createElement } from 'react';
import {
  Shield,
  Banknote,
  Activity,
  Percent,
  Wallet,
  ShoppingBag,
  ChartNoAxesColumnIncreasing,
  type LucideIcon,
} from 'lucide-react';

import { cn } from '@/utils/cn';

import { InfoTooltip } from './InfoTooltip';
import type { MetricAccent, ZoneBarModel } from './models';

interface HealthScoreCardProps {
  title: string;
  icon: string;
  value: string;
  supportingValue?: string;
  supportingLabel: string;
  accent: MetricAccent;
  tooltip: string;
  zoneBar?: ZoneBarModel;
}

const ICON_MAP: Record<string, LucideIcon> = {
  Shield,
  Banknote,
  Activity,
  Percent,
  Wallet,
  ShoppingBag,
  ChartNoAxesColumnIncreasing,
};

function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Activity;
}

function accentColor(accent: MetricAccent): string {
  switch (accent) {
    case 'income':
    case 'good':
      return 'var(--ft-success-500)';
    case 'expense':
    case 'poor':
      return 'var(--ft-danger-500)';
    case 'warning':
      return 'var(--ft-warning-400)';
    case 'neutral':
    default:
      return 'var(--ft-primary-400)';
  }
}

function accentBgColor(accent: MetricAccent): string {
  switch (accent) {
    case 'income':
    case 'good':
      return 'color-mix(in srgb, var(--ft-success-500) 16%, transparent)';
    case 'expense':
    case 'poor':
      return 'color-mix(in srgb, var(--ft-danger-500) 16%, transparent)';
    case 'warning':
      return 'color-mix(in srgb, var(--ft-warning-500) 16%, transparent)';
    case 'neutral':
    default:
      return 'color-mix(in srgb, var(--ft-text-secondary) 10%, transparent)';
  }
}

function resolveZoneColors(inverted = false) {
  const forward = [
    'var(--ft-danger-500)',
    'var(--ft-warning-500)',
    'var(--ft-success-500)',
  ];

  return inverted ? [...forward].reverse() : forward;
}

function ZoneBar({ model }: { model: ZoneBarModel }) {
  const colors = resolveZoneColors(model.inverted);
  const [warnStart, goodStart] = model.thresholds;
  const poorWidth = `${Math.max((warnStart / model.scaleMax) * 100, 0)}%`;
  const warningWidth = `${Math.max(((goodStart - warnStart) / model.scaleMax) * 100, 0)}%`;
  const goodWidth = `${Math.max(((model.scaleMax - goodStart) / model.scaleMax) * 100, 0)}%`;
  const markerPosition = `${Math.min(
    100,
    Math.max(0, ((model.value ?? 0) / model.scaleMax) * 100),
  )}%`;

  return (
    <div className="mt-auto pt-5">
      <div className="relative h-1.5 overflow-hidden rounded-full bg-[color-mix(in_srgb,var(--ft-surface-overlay)_72%,transparent)]">
        <div className="flex h-full w-full">
          <div style={{ width: poorWidth, backgroundColor: colors[0] }} />
          <div style={{ width: warningWidth, backgroundColor: colors[1] }} />
          <div style={{ width: goodWidth, backgroundColor: colors[2] }} />
        </div>

        <span
          className="absolute top-1/2 h-3.5 w-1.5 -translate-y-1/2 rounded-full border border-[var(--ft-surface-base)] bg-[var(--ft-text-primary)] shadow-[var(--ft-shadow-xs)]"
          style={{ left: `calc(${markerPosition} - 0.1875rem)` }}
          aria-hidden="true"
        />
      </div>
    </div>
  );
}

export function HealthScoreCard({
  title,
  icon,
  value,
  supportingValue,
  supportingLabel,
  accent,
  tooltip,
  zoneBar,
}: HealthScoreCardProps) {
  const color = accentColor(accent);

  return (
    <div
      className={cn(
        'flex h-full flex-col gap-4 rounded-[24px] border border-[var(--ft-border-subtle)] px-5 py-5 shadow-[var(--ft-shadow-xs)]',
      )}
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-base) 94%, var(--ft-bg-base)) 0%, color-mix(in srgb, var(--ft-surface-raised) 92%, var(--ft-bg-base)) 100%)',
      }}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-3">
          <div
            className="flex size-14 shrink-0 items-center justify-center rounded-full"
            style={{
              color,
              backgroundColor: accentBgColor(accent),
            }}
            aria-hidden="true"
          >
            {createElement(resolveIcon(icon), { className: 'size-5 shrink-0' })}
          </div>

          <span className="pt-2 text-base font-semibold text-foreground">{title}</span>
        </div>

        <InfoTooltip
          content={tooltip}
          className="-mt-2 -mr-2"
          ariaLabel={`Подробнее: ${title}`}
        />
      </div>

      <div className="flex flex-1 flex-col gap-3">
        <span
          className="text-[clamp(2.1rem,3.5vw,2.45rem)] font-bold leading-none"
          style={{ fontVariantNumeric: 'tabular-nums', color }}
        >
          {value}
        </span>

        <div className="space-y-1 text-sm text-[var(--ft-text-secondary)]">
          {supportingValue && (
            <p
              className="font-semibold text-foreground"
              style={{ fontVariantNumeric: 'tabular-nums' }}
            >
              {supportingValue}
              <span className="ml-2 font-normal text-[var(--ft-text-secondary)]">
                {supportingLabel}
              </span>
            </p>
          )}

          {!supportingValue && <p className="leading-6">{supportingLabel}</p>}
        </div>

        {zoneBar && <ZoneBar model={zoneBar} />}
      </div>
    </div>
  );
}

// vue-app/src/components/analytics/HealthScoreCard.vue
<script setup lang="ts">
type HealthAccent = 'good' | 'average' | 'poor' | 'neutral';

defineProps<{
  title: string;
  icon: string;
  mainValue: string;
  mainLabel: string;
  secondaryValue?: string;
  secondaryLabel?: string;
  accent: HealthAccent;
  tooltip: string;
}>();

const barClass = (accent: HealthAccent) => `health-score__bar--${accent}`;
const valueClass = (accent: HealthAccent) => `health-score__main-value--${accent}`;
</script>

<template>
  <div class="health-score">
    <div class="health-score__header">
      <span
        class="health-score__icon"
        :class="`health-score__icon--${accent}`"
      >
        <i :class="icon" />
      </span>
      <p class="health-score__title">
        {{ title }}
      </p>
      <button
        v-tooltip="{ value: tooltip, event: 'click', autoHide: false }"
        type="button"
        class="health-score__hint"
        aria-label="Подсказка"
      >
        <i class="pi pi-question-circle" />
      </button>
    </div>

    <div class="health-score__body">
      <p
        class="health-score__main-value"
        :class="valueClass(accent)"
      >
        {{ mainValue }}
      </p>
      <p class="health-score__main-label">
        {{ mainLabel }}
      </p>
    </div>

    <div
      v-if="secondaryValue"
      class="health-score__secondary"
    >
      <span class="health-score__secondary-value">{{ secondaryValue }}</span>
      <span
        v-if="secondaryLabel"
        class="health-score__secondary-label"
      >{{ secondaryLabel }}</span>
    </div>

    <div
      class="health-score__bar"
      :class="barClass(accent)"
    />
  </div>
</template>

<style scoped>
.health-score {
  position: relative;

  overflow: hidden;
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);

  padding: clamp(1.25rem, 2vw, 1.75rem);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-xl);
  box-shadow: var(--ft-shadow-sm);
}

.health-score__header {
  display: flex;
  gap: var(--ft-space-2);
  align-items: center;
}

.health-score__icon {
  display: grid;
  flex-shrink: 0;
  place-items: center;

  width: var(--ft-control-height);
  height: var(--ft-control-height);

  font-size: 1.05rem;
  color: var(--ft-text-secondary);

  background: color-mix(in srgb, var(--ft-surface-raised) 80%, transparent);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-lg);
}

.health-score__icon--good {
  color: var(--ft-success-400);
  background: color-mix(in srgb, var(--ft-success-400) 10%, transparent);
  border-color: color-mix(in srgb, var(--ft-success-400) 20%, transparent);
}

.health-score__icon--average {
  color: var(--ft-warning-400);
  background: color-mix(in srgb, var(--ft-warning-400) 10%, transparent);
  border-color: color-mix(in srgb, var(--ft-warning-400) 20%, transparent);
}

.health-score__icon--poor {
  color: var(--ft-danger-400);
  background: color-mix(in srgb, var(--ft-danger-400) 10%, transparent);
  border-color: color-mix(in srgb, var(--ft-danger-400) 20%, transparent);
}

.health-score__title {
  margin: 0;
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-secondary);
}

.health-score__hint {
  cursor: pointer;

  display: inline-flex;
  align-items: center;
  justify-content: center;

  /* Ensure minimum touch target size */
  min-width: var(--ft-control-height);
  min-height: var(--ft-control-height);
  margin-left: auto;
  padding: 0;

  font-size: 1rem;
  color: var(--ft-text-muted);

  background: none;
  border: none;

  transition: color var(--ft-transition-fast);
}

.health-score__hint:hover {
  color: var(--ft-text-secondary);
}

.health-score__hint:active {
  color: var(--ft-accent-primary);
}

.health-score__body {
  display: grid;
  gap: 2px;
}

.health-score__main-value {
  margin: 0;

  font-size: clamp(1.75rem, 2.5vw, 2.25rem);
  font-weight: var(--ft-font-bold);
  line-height: 1.15;
  color: var(--ft-text-primary);
}

.health-score__main-value--good {
  color: var(--ft-success-400);
}

.health-score__main-value--average {
  color: var(--ft-warning-400);
}

.health-score__main-value--poor {
  color: var(--ft-danger-400);
}

.health-score__main-label {
  margin: 0;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.health-score__secondary {
  display: flex;
  gap: var(--ft-space-2);
  align-items: baseline;

  padding-top: var(--ft-space-1);

  font-size: var(--ft-text-base);

  border-top: 1px solid var(--ft-border-subtle);
}

.health-score__secondary-value {
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.health-score__secondary-label {
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.health-score__bar {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;

  height: 3px;

  background: var(--ft-border-subtle);
  border-radius: 0 0 var(--ft-radius-xl) var(--ft-radius-xl);
}

.health-score__bar--good {
  background: var(--ft-success-400);
}

.health-score__bar--average {
  background: var(--ft-warning-400);
}

.health-score__bar--poor {
  background: var(--ft-danger-400);
}

@media (width <= 640px) {
  .health-score {
    gap: var(--ft-space-3);
    padding: var(--ft-space-4);
  }

  .health-score__main-value {
    font-size: var(--ft-text-2xl);
  }

  .health-score__icon {
    width: 44px;
    height: 44px;
    font-size: var(--ft-text-base);
  }
}
</style>
