// react-app/src/components/analytics/PeakDaysCard.tsx
import { useState } from 'react';
import { AlertCircle, Bolt } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/utils/cn';
import type { PeakDayDto, PeakDaysSummaryDto } from '@/types';

import { InfoTooltip } from './InfoTooltip';
import {
  formatAnalyticsMetaMoney,
  formatAnalyticsPercent,
} from './models';

interface PeakDaysCardProps {
  loading: boolean;
  error: string | null;
  peaks: PeakDayDto[];
  summary: PeakDaysSummaryDto;
  currency: string;
  onRetry: () => void;
  onPeakSelect: (peak: PeakDayDto) => void;
}

const DATE_FMT = new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short' });
const DEFAULT_VISIBLE = 3;

function formatPeakDate(year: number, month: number, day: number): string {
  return DATE_FMT.format(new Date(year, month - 1, day));
}

function pluralizeDays(n: number): string {
  if (n % 100 >= 11 && n % 100 <= 14) return 'дней';
  if (n % 10 === 1) return 'день';
  if (n % 10 >= 2 && n % 10 <= 4) return 'дня';
  return 'дней';
}

function resolveShareStyles(share: number | null) {
  if (share === null) {
    return {
      value: 'var(--ft-text-primary)',
      border: 'var(--ft-border-subtle)',
      background: 'color-mix(in srgb, var(--ft-surface-base) 74%, transparent)',
    };
  }

  if (share <= 10) {
    return {
      value: 'var(--ft-success-400)',
      border: 'color-mix(in srgb, var(--ft-success-500) 45%, var(--ft-border-subtle))',
      background: 'color-mix(in srgb, var(--ft-success-500) 10%, transparent)',
    };
  }

  if (share <= 25) {
    return {
      value: 'var(--ft-warning-300)',
      border: 'color-mix(in srgb, var(--ft-warning-500) 45%, var(--ft-border-subtle))',
      background: 'color-mix(in srgb, var(--ft-warning-500) 10%, transparent)',
    };
  }

  return {
    value: 'var(--ft-danger-400)',
    border: 'color-mix(in srgb, var(--ft-danger-500) 45%, var(--ft-border-subtle))',
    background: 'color-mix(in srgb, var(--ft-danger-500) 10%, transparent)',
  };
}

function PeakDaysSkeleton() {
  return (
    <div
      role="status"
      aria-busy="true"
      aria-label="Загрузка пиковых дней"
      className="space-y-4 px-7 pb-7"
    >
      <Skeleton className="h-[148px] rounded-[24px]" />
      <Skeleton className="h-[68px] rounded-2xl" />
      <Skeleton className="h-[68px] rounded-2xl" />
      <Skeleton className="h-[68px] rounded-2xl" />
    </div>
  );
}

function SummaryBlock({
  summary,
  currency,
}: {
  summary: PeakDaysSummaryDto;
  currency: string;
}) {
  const styles = resolveShareStyles(summary.sharePercent);
  const shareLabel = formatAnalyticsPercent(summary.sharePercent);

  return (
    <div
      className="rounded-[24px] border px-6 py-6"
      style={{
        borderColor: styles.border,
        backgroundColor: styles.background,
      }}
    >
      <p
        className="text-[clamp(2.45rem,5vw,3.25rem)] font-bold leading-[0.96]"
        style={{ color: styles.value, fontVariantNumeric: 'tabular-nums' }}
      >
        {shareLabel}
      </p>

      <p className="mt-2 text-base font-medium text-[var(--ft-text-secondary)]">
        расходов в пиковые дни
      </p>

      <p className="mt-3 text-sm text-[var(--ft-text-tertiary)]">
        {summary.count} {pluralizeDays(summary.count)} · {formatAnalyticsMetaMoney(summary.total, currency)} из{' '}
        {formatAnalyticsMetaMoney(summary.monthTotal, currency)}
      </p>
    </div>
  );
}

function PeakItem({
  peak,
  currency,
  onSelect,
}: {
  peak: PeakDayDto;
  currency: string;
  onSelect: (peak: PeakDayDto) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onSelect(peak)}
      className={cn(
        'grid min-h-[68px] w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 px-5 py-4 text-left transition-colors',
        'hover:bg-[color-mix(in_srgb,var(--ft-primary-400)_8%,transparent)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
      )}
    >
      <span className="text-base font-semibold text-foreground">
        {formatPeakDate(peak.year, peak.month, peak.day)}
      </span>

      <span className="flex flex-col items-end gap-1 text-right">
        <span className="text-base font-semibold tabular-nums text-foreground">
          {formatAnalyticsMetaMoney(peak.amount, currency)}
        </span>
        <span className="text-sm tabular-nums text-[var(--ft-text-secondary)]">
          {formatAnalyticsPercent(peak.sharePercent)}
        </span>
      </span>
    </button>
  );
}

export function PeakDaysCard({
  loading,
  error,
  peaks,
  summary,
  currency,
  onRetry,
  onPeakSelect,
}: PeakDaysCardProps) {
  const [expanded, setExpanded] = useState(false);
  const visiblePeaks = expanded ? peaks : peaks.slice(0, DEFAULT_VISIBLE);
  const hasMore = peaks.length > DEFAULT_VISIBLE;

  return (
    <Card
      className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
      }}
    >
      <div className="flex items-center gap-2 px-6 py-6">
        <div className="flex items-center gap-3">
          <Bolt className="size-5 text-[var(--ft-warning-400)]" aria-hidden="true" />
          <h2 className="text-[1.75rem] font-semibold leading-tight text-foreground">Пиковые дни</h2>
        </div>
        <InfoTooltip
          content="Дни, когда расходы заметно превысили привычный темп месяца."
          className="-mt-1"
          ariaLabel="Подробнее о пиковых днях"
        />
      </div>

      {loading ? (
        <PeakDaysSkeleton />
      ) : error ? (
        <div
          className="flex min-h-[296px] flex-col items-center justify-center gap-4 px-7 pb-7 text-center"
          role="alert"
        >
          <AlertCircle className="size-8 text-destructive" aria-hidden="true" />
          <div className="space-y-1">
            <p className="text-base font-medium text-foreground">Не удалось загрузить данные</p>
            <p className="text-sm text-[var(--ft-text-secondary)]">{error}</p>
          </div>
          <Button variant="outline" className="min-h-[44px]" onClick={onRetry}>
            Повторить
          </Button>
        </div>
      ) : peaks.length === 0 ? (
        <div className="px-7 pb-7">
          <div className="flex min-h-[296px] items-center justify-center rounded-[24px] border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-surface-base)_75%,transparent)] px-8 text-center">
            <p className="max-w-md text-base leading-7 text-[var(--ft-text-secondary)]">
              Пиковых дней нет. Расходы распределены по месяцу достаточно равномерно.
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-4 px-7 pb-7">
          <SummaryBlock summary={summary} currency={currency} />

          <div className="divide-y divide-[var(--ft-border-subtle)] rounded-[24px] border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-surface-base)_75%,transparent)]">
            {visiblePeaks.map((peak) => (
              <PeakItem
                key={`${peak.year}-${peak.month}-${peak.day}`}
                peak={peak}
                currency={currency}
                onSelect={onPeakSelect}
              />
            ))}
          </div>

          {hasMore && (
            <Button
              variant="ghost"
              className="min-h-[44px] w-full rounded-2xl text-[var(--ft-text-secondary)]"
              onClick={() => setExpanded((prev) => !prev)}
            >
              {expanded ? 'Свернуть' : `Показать все (${peaks.length})`}
            </Button>
          )}
        </div>
      )}
    </Card>
  );
}

// vue-app/src/components/analytics/PeakDaysCard.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import Skeleton from 'primevue/skeleton';
import Message from 'primevue/message';
import UiButton from '../../ui/UiButton.vue';

interface PeakDayItem {
  label: string;
  amountLabel: string;
  amount: number;
  date: Date;
  shareLabel: string;
}

interface PeaksSummary {
  count: number;
  totalLabel: string;
  shareLabel: string;
  shareValue: number | null;
  monthLabel: string;
}

const props = withDefaults(
  defineProps<{
    loading: boolean;
    error: string | null;
    peaks: PeakDayItem[];
    summary: PeaksSummary;
  }>(),
  {
    peaks: () => [],
    summary: () => ({ count: 0, totalLabel: '—', shareLabel: '—', shareValue: null, monthLabel: '—' }),
  }
);

const emit = defineEmits<{
  (event: 'retry'): void;
  (event: 'select-peak', value: PeakDayItem): void;
  (event: 'select-peak-summary'): void;
}>();

const showAll = ref(false);
const hasMore = computed(() => props.peaks.length > 3);
const visiblePeaks = computed(() => showAll.value ? props.peaks : props.peaks.slice(0, 3));

const showEmpty = computed(() => !props.loading && !props.error && props.peaks.length === 0);

const shareAccent = computed(() => {
  const share = props.summary.shareValue;
  if (share == null) return 'neutral';
  if (share <= 30) return 'good';
  if (share <= 50) return 'average';
  return 'poor';
});
</script>

<template>
  <div class="peak-days">
    <div class="peak-days__header">
      <div>
        <h3
          v-tooltip.top="'Дни, когда расходы значительно превысили среднедневной уровень. Помогает выявить крупные разовые траты.'"
          class="peak-days__title"
        >
          <i class="pi pi-bolt" />
          Пиковые дни
        </h3>
      </div>
    </div>

    <div
      v-if="loading"
      class="peak-days__loading"
    >
      <Skeleton
        width="100%"
        height="60px"
        border-radius="12px"
      />
      <Skeleton
        v-for="i in 2"
        :key="i"
        width="100%"
        height="44px"
        border-radius="10px"
      />
    </div>

    <div
      v-else-if="error"
      class="peak-days__message"
    >
      <Message
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        <div class="peak-days__message-body">
          <p>Не удалось загрузить данные</p>
          <UiButton
            label="Повторить"
            icon="pi pi-refresh"
            size="sm"
            @click="emit('retry')"
          />
        </div>
      </Message>
    </div>

    <div
      v-else-if="showEmpty"
      class="peak-days__message"
    >
      <Message
        severity="info"
        icon="pi pi-check-circle"
        :closable="false"
      >
        <p>Пиковых дней нет — расходы стабильны.</p>
      </Message>
    </div>

    <template v-else>
      <button
        type="button"
        class="peak-days__summary"
        :class="`peak-days__summary--${shareAccent}`"
        :aria-label="`${summary.shareLabel} расходов в пиковые дни: ${summary.count} дней, ${summary.totalLabel} из ${summary.monthLabel}`"
        @click="emit('select-peak-summary')"
      >
        <span class="peak-days__share-value">{{ summary.shareLabel }}</span>
        <span class="peak-days__share-text">расходов в пиковые дни</span>
        <span class="peak-days__share-meta">{{ summary.count }} дней &middot; {{ summary.totalLabel }} из {{ summary.monthLabel }}</span>
      </button>

      <div class="peak-days__list">
        <button
          v-for="peak in visiblePeaks"
          :key="peak.label"
          type="button"
          class="peak-days__item"
          @click="emit('select-peak', peak)"
        >
          <span class="peak-days__item-date">{{ peak.label }}</span>
          <span class="peak-days__item-amount">{{ peak.amountLabel }}</span>
          <span class="peak-days__item-share">{{ peak.shareLabel }}</span>
        </button>
      </div>

      <button
        v-if="hasMore"
        type="button"
        class="peak-days__toggle"
        @click="showAll = !showAll"
      >
        {{ showAll ? 'Свернуть' : `Показать все (${peaks.length})` }}
      </button>
    </template>
  </div>
</template>

<style scoped>
.peak-days {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);

  padding: clamp(1rem, 2vw, 1.5rem);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-2xl);
  box-shadow: var(--ft-shadow-sm);
}

.peak-days__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.peak-days__title {
  cursor: help;

  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;

  margin: 0;

  font-size: var(--ft-text-lg);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.peak-days__title i {
  font-size: 1rem;
  color: var(--ft-warning-400);
}

.peak-days__loading {
  display: grid;
  gap: var(--ft-space-3);
}

.peak-days__message {
  display: grid;
}

.peak-days__message-body {
  display: flex;
  gap: var(--ft-space-3);
  align-items: center;
}

.peak-days__message-body p {
  margin: 0;
  font-weight: var(--ft-font-semibold);
}

.peak-days__summary {
  cursor: pointer;

  display: grid;
  gap: var(--ft-space-1);

  width: 100%;
  padding: var(--ft-space-3);

  text-align: left;

  background: color-mix(in srgb, var(--ft-surface-raised) 60%, transparent);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-lg);

  transition: border-color var(--ft-transition-fast);
}

.peak-days__summary:hover {
  border-color: color-mix(in srgb, var(--ft-border-strong) 50%, transparent);
}

.peak-days__summary:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--ft-primary-500) 55%, transparent);
  outline-offset: 2px;
}

.peak-days__share-value {
  font-size: clamp(1.75rem, 3vw, 2.5rem);
  font-weight: var(--ft-font-bold);
  line-height: 1;
  color: var(--ft-text-primary);
}

.peak-days__summary--good .peak-days__share-value {
  color: var(--ft-success-400);
}

.peak-days__summary--average .peak-days__share-value {
  color: var(--ft-warning-400);
}

.peak-days__summary--poor .peak-days__share-value {
  color: var(--ft-danger-400);
}

.peak-days__summary--good {
  border-color: color-mix(in srgb, var(--ft-success-400) 30%, var(--ft-border-subtle));
}

.peak-days__summary--average {
  border-color: color-mix(in srgb, var(--ft-warning-400) 30%, var(--ft-border-subtle));
}

.peak-days__summary--poor {
  border-color: color-mix(in srgb, var(--ft-danger-400) 30%, var(--ft-border-subtle));
}

.peak-days__share-text {
  font-size: var(--ft-text-base);
  color: var(--ft-text-secondary);
}

.peak-days__share-meta {
  font-size: var(--ft-text-sm);
  color: var(--ft-text-tertiary);
}

.peak-days__list {
  display: grid;
  gap: var(--ft-space-2);
}

.peak-days__item {
  cursor: pointer;

  display: grid;
  grid-template-columns: auto 1fr auto;
  gap: var(--ft-space-3);
  align-items: center;

  width: 100%;
  padding: var(--ft-space-3);

  text-align: left;

  background: color-mix(in srgb, var(--ft-surface-soft) 70%, transparent);
  border: 1px solid transparent;
  border-radius: var(--ft-radius-lg);

  transition: background var(--ft-transition-fast), border-color var(--ft-transition-fast);
}

.peak-days__item:hover {
  background: var(--ft-surface-raised);
  border-color: var(--ft-border-subtle);
}

.peak-days__item:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--ft-primary-500) 55%, transparent);
  outline-offset: 2px;
}

.peak-days__item-date {
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-primary);
  white-space: nowrap;
}

.peak-days__item-amount {
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-bold);
  color: var(--ft-text-primary);
  text-align: right;
}

.peak-days__item-share {
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
  white-space: nowrap;
}

.peak-days__toggle {
  cursor: pointer;

  padding: var(--ft-space-1) 0;

  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
  color: var(--ft-primary-400);
  text-align: left;

  background: transparent;
  border: none;
}

.peak-days__toggle:hover {
  text-decoration: underline;
}
</style>
