// react-app/src/components/analytics/SpendingPieCard.tsx
import { useMemo, useState } from 'react';
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
  type TooltipProps,
} from 'recharts';

import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import type { CategoryBreakdownDto, CategoryBreakdownItemDto } from '@/types';

import { InfoTooltip } from './InfoTooltip';
import {
  formatAnalyticsHeroMoney,
  formatAnalyticsMetaMoney,
  formatAnalyticsPercent,
} from './models';

type CategoryDatasetMode = 'expenses' | 'income';
type CategoryScope = 'all' | 'mandatory' | 'discretionary';

interface SpendingPieCardProps {
  loading: boolean;
  error: string | null;
  data: CategoryBreakdownDto | null;
  currency: string;
  mode: CategoryDatasetMode;
  modeOptions: Array<{ label: string; value: CategoryDatasetMode }>;
  scope: CategoryScope;
  scopeOptions: Array<{ label: string; value: CategoryScope }>;
  onModeChange: (mode: CategoryDatasetMode) => void;
  onScopeChange: (scope: CategoryScope) => void;
  onCategorySelect: (item: CategoryBreakdownItemDto) => void;
  onRetry: () => void;
}

function getDisplayAmount(item: CategoryBreakdownItemDto, scope: CategoryScope): number {
  if (scope === 'mandatory') return item.mandatoryAmount;
  if (scope === 'discretionary') return item.discretionaryAmount;
  return item.amount;
}

function getDisplayTitle(mode: CategoryDatasetMode): string {
  return mode === 'income' ? 'Доходы по категориям' : 'Расходы по категориям';
}

function ChartTooltip({
  active,
  payload,
  currency,
}: TooltipProps<number, string> & { currency: string }) {
  const entry = payload?.[0]?.payload as
    | (CategoryBreakdownItemDto & { displayAmount: number })
    | undefined;

  if (!active || !entry) {
    return null;
  }

  return (
    <div className="rounded-xl border border-border bg-popover px-3 py-2 text-sm text-popover-foreground shadow-md">
      <div className="flex items-center gap-2">
        <span
          className="inline-block size-2.5 rounded-full"
          style={{ backgroundColor: entry.color }}
        />
        <span className="font-semibold text-foreground">{entry.name}</span>
      </div>
      <p className="mt-2 tabular-nums text-foreground">
        {formatAnalyticsMetaMoney(entry.displayAmount, currency)}
      </p>
      <p className="text-xs text-muted-foreground">
        {formatAnalyticsPercent(entry.percent)}
      </p>
    </div>
  );
}

function ModeToggle<T extends string>({
  options,
  value,
  onChange,
}: {
  options: Array<{ label: string; value: T }>;
  value: T;
  onChange: (value: T) => void;
}) {
  return (
    <div className="flex rounded-2xl border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-bg-base)_32%,transparent)] p-1">
      {options.map((option) => (
        <Button
          key={option.value}
          type="button"
          variant="ghost"
          onClick={() => onChange(option.value)}
          className={
            option.value === value
              ? 'rounded-xl bg-card text-foreground shadow-[var(--ft-shadow-xs)]'
              : 'rounded-xl text-[var(--ft-text-tertiary)] hover:text-foreground'
          }
        >
          {option.label}
        </Button>
      ))}
    </div>
  );
}

function LegendRow({
  item,
  currency,
  isActive,
  onHover,
  onClick,
}: {
  item: CategoryBreakdownItemDto & { displayAmount: number };
  currency: string;
  isActive: boolean;
  onHover: (id: string | null) => void;
  onClick: (item: CategoryBreakdownItemDto) => void;
}) {
  return (
    <button
      type="button"
      className="grid min-h-[64px] w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-2xl px-3 py-3 text-left transition-colors hover:bg-[color-mix(in_srgb,var(--ft-primary-400)_8%,transparent)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      style={{ opacity: isActive ? 1 : 0.45 }}
      onMouseEnter={() => onHover(item.id)}
      onMouseLeave={() => onHover(null)}
      onClick={() => onClick(item)}
    >
      <span
        className="inline-block size-4 rounded-full"
        style={{ backgroundColor: item.color }}
        aria-hidden="true"
      />

      <div className="min-w-0">
        <p className="truncate text-base font-semibold text-foreground">{item.name}</p>
        <p className="truncate text-sm font-semibold tabular-nums text-[var(--ft-text-secondary)]">
          {formatAnalyticsMetaMoney(item.displayAmount, currency)}
        </p>
      </div>

      <p className="text-right text-base font-semibold tabular-nums text-foreground">
        {formatAnalyticsPercent(item.percent)}
      </p>
    </button>
  );
}

function PieSkeleton() {
  return (
    <div className="grid grid-cols-1 gap-6 px-7 pb-7 pt-3 lg:grid-cols-[minmax(280px,1fr)_minmax(280px,0.9fr)]">
      <div className="flex items-center justify-center">
        <Skeleton className="size-[320px] rounded-full" />
      </div>
      <div className="space-y-3">
        {[1, 2, 3, 4].map((key) => (
          <Skeleton key={key} className="h-[72px] rounded-2xl" />
        ))}
      </div>
    </div>
  );
}

export function SpendingPieCard({
  loading,
  error,
  data,
  currency,
  mode,
  modeOptions,
  scope,
  scopeOptions,
  onModeChange,
  onScopeChange,
  onCategorySelect,
  onRetry,
}: SpendingPieCardProps) {
  const [activeId, setActiveId] = useState<string | null>(null);

  const chartData = useMemo(
    () =>
      (data?.items ?? [])
        .map((item) => ({
          ...item,
          displayAmount: getDisplayAmount(item, scope),
        }))
        .filter((item) => item.displayAmount > 0)
        .sort((left, right) => right.displayAmount - left.displayAmount),
    [data?.items, scope],
  );

  const total = chartData.reduce((sum, item) => sum + item.displayAmount, 0);
  const isEmpty = !loading && !error && total === 0;

  return (
    <Card
      className="gap-0 rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
      }}
    >
      <div className="flex flex-col gap-5 px-6 py-6">
        <div className="grid gap-4 xl:grid-cols-[minmax(16rem,1fr)_auto] xl:items-start">
          <div className="flex min-w-0 items-start gap-2">
            <h2 className="max-w-[11ch] text-[1.75rem] font-semibold leading-tight text-foreground">
              {getDisplayTitle(mode)}
            </h2>
            <InfoTooltip
              content="Показывает распределение операций по категориям за выбранный месяц."
              className="-mt-1"
              ariaLabel="Подробнее о распределении по категориям"
            />
          </div>

          <div className="flex flex-wrap gap-3 xl:justify-end">
            <ModeToggle options={modeOptions} value={mode} onChange={onModeChange} />

            {mode === 'expenses' && (
              <Select value={scope} onValueChange={(value) => onScopeChange(value as CategoryScope)}>
                <SelectTrigger className="h-12 min-w-[156px] rounded-2xl border-[var(--ft-border-default)] bg-transparent px-4 text-base">
                  <SelectValue placeholder="Все" />
                </SelectTrigger>
                <SelectContent className="rounded-2xl border-[var(--ft-border-default)] bg-popover">
                  {scopeOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </div>
        </div>
      </div>

      {loading && <PieSkeleton />}

      {!loading && error && (
        <div className="flex flex-col items-center gap-4 px-7 pb-7 text-center">
          <p className="text-sm text-destructive">{error}</p>
          <Button variant="outline" onClick={onRetry}>
            Повторить
          </Button>
        </div>
      )}

      {!loading && !error && isEmpty && (
        <div className="px-7 pb-7">
          <p className="rounded-2xl border border-[var(--ft-border-subtle)] px-5 py-10 text-center text-base text-[var(--ft-text-secondary)]">
            Нет данных за выбранный период
          </p>
        </div>
      )}

      {!loading && !error && !isEmpty && (
        <div className="grid grid-cols-1 gap-7 px-6 pb-6 pt-1 lg:grid-cols-[minmax(320px,1.05fr)_minmax(280px,0.95fr)]">
          <div
            className="relative min-h-[372px]"
            role="img"
            aria-label="Кольцевая диаграмма распределения по категориям"
          >
            <ResponsiveContainer width="100%" height={372}>
              <PieChart>
                <Pie
                  data={chartData}
                  dataKey="displayAmount"
                  cx="50%"
                  cy="50%"
                  innerRadius="70%"
                  outerRadius="88%"
                  paddingAngle={1.2}
                  stroke="none"
                >
                  {chartData.map((entry) => (
                    <Cell
                      key={entry.id}
                      fill={entry.color}
                      opacity={activeId === null || activeId === entry.id ? 1 : 0.32}
                    />
                  ))}
                </Pie>
                <Tooltip content={(props) => <ChartTooltip {...props} currency={currency} />} />
              </PieChart>
            </ResponsiveContainer>

            <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
              <div className="flex flex-col items-center gap-1 text-center">
                <span className="text-xs font-medium uppercase tracking-[0.08em] text-[var(--ft-text-tertiary)]">
                  Всего
                </span>
                <span
                  className="text-[clamp(1.85rem,3.2vw,2.45rem)] font-bold leading-none text-foreground"
                  style={{ fontVariantNumeric: 'tabular-nums' }}
                >
                  {formatAnalyticsHeroMoney(total, currency)}
                </span>
              </div>
            </div>
          </div>

          <div className="rounded-[24px] border border-[var(--ft-border-subtle)] bg-[color-mix(in_srgb,var(--ft-surface-base)_82%,transparent)] p-2.5">
            <div className="max-h-[372px] space-y-1 overflow-y-auto pr-1">
              {chartData.map((item) => (
                <LegendRow
                  key={item.id}
                  item={item}
                  currency={currency}
                  isActive={activeId === null || activeId === item.id}
                  onHover={setActiveId}
                  onClick={onCategorySelect}
                />
              ))}
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}

// vue-app/src/components/analytics/SpendingPieCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ChartData, Plugin } from 'chart.js';
import SelectButton from 'primevue/selectbutton';
import Skeleton from 'primevue/skeleton';
import Message from 'primevue/message';
import UiButton from '../../ui/UiButton.vue';
import Chart from 'primevue/chart';
import type { CategoryLegendItem, CategoryScope } from '../../types/analytics';
import { useChartColors } from '../../composables/useChartColors';

const props = defineProps<{
  loading: boolean;
  error: string | null;
  chartData: ChartData<'pie', number[], string> | null;
  legend: CategoryLegendItem[];
  currency: string;
  scope: CategoryScope;
  scopeOptions: Array<{ label: string; value: CategoryScope }>;
}>();

const emit = defineEmits<{
  (event: 'retry'): void;
  (event: 'select-category', value: CategoryLegendItem): void;
  (event: 'update:scope', value: CategoryScope): void;
}>();

const { colors, tooltipConfig } = useChartColors();

const handleCategoryClick = (item: CategoryLegendItem) => {
  emit('select-category', item);
};

const showEmpty = computed(
  () => !props.loading && !props.error && (!props.chartData || props.legend.length === 0)
);

const totalAmount = computed(() => {
  return props.legend.reduce((sum, item) => sum + item.amount, 0);
});

const formattedTotal = computed(() => {
  if (totalAmount.value <= 0) return '—';
  return totalAmount.value.toLocaleString('ru-RU', {
    style: 'currency',
    currency: props.currency,
    maximumFractionDigits: 0,
  });
});

const centerTextPlugin = computed<Plugin<'doughnut'>>(() => ({
  id: 'centerText',
  afterDraw(chart) {
    const { ctx, width, height } = chart;
    if (!ctx) return;
    ctx.save();

    const text = formattedTotal.value;
    const fontSize = Math.min(width, height) * 0.08;
    ctx.font = `bold ${fontSize}px sans-serif`;
    ctx.fillStyle = colors.tooltipText;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(text, width / 2, height / 2);

    ctx.restore();
  },
}));

const donutChartData = computed(() => {
  if (!props.chartData) return null;
  return {
    ...props.chartData,
    datasets: props.chartData.datasets.map(ds => ({
      ...ds,
      borderWidth: 2,
      borderColor: colors.surface,
      hoverBorderWidth: 3,
      hoverOffset: 8,
    })),
  };
});

const chartOptions = computed(() => ({
  responsive: true,
  maintainAspectRatio: true,
  aspectRatio: 1,
  cutout: '65%',
  plugins: {
    legend: {
      display: false,
    },
    tooltip: {
      ...tooltipConfig(),
      callbacks: {
        label(context: { parsed: number; label: string }) {
          const formatted = context.parsed.toLocaleString('ru-RU', {
            style: 'currency',
            currency: props.currency,
            maximumFractionDigits: 0,
          });
          return `${context.label}: ${formatted}`;
        },
      },
    },
  },
}));
</script>

<template>
  <div class="donut-card">
    <div class="donut-card__head">
      <div>
        <div class="donut-card__title-row">
          <h3 class="donut-card__title">
            Расходы по категориям
          </h3>
          <i
            v-tooltip.top="'Показывает, на что уходят деньги. Кликните на категорию, чтобы увидеть транзакции.'"
            class="pi pi-question-circle donut-card__hint"
          />
        </div>
        <p class="donut-card__subtitle">
          Распределение за выбранный месяц
        </p>
      </div>
      <SelectButton
        :model-value="scope"
        :options="scopeOptions"
        option-label="label"
        option-value="value"
        class="donut-card__scope-toggle"
        @update:model-value="emit('update:scope', $event)"
      />
    </div>

    <div
      v-if="loading"
      class="donut-card__loading"
    >
      <Skeleton
        width="220px"
        height="220px"
        border-radius="999px"
      />
      <div class="donut-card__loading-legend">
        <Skeleton
          v-for="i in 4"
          :key="i"
          height="18px"
          width="70%"
        />
      </div>
    </div>

    <div
      v-else-if="error"
      class="donut-card__message"
    >
      <Message
        severity="error"
        icon="pi pi-exclamation-triangle"
        :closable="false"
      >
        <div class="donut-card__message-body">
          <p class="donut-card__message-title">
            Не удалось загрузить структуру расходов
          </p>
          <p class="donut-card__message-text">
            {{ error }}
          </p>
          <UiButton
            label="Попробовать снова"
            icon="pi pi-refresh"
            size="sm"
            @click="emit('retry')"
          />
        </div>
      </Message>
    </div>

    <div
      v-else-if="showEmpty"
      class="donut-card__message"
    >
      <Message
        severity="info"
        icon="pi pi-inbox"
        :closable="false"
      >
        <div class="donut-card__message-body donut-card__message-body--compact">
          <p class="donut-card__message-title">
            Нет данных за период
          </p>
          <p class="donut-card__message-text">
            Добавьте расходы, чтобы увидеть распределение.
          </p>
        </div>
      </Message>
    </div>

    <div
      v-else
      class="donut-card__content"
    >
      <div
        class="donut-card__chart"
        role="img"
        aria-label="Круговая диаграмма расходов по категориям"
      >
        <Chart
          v-if="donutChartData"
          type="doughnut"
          :data="donutChartData"
          :options="chartOptions"
          :plugins="[centerTextPlugin]"
        />
      </div>
      <ul class="donut-card__legend">
        <li
          v-for="item in legend"
          :key="item.id"
          class="donut-card__legend-item"
          role="button"
          tabindex="0"
          :aria-label="`${item.name}, ${item.amount.toLocaleString('ru-RU', {
            style: 'currency',
            currency,
            maximumFractionDigits: 0,
          })}, ${item.percent.toFixed(1)}%`"
          @click="handleCategoryClick(item)"
          @keydown.enter.prevent="handleCategoryClick(item)"
          @keydown.space.prevent="handleCategoryClick(item)"
        >
          <span
            class="donut-card__legend-color"
            :style="{ backgroundColor: item.color }"
          />
          <div class="donut-card__legend-body">
            <span class="donut-card__legend-name">{{ item.name }}</span>
            <span class="donut-card__legend-amount">
              {{
                item.amount.toLocaleString('ru-RU', {
                  style: 'currency',
                  currency,
                  maximumFractionDigits: 0,
                })
              }}
            </span>
          </div>
          <span class="donut-card__legend-percent">{{ item.percent.toFixed(1) }}%</span>
        </li>
      </ul>
    </div>
  </div>
</template>

<style scoped>
.donut-card {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);

  padding: clamp(1rem, 2vw, 1.5rem);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-2xl);
  box-shadow: var(--ft-shadow-sm);
}

.donut-card__head {
  display: flex;
  gap: var(--ft-space-4);
  align-items: flex-start;
  justify-content: space-between;
}

.donut-card__title-row {
  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;
}

.donut-card__title {
  margin: 0;

  font-size: var(--ft-text-lg);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-text-primary);
}

.donut-card__hint {
  cursor: help;
  font-size: 0.85rem;
  color: var(--ft-text-muted);
  transition: color var(--ft-transition-fast);
}

.donut-card__hint:hover {
  color: var(--ft-text-secondary);
}

.donut-card__subtitle {
  margin: var(--ft-space-1) 0 0;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.donut-card__loading {
  display: grid;
  gap: var(--ft-space-4);
  place-items: center;
  min-height: 280px;
}

.donut-card__loading-legend {
  display: grid;
  gap: var(--ft-space-2);
  width: 100%;
  max-width: 240px;
}

.donut-card__message {
  display: grid;
}

.donut-card__message-body {
  display: grid;
  gap: var(--ft-space-3);
}

.donut-card__message-body--compact {
  gap: var(--ft-space-2);
}

.donut-card__message-title {
  margin: 0;
  font-weight: var(--ft-font-semibold);
}

.donut-card__message-text {
  margin: 0;
}

.donut-card__content {
  display: grid;
  gap: var(--ft-space-4);
  align-items: start;
}

.donut-card__chart {
  display: flex;
  align-items: center;
  justify-content: center;

  width: 100%;
  padding: var(--ft-space-2);
}

.donut-card__chart :deep(.p-chart) {
  width: 100%;
  max-width: 280px;
}

.donut-card__chart :deep(canvas) {
  width: 100% !important;
  height: auto !important;
}

.donut-card__legend {
  display: grid;
  gap: var(--ft-space-2);

  margin: 0;
  padding: 0;

  list-style: none;
}

.donut-card__legend-item {
  cursor: pointer;

  display: flex;
  gap: var(--ft-space-3);
  align-items: center;

  padding: var(--ft-space-3);

  border: 1px solid transparent;
  border-radius: var(--ft-radius-lg);

  transition: background var(--ft-transition-fast), border-color var(--ft-transition-fast);
}

.donut-card__legend-item:hover {
  background: color-mix(in srgb, var(--ft-surface-raised) 70%, transparent);
  border-color: var(--ft-border-subtle);
}

.donut-card__legend-item:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--ft-primary-500) 65%, transparent);
  outline-offset: 2px;
}

.donut-card__legend-color {
  flex-shrink: 0;
  width: 12px;
  height: 12px;
  border-radius: 50%;
}

.donut-card__legend-body {
  display: grid;
  flex: 1;
  gap: 1px;
  min-width: 0;
}

.donut-card__legend-name {
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-primary);
}

.donut-card__legend-amount {
  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-semibold);
  font-variant-numeric: tabular-nums;
  color: var(--ft-text-secondary);
}

.donut-card__legend-percent {
  font-size: var(--ft-text-base);
  font-weight: var(--ft-font-bold);
  color: var(--ft-text-primary);
  white-space: nowrap;
}

@media (width >= 768px) {
  .donut-card__content {
    grid-template-columns: minmax(200px, 280px) minmax(0, 1fr);
  }

  .donut-card__legend {
    overflow: auto;
    max-height: 320px;
    padding-right: var(--ft-space-1);
  }
}

@media (width <= 640px) {
  .donut-card__head {
    flex-direction: column;
    align-items: stretch;
  }

  .donut-card__scope-toggle {
    width: 100%;
  }

  .donut-card__scope-toggle :deep(.p-button) {
    flex: 1 1 0;
    min-width: 0;
  }

  .donut-card__scope-toggle :deep(.p-button-label) {
    font-size: var(--ft-text-xs);
  }

  .donut-card__chart :deep(.p-chart) {
    max-width: 220px;
  }
}
</style>
