// vue-app/src/components/analytics/SummaryStrip.vue
<script setup lang="ts">
import Skeleton from 'primevue/skeleton';
import Message from 'primevue/message';
import UiButton from '../../ui/UiButton.vue';

type MetricAccent = 'income' | 'expense' | 'good' | 'poor' | 'neutral';

interface SummaryMetric {
  key: string;
  label: string;
  value: string;
  icon: string;
  accent: MetricAccent;
  tooltip: string;
  secondary?: string;
}

defineProps<{
  loading: boolean;
  error: string | null;
  metrics: SummaryMetric[];
}>();

const emit = defineEmits<{
  (event: 'retry'): void;
}>();

const accentClass = (accent: MetricAccent) => `summary-strip__value--${accent}`;
const iconAccentClass = (accent: MetricAccent) => `summary-strip__icon--${accent}`;
</script>

<template>
  <div class="summary-strip">
    <template v-if="loading">
      <div
        v-for="i in 3"
        :key="i"
        class="summary-strip__item summary-strip__item--skeleton"
      >
        <Skeleton
          width="40px"
          height="40px"
          border-radius="12px"
        />
        <div class="summary-strip__skeleton-text">
          <Skeleton
            width="80px"
            height="14px"
          />
          <Skeleton
            width="120px"
            height="28px"
          />
        </div>
      </div>
    </template>

    <template v-else-if="error">
      <div class="summary-strip__error">
        <Message
          severity="error"
          icon="pi pi-exclamation-triangle"
          :closable="false"
        >
          <div class="summary-strip__error-body">
            <p class="summary-strip__error-title">
              Не удалось загрузить сводку
            </p>
            <UiButton
              label="Повторить"
              icon="pi pi-refresh"
              size="sm"
              @click="emit('retry')"
            />
          </div>
        </Message>
      </div>
    </template>

    <template v-else>
      <div
        v-for="metric in metrics"
        :key="metric.key"
        class="summary-strip__item"
      >
        <span
          class="summary-strip__icon"
          :class="iconAccentClass(metric.accent)"
        >
          <i :class="metric.icon" />
        </span>
        <div class="summary-strip__text">
          <p class="summary-strip__label">
            {{ metric.label }}
            <i
              v-tooltip.top="metric.tooltip"
              class="pi pi-question-circle summary-strip__hint"
            />
          </p>
          <p
            class="summary-strip__value"
            :class="accentClass(metric.accent)"
          >
            {{ metric.value }}
          </p>
          <p
            v-if="metric.secondary"
            class="summary-strip__secondary"
          >
            {{ metric.secondary }}
          </p>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.summary-strip {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: var(--ft-space-4);

  padding: var(--ft-space-5);

  background: var(--ft-surface-base);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-2xl);
  box-shadow: var(--ft-shadow-sm);
}

.summary-strip__item {
  display: flex;
  gap: var(--ft-space-3);
  align-items: flex-start;

  padding: var(--ft-space-3);

  border-radius: var(--ft-radius-xl);
}

.summary-strip__item--skeleton {
  cursor: default;
}

.summary-strip__item--skeleton:hover {
  background: transparent;
}

.summary-strip__skeleton-text {
  display: grid;
  gap: var(--ft-space-2);
}

.summary-strip__icon {
  display: grid;
  flex-shrink: 0;
  place-items: center;

  width: 44px;
  height: 44px;

  font-size: 1.1rem;
  color: var(--ft-text-secondary);

  background: color-mix(in srgb, var(--ft-surface-raised) 80%, transparent);
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-lg);
}

.summary-strip__icon--income {
  color: var(--ft-success-400);
  background: color-mix(in srgb, var(--ft-success-400) 12%, transparent);
  border-color: color-mix(in srgb, var(--ft-success-400) 25%, transparent);
}

.summary-strip__icon--expense {
  color: var(--ft-danger-400);
  background: color-mix(in srgb, var(--ft-danger-400) 12%, transparent);
  border-color: color-mix(in srgb, var(--ft-danger-400) 25%, transparent);
}

.summary-strip__icon--good {
  color: var(--ft-success-400);
  background: color-mix(in srgb, var(--ft-success-400) 12%, transparent);
  border-color: color-mix(in srgb, var(--ft-success-400) 25%, transparent);
}

.summary-strip__icon--poor {
  color: var(--ft-danger-400);
  background: color-mix(in srgb, var(--ft-danger-400) 12%, transparent);
  border-color: color-mix(in srgb, var(--ft-danger-400) 25%, transparent);
}

.summary-strip__text {
  display: grid;
  gap: 2px;
  min-width: 0;
}

.summary-strip__label {
  display: flex;
  gap: var(--ft-space-1);
  align-items: center;

  margin: 0;

  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.summary-strip__hint {
  cursor: pointer;
  font-size: 0.95rem;
  color: var(--ft-text-muted);
  text-transform: none;
  transition: color var(--ft-transition-fast);

  /* Ensure minimum touch target size */
  min-width: var(--ft-control-height);
  min-height: var(--ft-control-height);
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.summary-strip__hint:hover {
  color: var(--ft-text-secondary);
}

.summary-strip__hint:active {
  color: var(--ft-accent-primary);
}

.summary-strip__value {
  margin: 0;

  font-size: clamp(1.5rem, 2.5vw, 2rem);
  font-weight: var(--ft-font-bold);
  font-variant-numeric: tabular-nums;
  line-height: 1.15;
  color: var(--ft-text-primary);
}

.summary-strip__value--income {
  color: var(--ft-success-400);
}

.summary-strip__value--expense {
  color: var(--ft-danger-400);
}

.summary-strip__value--good {
  color: var(--ft-success-400);
}

.summary-strip__value--poor {
  color: var(--ft-danger-400);
}

.summary-strip__secondary {
  margin: 0;
  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.summary-strip__error {
  grid-column: 1 / -1;
}

.summary-strip__error-body {
  display: flex;
  gap: var(--ft-space-3);
  align-items: center;
}

.summary-strip__error-title {
  margin: 0;
  font-weight: var(--ft-font-semibold);
}

@media (width <= 640px) {
  .summary-strip {
    grid-template-columns: 1fr;
    gap: var(--ft-space-2);
    padding: var(--ft-space-4);
  }

  .summary-strip__item {
    padding: var(--ft-space-2);
  }

  .summary-strip__value {
    font-size: 1.25rem;
  }

  .summary-strip__icon {
    width: 38px;
    height: 38px;
    font-size: 1rem;
  }
}
</style>

// react-app/src/components/analytics/SummaryStrip.tsx
import { createElement } from 'react';
import {
  TrendingDown,
  Banknote,
  Activity,
  Wallet,
  type LucideIcon,
  AlertCircle,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { InfoTooltip } from './InfoTooltip';
import type { MetricAccent, SummaryMetric } from './models';

interface SummaryStripProps {
  loading: boolean;
  error: string | null;
  metrics: SummaryMetric[];
  onRetry: () => void;
}

// ─── Icon map ─────────────────────────────────────────────────────────────────

const ICON_MAP: Record<string, LucideIcon> = {
  TrendingDown,
  Banknote,
  Activity,
  Wallet,
};

function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Activity;
}

// ─── Accent helpers ───────────────────────────────────────────────────────────

function accentBgStyle(accent: MetricAccent): React.CSSProperties {
  switch (accent) {
    case 'income':
    case 'good':
      return {
        backgroundColor: 'color-mix(in srgb, var(--ft-success-500) 15%, transparent)',
        color: 'var(--ft-success-500)',
      };
    case 'expense':
    case 'poor':
      return {
        backgroundColor: 'color-mix(in srgb, var(--ft-danger-500) 15%, transparent)',
        color: 'var(--ft-danger-500)',
      };
    case 'warning':
      return {
        backgroundColor: 'color-mix(in srgb, var(--ft-warning-500) 16%, transparent)',
        color: 'var(--ft-warning-400)',
      };
    case 'neutral':
    default:
      return {
        backgroundColor: 'color-mix(in srgb, var(--ft-text-secondary) 10%, transparent)',
        color: 'var(--ft-text-secondary)',
      };
  }
}

// ─── MetricCard ───────────────────────────────────────────────────────────────

interface MetricCardProps {
  metric: SummaryMetric;
}

function MetricCard({ metric }: MetricCardProps) {
  const iconStyle = accentBgStyle(metric.accent);
  const valueColor =
    metric.accent === 'income' || metric.accent === 'good'
      ? 'var(--ft-success-400)'
      : metric.accent === 'expense' || metric.accent === 'poor'
        ? 'var(--ft-danger-400)'
        : metric.accent === 'warning'
          ? 'var(--ft-warning-300)'
          : 'var(--ft-text-primary)';

  return (
    <div className="flex min-h-[156px] flex-col justify-between gap-5 px-6 py-5">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-4">
          <div
            className="flex size-14 shrink-0 items-center justify-center rounded-full"
            style={iconStyle}
            aria-hidden="true"
          >
            {createElement(resolveIcon(metric.icon), { className: 'size-6' })}
          </div>

          <span className="pt-2 text-xs font-semibold uppercase tracking-[0.08em] text-[var(--ft-text-secondary)]">
            {metric.label}
          </span>
        </div>

        <InfoTooltip
          content={metric.tooltip}
          className="-mt-2 -mr-2"
          ariaLabel={`Подробнее: ${metric.label}`}
        />
      </div>

      <div
        className="flex min-w-0 flex-1 flex-col justify-end gap-2"
        style={{ fontVariantNumeric: 'tabular-nums' }}
      >
        <span
          className="text-[clamp(2.1rem,3vw,2.65rem)] font-bold leading-none"
          style={{ color: valueColor }}
        >
          {metric.value}
        </span>

        {metric.secondary && (
          <span className="text-sm text-[var(--ft-text-secondary)]">
            {metric.secondary}
          </span>
        )}
      </div>
    </div>
  );
}

// ─── Loading skeleton ─────────────────────────────────────────────────────────

const SKELETON_KEYS = ['alpha', 'beta', 'gamma'] as const;

function StripSkeleton() {
  return (
    <div
      className="overflow-hidden rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
      }}
      role="status"
      aria-busy="true"
      aria-label="Загрузка метрик"
    >
      <div className="grid grid-cols-1 divide-y divide-[var(--ft-border-subtle)] md:grid-cols-3 md:divide-x md:divide-y-0">
        {SKELETON_KEYS.map((key) => (
          <div key={key} className="flex min-h-[156px] flex-col justify-between gap-5 px-6 py-5">
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-4">
                <Skeleton className="size-14 rounded-full" />
                <Skeleton className="mt-2 h-4 w-28" />
              </div>
              <Skeleton className="size-10 rounded-full" />
            </div>
            <div className="flex flex-col gap-3">
              <Skeleton className="h-10 w-44" />
              <Skeleton className="h-5 w-36" />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── SummaryStrip ─────────────────────────────────────────────────────────────

export function SummaryStrip({ loading, error, metrics, onRetry }: SummaryStripProps) {
  if (loading) {
    return <StripSkeleton />;
  }

  if (error) {
    return (
      <div
        className="flex min-h-[170px] flex-col items-center justify-center gap-4 rounded-[28px] border border-destructive/30 bg-destructive/10 p-6 text-center"
        role="alert"
      >
        <AlertCircle className="size-8 text-destructive" aria-hidden="true" />
        <div className="flex flex-col gap-1">
          <p className="font-medium text-foreground">Не удалось загрузить метрики</p>
          <p className="text-sm text-muted-foreground">{error}</p>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="min-h-[44px]"
          onClick={onRetry}
        >
          Повторить
        </Button>
      </div>
    );
  }

  return (
    <section
      className="overflow-hidden rounded-[28px] border border-[var(--ft-border-default)] shadow-[var(--ft-shadow-lg)]"
      style={{
        background:
          'linear-gradient(180deg, color-mix(in srgb, var(--ft-surface-raised) 84%, var(--ft-bg-base)) 0%, var(--ft-surface-base) 100%)',
      }}
    >
      <div className="grid grid-cols-1 divide-y divide-[var(--ft-border-subtle)] md:grid-cols-3 md:divide-x md:divide-y-0">
        {metrics.map((metric) => (
          <MetricCard key={metric.key} metric={metric} />
        ))}
      </div>
    </section>
  );
}
