// vue-app/src/pages/RegisterPage.vue
<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import UiButton from '../ui/UiButton.vue'
import UiCard from '../ui/UiCard.vue'
import UiInputText from '../ui/UiInputText.vue'
import ThemeToggle from '../components/common/ThemeToggle.vue'

const router = useRouter()
const authStore = useAuthStore()

const showEmailForm = ref(false)
const email = ref('')
const password = ref('')
const showPassword = ref(false)
const telegramMount = ref<HTMLElement | null>(null)
const telegramScript = ref<HTMLScriptElement | null>(null)
const telegramLoaded = ref(false)

const hasPasswordInput = computed(() => password.value.length > 0)

const passwordRules = computed(() => {
  const value = password.value

  return [
    { key: 'length', label: 'Минимум 8 символов', met: value.length >= 8 },
    { key: 'lowercase', label: 'Строчная буква (a-z)', met: /[a-z]/.test(value) },
    { key: 'uppercase', label: 'Заглавная буква (A-Z)', met: /[A-Z]/.test(value) },
    { key: 'digit', label: 'Цифра (0-9)', met: /\d/.test(value) },
    { key: 'special', label: 'Спецсимвол (!@#$...)', met: /[^a-zA-Z0-9]/.test(value) }
  ]
})

const allRulesMet = computed(() => passwordRules.value.every(rule => rule.met))

const isDisabled = computed(() => {
  return authStore.isLoading || !email.value || !password.value || !allRulesMet.value
})

onMounted(() => {
  authStore.clearError()
  if (authStore.isAuthenticated) {
    void router.push('/analytics')
  }

  const botName = (import.meta.env.VITE_TELEGRAM_BOT_NAME as string | undefined) ?? 'financetree_bot'
  const mount = telegramMount.value
  if (!mount) return

  const handleTelegramAuth = async (payload: {
    id: number
    auth_date: number
    hash: string
    first_name?: string
    last_name?: string
    username?: string
    photo_url?: string
  }) => {
    const success = await authStore.loginWithTelegram(payload)
    if (success) {
      router.push('/analytics')
    }
  }

  ;(window as Window & { onTelegramAuth?: typeof handleTelegramAuth }).onTelegramAuth = handleTelegramAuth

  const script = document.createElement('script')
  script.async = true
  script.src = 'https://telegram.org/js/telegram-widget.js?22'
  script.setAttribute('data-telegram-login', botName)
  script.setAttribute('data-size', 'large')
  script.setAttribute('data-radius', '12')
  script.setAttribute('data-userpic', 'false')
  script.setAttribute('data-onauth', 'onTelegramAuth(user)')
  script.setAttribute('data-request-access', 'write')

  script.onload = () => {
    telegramLoaded.value = true
  }

  script.onerror = () => {
    telegramLoaded.value = false
  }

  mount.appendChild(script)
  telegramScript.value = script

  setTimeout(() => {
    if (!telegramLoaded.value) {
      telegramLoaded.value = false
    }
  }, 5000)
})

onBeforeUnmount(() => {
  const script = telegramScript.value
  if (script?.parentElement) {
    script.parentElement.removeChild(script)
  }
  if ((window as Window & { onTelegramAuth?: unknown }).onTelegramAuth) {
    delete (window as Window & { onTelegramAuth?: unknown }).onTelegramAuth
  }
})

const handleRegister = async () => {
  if (isDisabled.value) return
  const success = await authStore.register({
    email: email.value,
    password: password.value,
    passwordConfirmation: password.value
  })

  if (success) {
    router.push('/analytics')
  }
}
</script>

<template>
  <div class="auth">
    <div class="auth__theme-toggle">
      <ThemeToggle />
    </div>

    <div class="auth__center">
      <router-link
        to="/"
        class="auth__brand"
      >
        <i class="pi pi-chart-bar" />
        <span>FinTree</span>
      </router-link>

      <h1 class="auth__title">
        Начните учет финансов
      </h1>

      <UiCard
        class="auth__card"
        variant="muted"
        padding="lg"
      >
        <div class="auth__telegram">
          <p class="auth__telegram-label">
            Регистрация через Telegram
          </p>
          <div
            ref="telegramMount"
            class="auth__telegram-widget"
          />
          <p
            v-if="telegramLoaded === false && !telegramScript"
            class="auth__telegram-fallback"
          >
            Виджет Telegram не загрузился.
            <button
              type="button"
              class="auth__link-btn"
              @click="showEmailForm = true"
            >
              Зарегистрируйтесь через Email
            </button>
          </p>
        </div>

        <div class="auth__divider">
          <span>или</span>
        </div>

        <div v-if="!showEmailForm">
          <button
            type="button"
            class="auth__email-toggle"
            @click="showEmailForm = true"
          >
            Зарегистрироваться через Email
          </button>
        </div>

        <form
          v-else
          class="auth__form"
          @submit.prevent="handleRegister"
        >
          <div class="auth__field">
            <label for="reg-email">Email</label>
            <UiInputText
              id="reg-email"
              v-model="email"
              type="email"
              placeholder="name@domain.com"
              autocomplete="email"
            />
          </div>

          <div class="auth__field">
            <label for="reg-password">Пароль</label>
            <div class="auth__password-wrap">
              <UiInputText
                id="reg-password"
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                placeholder="Минимум 8 символов"
                autocomplete="new-password"
              />
              <button
                type="button"
                class="auth__eye"
                :aria-label="showPassword ? 'Скрыть пароль' : 'Показать пароль'"
                tabindex="-1"
                @click="showPassword = !showPassword"
              >
                <i :class="showPassword ? 'pi pi-eye-slash' : 'pi pi-eye'" />
              </button>
            </div>
            <ul
              v-if="hasPasswordInput"
              class="auth__rules"
            >
              <li
                v-for="rule in passwordRules"
                :key="rule.key"
                :class="{ 'auth__rule--ok': rule.met, 'auth__rule--fail': hasPasswordInput && !rule.met }"
              >
                <i :class="rule.met ? 'pi pi-check' : 'pi pi-times'" />
                <span>{{ rule.label }}</span>
              </li>
            </ul>
          </div>

          <p
            v-if="authStore.error"
            class="auth__error"
          >
            <i class="pi pi-exclamation-circle" />
            <span>{{ authStore.error }}</span>
          </p>

          <UiButton
            type="submit"
            label="Создать аккаунт"
            :loading="authStore.isLoading"
            :disabled="isDisabled"
            block
          />
        </form>

        <footer class="auth__footer">
          <span>Уже есть аккаунт?</span>
          <router-link to="/login">
            Войти
          </router-link>
        </footer>
      </UiCard>
    </div>
  </div>
</template>

<style scoped>
.auth {
  position: relative;

  display: grid;
  place-items: center;

  min-height: 100vh;
  padding: clamp(var(--ft-space-6), 6vw, var(--ft-space-10)) clamp(var(--ft-space-4), 6vw, var(--ft-space-8));

  color: var(--ft-text-primary);

  background:
    radial-gradient(
      760px 560px at 50% -10%,
      color-mix(in srgb, var(--ft-primary-500) 24%, transparent),
      transparent
    ),
    linear-gradient(180deg, var(--ft-bg-base) 0%, var(--ft-bg-muted) 100%);
}

.auth__theme-toggle {
  position: absolute;
  z-index: var(--ft-z-above);
  top: clamp(var(--ft-space-4), 4vw, var(--ft-space-6));
  right: clamp(var(--ft-space-4), 4vw, var(--ft-space-6));
}

.auth__center {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);
  align-items: center;

  width: 100%;
  max-width: 420px;

  text-align: center;
}

.auth__brand {
  display: inline-flex;
  gap: var(--ft-space-2);
  align-items: center;

  font-family: var(--ft-font-display);
  font-weight: var(--ft-font-semibold);
  color: var(--ft-primary-200);
  text-decoration: none;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.light-mode .auth__brand {
  color: var(--ft-primary-700);
}

.auth__title {
  margin: 0;
  font-family: var(--ft-font-display);
  font-size: clamp(1.5rem, 4vw, 2rem);
  line-height: 1.2;
}

.auth__card {
  width: 100%;

  background: var(--ft-surface-base);
  backdrop-filter: blur(18px);
  border: 1px solid var(--ft-border-subtle);
  box-shadow: var(--ft-shadow-xl);
}

.auth__telegram {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-3);
  align-items: center;

  text-align: center;
}

.auth__telegram-label {
  margin: 0;
  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-primary);
}

.auth__telegram-widget {
  display: flex;
  justify-content: center;
  min-height: 44px;
}

.auth__telegram-fallback {
  margin: 0;
  font-size: var(--ft-text-xs);
  color: var(--ft-text-tertiary);
}

.auth__link-btn {
  cursor: pointer;

  padding: 0;

  font-size: inherit;
  color: var(--ft-primary-400);
  text-decoration: underline;

  background: none;
  border: none;
}

.auth__link-btn:hover {
  color: var(--ft-primary-300);
}

.auth__divider {
  position: relative;

  display: grid;
  place-items: center;

  margin: var(--ft-space-1) 0;

  font-size: var(--ft-text-xs);
  color: var(--ft-text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.16em;
}

.auth__divider::before {
  content: '';

  position: absolute;
  inset: 50% 0 auto;

  height: 1px;

  opacity: 0.6;
  background: var(--ft-border-subtle);
}

.auth__divider span {
  position: relative;
  padding: 0 var(--ft-space-3);
  background: var(--ft-surface-base);
}

.auth__email-toggle {
  cursor: pointer;

  display: block;

  width: 100%;
  padding: var(--ft-space-3);

  font-size: var(--ft-text-sm);
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-secondary);
  text-align: center;

  background: none;
  border: 1px solid var(--ft-border-subtle);
  border-radius: var(--ft-radius-md);

  transition:
    color var(--ft-transition-fast),
    border-color var(--ft-transition-fast);
}

.auth__email-toggle:hover {
  color: var(--ft-text-primary);
  border-color: var(--ft-border-default);
}

.auth__form {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-4);
}

.auth__field {
  display: flex;
  flex-direction: column;
  gap: var(--ft-space-2);
  text-align: left;
}

.auth__field > label {
  font-size: var(--ft-text-xs);
  color: var(--ft-text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.14em;
}

.auth__password-wrap {
  position: relative;
}

.auth__password-wrap :deep(input) {
  padding-right: var(--ft-space-10);
}

.auth__eye {
  cursor: pointer;

  position: absolute;
  top: 50%;
  right: var(--ft-space-3);
  transform: translateY(-50%);

  display: grid;
  place-items: center;

  padding: 0;

  font-size: 1rem;
  color: var(--ft-text-tertiary);

  background: none;
  border: none;

  transition: color var(--ft-transition-fast);
}

.auth__eye:hover {
  color: var(--ft-text-primary);
}

.auth__rules {
  display: grid;
  gap: var(--ft-space-1);

  margin: 0;
  padding: 0;

  list-style: none;
}

.auth__rules li {
  display: flex;
  gap: var(--ft-space-2);
  align-items: center;

  font-size: var(--ft-text-xs);
  color: var(--ft-text-tertiary);
}

.auth__rules li i {
  font-size: 0.75rem;
}

.auth__rule--ok {
  color: var(--ft-success-400);
}

.auth__rule--fail {
  color: var(--ft-danger-400);
}

.auth__error {
  display: flex;
  gap: var(--ft-space-2);
  align-items: center;

  margin: 0;

  font-size: var(--ft-text-sm);
  color: var(--ft-danger-400);
}

.auth__footer {
  display: flex;
  gap: var(--ft-space-2);
  justify-content: center;

  margin-top: var(--ft-space-2);

  font-size: var(--ft-text-sm);
  color: var(--ft-text-secondary);
}

.auth__footer a {
  font-weight: var(--ft-font-medium);
  color: var(--ft-text-primary);
  text-decoration: none;
}

.auth__footer a:hover {
  text-decoration: underline;
}
</style>

// react-app/src/pages/RegisterPage.tsx
import { useEffect, useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { Link, useNavigate } from '@tanstack/react-router';
import { Check, X } from 'lucide-react';
import { useForm, useWatch } from 'react-hook-form';
import {
  AuthDivider,
  AuthErrorMessage,
} from '@/components/auth/AuthContentParts';
import { AuthPageLayout } from '@/components/auth/AuthPageLayout';
import { PasswordInput } from '@/components/auth/PasswordInput';
import { TelegramAuthWidget } from '@/components/auth/TelegramAuthWidget';
import { FormField } from '@/components/common/FormField';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useAuth } from '@/hooks/useAuth';
import { PATHS } from '@/router/paths';
import type { TelegramLoginPayload } from '@/types';
import { registerSchema, type RegisterFormValues } from '@/utils/schemas';

const PASSWORD_RULES = [
  {
    key: 'length',
    label: 'Минимум 8 символов',
    check: (value: string) => value.length >= 8,
  },
  {
    key: 'lowercase',
    label: 'Строчная буква (a-z)',
    check: (value: string) => /[a-z]/.test(value),
  },
  {
    key: 'uppercase',
    label: 'Заглавная буква (A-Z)',
    check: (value: string) => /[A-Z]/.test(value),
  },
  {
    key: 'digit',
    label: 'Цифра (0-9)',
    check: (value: string) => /\d/.test(value),
  },
  {
    key: 'special',
    label: 'Хотя бы один спецсимвол',
    check: (value: string) => /[^a-zA-Z0-9]/.test(value),
  },
] as const;

export default function RegisterPage() {
  const navigate = useNavigate();
  const {
    clearError,
    error,
    isLoading,
    loginWithTelegram,
    register,
  } = useAuth();
  const [showEmailForm, setShowEmailForm] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const form = useForm<RegisterFormValues>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  });

  const [email, password] = useWatch({
    control: form.control,
    name: ['email', 'password'],
  });
  const hasPasswordInput = password.length > 0;

  const passwordRules = PASSWORD_RULES.map((rule) => ({
    ...rule,
    met: rule.check(password),
  }));

  const allRulesMet = passwordRules.every((rule) => rule.met);

  useEffect(() => {
    clearError();

    return () => {
      clearError();
    };
  }, [clearError]);

  const handleTelegramAuth = async (payload: TelegramLoginPayload) => {
    const isAuthenticated = await loginWithTelegram(payload);

    if (isAuthenticated) {
      await navigate({ to: PATHS.ANALYTICS });
    }

    return isAuthenticated;
  };

  const handleRegister = form.handleSubmit(async (values) => {
    const isAuthenticated = await register({
      email: values.email,
      password: values.password,
      passwordConfirmation: values.password,
    });

    if (isAuthenticated) {
      await navigate({ to: PATHS.ANALYTICS });
    }
  });

  return (
    <AuthPageLayout
      title="Начните учет финансов"
      description="Создайте аккаунт через Telegram или откройте email-регистрацию."
    >
      <Card
        className="overflow-hidden rounded-[1.75rem] border border-border/70 bg-[color-mix(in_srgb,var(--ft-surface-raised)_88%,transparent)] shadow-(--ft-shadow-2xl) backdrop-blur-xl"
      >
        <CardContent className="space-y-6 px-5 pt-5 pb-6 sm:px-6 sm:pt-6">
          <TelegramAuthWidget
            mode="register"
            label="Регистрация через Telegram"
            fallback={
              <>
                Виджет Telegram не загрузился.{' '}
                <button
                  type="button"
                  className="font-medium text-primary underline decoration-primary/50 underline-offset-4 transition-colors hover:text-primary/80"
                  onClick={() => setShowEmailForm(true)}
                >
                  Зарегистрируйтесь через Email
                </button>
              </>
            }
            onAuthenticate={handleTelegramAuth}
          />

          <AuthDivider label="или" />

          {!showEmailForm ? (
            <Button
              type="button"
              variant="outline"
              size="lg"
              className="min-h-12 w-full rounded-xl"
              onClick={() => setShowEmailForm(true)}
            >
              Зарегистрироваться через Email
            </Button>
          ) : (
            <form className="space-y-4" onSubmit={handleRegister} noValidate>
              <FormField
                id="register-email"
                label="Email"
                required
                error={form.formState.errors.email?.message}
                className="text-left"
              >
                <Input
                  type="email"
                  placeholder="name@domain.com"
                  autoComplete="email"
                  {...form.register('email')}
                />
              </FormField>

              <FormField
                id="register-password"
                label="Пароль"
                required
                error={form.formState.errors.password?.message}
                className="text-left"
              >
                <PasswordInput
                  placeholder="Минимум 8 символов"
                  autoComplete="new-password"
                  visible={showPassword}
                  onToggleVisibility={() => setShowPassword((current) => !current)}
                  {...form.register('password')}
                />
              </FormField>

              {hasPasswordInput ? (
                <ul className="grid gap-1.5 text-xs">
                  {passwordRules.map((rule) => (
                    <li
                      key={rule.key}
                      className={
                        rule.met
                          ? 'flex items-center gap-2 text-[var(--ft-success-500)]'
                          : 'flex items-center gap-2 text-destructive'
                      }
                    >
                      {rule.met ? (
                        <Check className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
                      ) : (
                        <X className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
                      )}
                      <span>{rule.label}</span>
                    </li>
                  ))}
                </ul>
              ) : null}

              {error ? <AuthErrorMessage message={error} /> : null}

              <Button
                type="submit"
                size="lg"
                className="min-h-12 w-full rounded-xl"
                disabled={isLoading || !email || !password || !allRulesMet}
              >
                {isLoading ? 'Создаём аккаунт…' : 'Создать аккаунт'}
              </Button>
            </form>
          )}
        </CardContent>

        <CardFooter className="justify-center gap-2 border-t border-border/60 bg-background/25 text-sm">
          <span className="text-muted-foreground">Уже есть аккаунт?</span>
          <Link
            to={PATHS.LOGIN}
            className="font-medium text-foreground transition-colors hover:text-primary hover:underline"
          >
            Войти
          </Link>
        </CardFooter>
      </Card>
    </AuthPageLayout>
  );
}
